module.exports = async function (knex) {
  await knex('player').insert([{
    player: 'ARI',
    fname: 'Arizona',
    lname: 'Cardinals',
    pname: 'ARI',
    pos1: 'DST',
    cteam: 'ARI'
  }, {
    player: 'ATL',
    fname: 'Atlanta',
    lname: 'Falcons',
    pname: 'ATL',
    pos1: 'DST',
    cteam: 'ATL'
  }, {
    player: 'BAL',
    fname: 'Baltimore',
    lname: 'Ravens',
    pname: 'BAL',
    pos1: 'DST',
    cteam: 'BAL'
  }, {
    player: 'BUF',
    fname: 'Buffalo',
    lname: 'Bills',
    pname: 'BUF',
    pos1: 'DST'
  }, {
    player: 'CAR',
    fname: 'Carolina',
    lname: 'Panthers',
    pname: 'CAR',
    pos1: 'DST',
    cteam: 'CAR'
  }, {
    player: 'CHI',
    fname: 'Chicago',
    lname: 'Bears',
    pname: 'CHI',
    pos1: 'DST',
    cteam: 'CHI'
  }, {
    player: 'CIN',
    fname: 'Cincinnati',
    lname: 'Bengals',
    pname: 'CIN',
    pos1: 'DST',
    cteam: 'CIN'
  }, {
    player: 'CLE',
    fname: 'Cleveland',
    lname: 'Browns',
    pname: 'CLE',
    pos1: 'DST',
    cteam: 'CLE'
  }, {
    player: 'DAL',
    fname: 'Dallas',
    lname: 'Cowboys',
    pname: 'DAL',
    pos1: 'DST',
    cteam: 'DAL'
  }, {
    player: 'DEN',
    fname: 'Denver',
    lname: 'Broncos',
    pname: 'DEN',
    pos1: 'DST',
    cteam: 'DEN'
  }, {
    player: 'DET',
    fname: 'Detroit',
    lname: 'Lions',
    pname: 'DET',
    pos1: 'DST',
    cteam: 'DET'
  }, {
    player: 'GB',
    fname: 'Green Bay',
    lname: 'Packers',
    pname: 'GB',
    pos1: 'DST',
    cteam: 'GB'
  }, {
    player: 'HOU',
    fname: 'Houston',
    lname: 'Texans',
    pname: 'HOU',
    pos1: 'DST',
    cteam: 'HOU'
  }, {
    player: 'IND',
    fname: 'Indianapolis',
    lname: 'Colts',
    pname: 'IND',
    pos1: 'DST',
    cteam: 'IND'
  }, {
    player: 'JAC',
    fname: 'Jacksonville',
    lname: 'Jaguars',
    pname: 'JAC',
    pos1: 'DST',
    cteam: 'JAC'
  }, {
    player: 'KC',
    fname: 'Kansas City',
    lname: 'Chiefs',
    pname: 'KC',
    pos1: 'DST',
    cteam: 'KC'
  }, {
    player: 'LA',
    fname: 'Los Angeles',
    lname: 'Rams',
    pname: 'LA',
    pos1: 'DST',
    cteam: 'LA'
  }, {
    player: 'LAC',
    fname: 'Los Angeles',
    lname: 'Chargers',
    pname: 'LAC',
    pos1: 'DST',
    cteam: 'LAC'
  }, {
    player: 'LV',
    fname: 'Las Vegas',
    lname: 'Raiders',
    pname: 'LV',
    pos1: 'DST',
    cteam: 'LV'
  }, {
    player: 'MIA',
    fname: 'Miami',
    lname: 'Dolphins',
    pname: 'MIA',
    pos1: 'DST',
    cteam: 'MIA'
  }, {
    player: 'MIN',
    fname: 'Minnesota',
    lname: 'Vikings',
    pname: 'MINT',
    pos1: 'DST',
    cteam: 'MIN'
  }, {
    player: 'NE',
    fname: 'New England',
    lname: 'Patriots',
    pname: 'NE',
    pos1: 'DST',
    cteam: 'NE'
  }, {
    player: 'NO',
    fname: 'New Orleans',
    lname: 'Saints',
    pname: 'NO',
    pos1: 'DST',
    cteam: 'NO'
  }, {
    player: 'NYG',
    fname: 'New York',
    lname: 'Giants',
    pname: 'NYG',
    pos1: 'DST',
    cteam: 'NYG'
  }, {
    player: 'NYJ',
    fname: 'New York',
    lname: 'Jets',
    pname: 'NYJ',
    pos1: 'DST',
    cteam: 'NYJ'
  }, {
    player: 'PHI',
    fname: 'Philadelphia',
    lname: 'Eagles',
    pname: 'PHI',
    pos1: 'DST',
    cteam: 'PHI'
  }, {
    player: 'PIT',
    fname: 'Pittsburgh',
    lname: 'Steelers',
    pname: 'PIT',
    pos1: 'DST',
    cteam: 'PIT'
  }, {
    player: 'SEA',
    fname: 'Seattle',
    lname: 'Seahawks',
    pname: 'SEA',
    pos1: 'DST',
    cteam: 'SEA'
  }, {
    player: 'SF',
    fname: 'San Francisco',
    lname: '49ers',
    pname: 'SF',
    pos1: 'DST',
    cteam: 'SF'
  }, {
    player: 'TB',
    fname: 'Tampa Bay',
    lname: 'Buccaneers',
    pname: 'TB',
    pos1: 'DST',
    cteam: 'TB'
  }, {
    player: 'TEN',
    fname: 'Tennessee',
    lname: 'Titans',
    pname: 'TEN',
    pos1: 'DST',
    cteam: 'TEN'
  }, {
    player: 'WAS',
    fname: 'Washington',
    lname: 'Redskins',
    pname: 'WAS',
    pos1: 'DST',
    cteam: 'WAS',
  }])
}
