export default {
  'Arizona (ARI)': 'ARI',
  'Atlanta (ATL)': 'ATL',
  'Baltimore (BAL)': 'BAL',
  'Buffalo (BUF)': 'BUF',
  'Carolina (CAR)': 'CAR',
  'Chicago (CHI)': 'CHI',
  'Cincinnati (CIN)': 'CIN',
  'Cleveland (CLE)': 'CLE',
  'Dallas (DAL)': 'DAL',
  'Denver (DEN)': 'DEN',
  'Detroit (DET)': 'DET',
  'Green Bay (GB)': 'GB',
  'Houston (HOU)': 'HOU',
  'Indianapolis (IND)': 'IND',
  'Jacksonville (JAC)': 'JAX',
  'Kansas City (KC)': 'KC',
  'Los Angeles (LAC)': 'LAC',
  'Los Angeles (LAR)': 'LA',
  'Las Vegas (LV)': 'LV',
  'Miami (MIA)': 'MIA',
  'Minnesota (MIN)': 'MIN',
  'New England (NE)': 'NE',
  'New Orleans (NO)': 'NO',
  'New York (NYG)': 'NYG',
  'New York (NYJ)': 'NYJ',
  'Philadelphia (PHI)': 'PHI',
  'Pittsburgh (PIT)': 'PIT',
  'Seattle (SEA)': 'SEA',
  'San Francisco (SF)': 'SF',
  'Tampa Bay (TB)': 'TB',
  'Tennessee (TEN)': 'TEN',
  'Washington (WAS)': 'WAS',

  '49ers D/ST': 'SF',
  '49ers DST': 'SF',
  'Bears D/ST': 'CHI',
  'Bears DST': 'CHI',
  'Bengals D/ST': 'CIN',
  'Bengals DST': 'CIN',
  'Bills D/ST': 'BUF',
  'Bills DST': 'BUF',
  'Broncos D/ST': 'DEN',
  'Broncos DST': 'DEN',
  'Browns D/ST': 'CLE',
  'Browns DST': 'CLE',
  'Buccaneers D/ST': 'TB',
  'Buccaneers DST': 'TB',
  'Cardinals D/ST': 'ARI',
  'Cardinals DST': 'ARI',
  'Chargers D/ST': 'LAC',
  'Chargers DST': 'LAC',
  'Chiefs D/ST': 'KC',
  'Chiefs DST': 'KC',
  'Colts D/ST': 'IND',
  'Colts DST': 'IND',
  'Cowboys D/ST': 'DAL',
  'Cowboys DST': 'DAL',
  'Dolphins D/ST': 'MIA',
  'Dolphins DST': 'MIA',
  'Eagles D/ST': 'PHI',
  'Eagles DST': 'PHI',
  'Falcons D/ST': 'ATL',
  'Falcons DST': 'ATL',
  'Giants D/ST': 'NYG',
  'Giants DST': 'NYG',
  'Jaguars D/ST': 'JAX',
  'Jaguars DST': 'JAX',
  'Jets D/ST': 'NYJ',
  'Jets DST': 'NYJ',
  'Lions D/ST': 'DET',
  'Lions DST': 'DET',
  'Packers D/ST': 'GB',
  'Packers DST': 'GB',
  'Panthers D/ST': 'CAR',
  'Panthers DST': 'CAR',
  'Patriots D/ST': 'NE',
  'Patriots DST': 'NE',
  'Raiders D/ST': 'LV',
  'Raiders DST': 'LV',
  'Rams D/ST': 'LA',
  'Rams DST': 'LA',
  'Ravens D/ST': 'BAL',
  'Ravens DST': 'BAL',
  'Redskins D/ST': 'WAS',
  'Redskins DST': 'WAS',
  'Saints D/ST': 'NO',
  'Saints DST': 'NO',
  'Seahawks D/ST': 'SEA',
  'Seahawks DST': 'SEA',
  'Steelers D/ST': 'PIT',
  'Steelers DST': 'PIT',
  'Texans D/ST': 'HOU',
  'Texans DST': 'HOU',
  'Titans D/ST': 'TEN',
  'Titans DST': 'TEN',
  'Vikings D/ST': 'MIN',
  'Vikings DST': 'MIN',
  'Washington D/ST': 'WAS',
  'Washington DST': 'WAS',
  'Football Team DST': 'WAS',
  'Commanders D/ST': 'WAS',
  'Commanders DST': 'WAS',

  'Arizona Cardinals': 'ARI',
  'Atlanta Falcons': 'ATL',
  'Baltimore Ravens': 'BAL',
  'Buffalo Bills': 'BUF',
  'Carolina Panthers': 'CAR',
  'Chicago Bears': 'CHI',
  'Cincinnati Bengals': 'CIN',
  'Cleveland Browns': 'CLE',
  'Dallas Cowboys': 'DAL',
  'Denver Broncos': 'DEN',
  'Detroit Lions': 'DET',
  'Green Bay Packers': 'GB',
  'Houston Texans': 'HOU',
  'Indianapolis Colts': 'IND',
  'Jacksonville Jaguars': 'JAX',
  'Kansas City Chiefs': 'KC',
  'Las Vegas Raiders': 'LV',
  'Los Angeles Chargers': 'LAC',
  'Los Angeles Rams': 'LA',
  'Miami Dolphins': 'MIA',
  'Minnesota Vikings': 'MIN',
  'New England Patriots': 'NE',
  'New Orleans Saints': 'NO',
  'New York Giants': 'NYG',
  'New York Jets': 'NYJ',
  'Philadelphia Eagles': 'PHI',
  'Pittsburgh Steelers': 'PIT',
  'San Francisco 49ers': 'SF',
  'Seattle Seahawks': 'SEA',
  'Tampa Bay Buccaneers': 'TB',
  'Tennessee Titans': 'TEN',
  'Washington Commanders': 'WAS',
  'Washington Football Team': 'WAS',

  '49ers Defense': 'SF_DEF',
  'Bears Defense': 'CHI_DEF',
  'Bengals Defense': 'CIN_DEF',
  'Bills Defense': 'BUF_DEF',
  'Broncos Defense': 'DEN_DEF',
  'Browns Defense': 'CLE_DEF',
  'Buccaneers Defense': 'TB_DEF',
  'Cardinals Defense': 'ARI_DEF',
  'Chargers Defense': 'LAC_DEF',
  'Chiefs Defense': 'KC_DEF',
  'Colts Defense': 'IND_DEF',
  'Commanders Defense': 'WAS_DEF',
  'Cowboys Defense': 'DAL_DEF',
  'Dolphins Defense': 'MIA_DEF',
  'Eagles Defense': 'PHI_DEF',
  'Falcons Defense': 'ATL_DEF',
  'Giants Defense': 'NYG_DEF',
  'Jaguars Defense': 'JAX_DEF',
  'Jets Defense': 'NYJ_DEF',
  'Lions Defense': 'DET_DEF',
  'Packers Defense': 'GB_DEF',
  'Panthers Defense': 'CAR_DEF',
  'Patriots Defense': 'NE_DEF',
  'Raiders Defense': 'LV_DEF',
  'Rams Defense': 'LA_DEF',
  'Ravens Defense': 'BAL_DEF',
  'Redskins Defense': 'WAS_DEF',
  'Saints Defense': 'NO_DEF',
  'Seahawks Defense': 'SEA_DEF',
  'Steelers Defense': 'PIT_DEF',
  'Texans Defense': 'HOU_DEF',
  'Titans Defense': 'TEN_DEF',
  'Vikings Defense': 'MIN_DEF',

  'Arizona Defense': 'ARI_DEF',
  'Atlanta Defense': 'ATL_DEF',
  'Baltimore Defense': 'BAL_DEF',
  'Buffalo Defense': 'BUF_DEF',
  'Carolina Defense': 'CAR_DEF',
  'Chicago Defense': 'CHI_DEF',
  'Cincinnati Defense': 'CIN_DEF',
  'Cleveland Defense': 'CLE_DEF',
  'Dallas Defense': 'DAL_DEF',
  'Denver Defense': 'DEN_DEF',
  'Detroit Defense': 'DET_DEF',
  'Green Bay Defense': 'GB_DEF',
  'Houston Defense': 'HOU_DEF',
  'Indianapolis Defense': 'IND_DEF',
  'Jacksonville Defense': 'JAX_DEF',
  'Kansas City Defense': 'KC_DEF',
  'Las Vegas Defense': 'LV_DEF',
  'Los Angeles Chargers Defense': 'LAC_DEF',
  'Los Angeles Rams Defense': 'LA_DEF',
  'Miami Defense': 'MIA_DEF',
  'Minnesota Defense': 'MIN_DEF',
  'New England Defense': 'NE_DEF',
  'New Orleans Defense': 'NO_DEF',
  'New York Giants Defense': 'NYG_DEF',
  'New York Jets Defense': 'NYJ_DEF',
  'Philadelphia Defense': 'PHI_DEF',
  'Pittsburgh Defense': 'PIT_DEF',
  'San Francisco Defense': 'SF_DEF',
  'Seattle Defense': 'SEA_DEF',
  'Tampa Bay Defense': 'TB_DEF',
  'Tennessee Defense': 'TEN_DEF',
  'Washington Defense': 'WAS_DEF'
}
