-- STATUS: PENDING
--
-- Give every mutation of a bid a row of its own, so a bid's history stops being
-- unrecoverable.
--
-- On 2026-08-05 league 1 managers reported their restricted free agency bids
-- "were reset". Answering that took reconstructing bid history from daily
-- pg_dump snapshots on the league host, because `restricted_free_agency_bids` is
-- mutated IN PLACE and keeps nothing: `PUT /teams/:id/tag/restricted-free-agency`
-- overwrites `bid_amount` and `userid` with no trace, the POST path silently
-- cancels a prior bid when a manager tags a different player, cancellation
-- stamps `cancelled`, and settlement stamps `processed` / `is_successful` /
-- `outcome`. Every one of those is a destructive write over the only copy of the
-- fact. The database could not answer "what was this manager's bid at time T,
-- and who changed it" at any point in six seasons, and the snapshots that made
-- the incident diagnosable at all existed by luck and gave 24-hour granularity.
--
-- ONE TABLE FOR BOTH BID KINDS, WIRED TO ONE OF THEM
--
-- `waivers` has the identical shape -- uid / userid / tid / lid / pid /
-- submitted / bid_amount / is_successful / processed / cancelled, the same
-- `bid` -> `bid_amount` rename, and the same in-place mutation -- so two bespoke
-- trails would be two of everything: two tables, two recorder helpers, two sets
-- of fixtures, and two half-remembered vocabularies that drift. `bid_type`
-- discriminates, and `libs-server/record-bid-change.mjs` already resolves it to
-- a table, so wiring waivers later is a call per write site and no new
-- mechanism.
--
-- Only the restricted free agency writers are wired in this change, and that is
-- deliberate rather than unfinished. Waivers has roughly twenty mutation sites
-- across five settlement scripts and two routers; sweeping them belongs in its
-- own change with its own tests, and a HALF-swept waiver trail would be worse
-- than none -- a reader could not tell "this bid was never changed" from "this
-- code path was never instrumented", which is exactly the ambiguity an audit
-- trail exists to remove. Nothing here needs revisiting when that sweep lands.
--
-- WHY POST-CHANGE STATE RATHER THAN A DIFF
--
-- Each row carries the complete state of the audited fields AFTER the change,
-- not the sparse set of fields that moved. That makes the question the incident
-- could not answer a single query -- the bid's row set ordered by changed_at,
-- limit 1 at or before T -- where a diff log would require replaying every row
-- from creation and would have no floor at all for a bid predating this table.
-- The old value is the previous row for the same bid (`lag()` over changed_at)
-- and is deliberately not stored a second time: two copies of one fact can
-- disagree, and the derived copy cannot.
--
-- `bid_user_id` and `changed_by_user_id` are not the same fact and both are
-- kept. The first is the bid row's own `userid`, which is whoever last WROTE the
-- row; the second is the actor of this particular change. They diverge on every
-- cancellation, because the cancel path does not touch `userid`.
--
-- Conditional releases (`restricted_free_agency_releases`) are in this trail
-- rather than in one of their own. They are part of the offer -- which players a
-- team commits to dropping changes what the bid means -- and the update path
-- rewrites them by delete-and-insert, so they are today the least recoverable
-- part of a bid. A release row has no meaning apart from its bid, so splitting
-- them would make reconstructing a single offer a join across two histories with
-- independent clocks. They are snapshotted as an ordered array on the bid's own
-- row. The column stays NULL for a waiver, which has no equivalent: absent and
-- empty are different statements about an offer.
--
-- NAMING
--
-- Full-word column names and `timestamptz` throughout, diverging from the
-- lid/tid/pid/epoch-bigint shorthand on the tables this one references. Those
-- are baselined conformance violations; reintroducing either on a new table
-- mints fresh ones and turns the CI ratchet red. `bid_id` references
-- `restricted_free_agency_bids.uid` or `waivers.uid` depending on `bid_type`,
-- which is why it carries no foreign key -- a polymorphic reference cannot have
-- one, and the alternative is two nullable columns that are each wrong half the
-- time.
--
-- The vocabularies for `bid_type`, `change_type` and `change_source` are closed
-- sets defined once in `libs-shared/constants/bid-changelog-constants.mjs`,
-- following the `restricted_free_agency_bids.outcome` precedent: codes in the
-- database, labels in the client, and no CHECK constraint, so adding a code is a
-- code change rather than a migration.

CREATE TABLE public.bid_changelog (
  change_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- which bid table `bid_id` points into
  bid_type character varying(32) NOT NULL,
  bid_id integer NOT NULL,

  -- denormalized from the bid so the trail survives the bid row being dropped,
  -- and so a league-scoped audit read needs no join
  league_id integer NOT NULL,
  team_id integer NOT NULL,
  player_id character varying(25),
  season_year smallint,

  change_type character varying(32) NOT NULL,
  change_source character varying(32) NOT NULL,
  changed_by_user_id integer,
  changed_at timestamp with time zone DEFAULT now() NOT NULL,

  -- complete post-change state of the audited fields
  bid_amount integer,
  bid_user_id integer,
  cancelled_at timestamp with time zone,
  processed_at timestamp with time zone,
  is_successful boolean,
  outcome character varying(32),
  outcome_detail text,
  conditional_release_player_ids character varying(25)[]
);

-- The state-at-time-T read: one bid's history in order.
CREATE INDEX idx_bid_changelog_bid_identity
  ON public.bid_changelog
  USING btree (bid_type, bid_id, changed_at);

-- The auction-level read: every team's bidding on one player in one season,
-- and (on the leading column alone) a league-scoped audit browse.
CREATE INDEX idx_bid_changelog_league_player_season
  ON public.bid_changelog
  USING btree (league_id, player_id, season_year, changed_at);

-- Matching what every other league table grants. The reader role is read-only by
-- construction, which is the right shape for an append-only audit trail: nothing
-- outside the API writers should ever touch it.
GRANT SELECT ON TABLE public.bid_changelog TO league_reader;
GRANT SELECT ON SEQUENCE public.bid_changelog_change_id_seq TO league_reader;

-- Seed a floor for every bid that already exists, so no live bid has an empty
-- history and every later row has something to be a change FROM.
--
-- These are `backfilled_snapshot`, not `created`: the state recorded is the
-- state NOW, and the instant is the apply, so calling them creations would
-- assert that a five-season-old settled bid was submitted today. `submitted` is
-- on the row and would give a truthful creation instant, but not a truthful
-- creation STATE -- the amount, the outcome and the cancellation on these rows
-- are the end of a history, not its beginning -- and a row that is right about
-- when and wrong about what is the worse of the two errors, because nothing
-- marks it as reconstructed.
--
-- `changed_by_user_id` is NULL throughout: the actor of the change that produced
-- this state is not recoverable. `bid_user_id` carries the row's `userid`, which
-- is a real fact (the last writer) and is not the same claim.
--
-- The companion file 2026-08-05-backfill-bid-changelog-from-snapshots.sql adds
-- the eight daily observations preceding this one; its header states what that
-- reconstruction can and cannot see.
INSERT INTO public.bid_changelog (
  bid_type,
  bid_id,
  league_id,
  team_id,
  player_id,
  season_year,
  change_type,
  change_source,
  changed_by_user_id,
  changed_at,
  bid_amount,
  bid_user_id,
  cancelled_at,
  processed_at,
  is_successful,
  outcome,
  outcome_detail,
  conditional_release_player_ids
)
SELECT
  'restricted_free_agency',
  bids.uid,
  bids.lid,
  bids.tid,
  bids.pid,
  bids.year,
  'backfilled_snapshot',
  'daily_snapshot_backfill',
  NULL,
  now(),
  bids.bid_amount,
  bids.userid,
  TO_TIMESTAMP(bids.cancelled),
  TO_TIMESTAMP(bids.processed),
  bids.is_successful,
  bids.outcome,
  bids.outcome_detail,
  COALESCE(
    (
      SELECT array_agg(releases.pid ORDER BY releases.pid)
      FROM public.restricted_free_agency_releases AS releases
      WHERE releases.restricted_free_agency_bid_id = bids.uid
    ),
    ARRAY[]::character varying(25)[]
  )
FROM public.restricted_free_agency_bids AS bids;

ANALYZE public.bid_changelog;
