-- STATUS: APPLIED 2026-08-02 against league_production
--
-- Give a restricted free agency auction its own row, and replace the free-text
-- outcome column with a closed-set code.
--
-- An auction is identified by (league, player, season), but no table has ever
-- represented it. Its group-level facts were written onto whichever bid belonged
-- to the nominating team: `restricted_free_agency_bids.announced` is populated on
-- exactly one bid per auction (2025 carries 131 bids and 20 announcements), so
-- every competing bid holds a null for a field that describes the PLAYER's
-- window rather than the bid. `process-restricted-free-agency-bids.mjs` read it
-- per bid, `Number(null)` coerced to 0, and a competing bid landed roughly
-- 41,000 windows in the past and came due the instant it was submitted --
-- league 1 processed its second 2026 nomination six hours early on 2026-08-02.
-- Resolving the announcement through the auction removes the null entirely.
--
-- The second change retires `reason`. That column carried whatever string was in
-- scope at settlement: two hardcoded sentences in the processing script plus
-- `error.message` from `process-restricted-free-agency-bid.mjs`. 262 of the 280
-- losing bids across 2021-2025 read `player no longer a restricted free agent`,
-- which is true of every ordinary loss and distinguishes none of them -- outbid,
-- matched by the original team, and lost-on-waiver-order are the three cases a
-- manager actually wants told apart. `outcome` holds a code from
-- `libs-shared/constants/restricted-free-agency-constants.mjs`; `outcome_detail`
-- carries an error message for the `processing_error` code alone and nothing
-- branches on it.
--
-- Column naming diverges from the `lid`/`pid`/`tid` shorthand used by the older
-- tables. Those are baselined conformance violations; reintroducing them on a
-- new table mints fresh ones and turns the CI ratchet red. Timestamps are
-- `timestamptz` for the same reason -- the bigint epochs beside them are
-- baselined, and a new time column following that convention is a new violation.
--
-- The backfill of `nomination_id` runs off (lid, pid, year) and covers cancelled
-- and still-live bids as well as settled ones, so every bid row keeps a path to
-- its auction. Per-bid `outcome` values are assigned by the companion file
-- 2026-08-02-backfill-restricted-free-agency-outcomes.sql.

CREATE TABLE public.restricted_free_agency_nominations (
  nomination_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  league_id integer NOT NULL,
  player_id character varying(25) NOT NULL,
  season_year smallint NOT NULL,
  original_team_id integer NOT NULL,
  nominated_at timestamp with time zone,
  announced_at timestamp with time zone,
  processed_at timestamp with time zone,
  winning_bid_id integer
);

CREATE UNIQUE INDEX idx_restricted_free_agency_nominations_identity
  ON public.restricted_free_agency_nominations
  USING btree (league_id, player_id, season_year);

CREATE INDEX idx_restricted_free_agency_nominations_league_season
  ON public.restricted_free_agency_nominations
  USING btree (league_id, season_year);

-- One nomination per (league, player, season). `player_tid` is NOT constant
-- within such a group: two of the 166 production auctions disagree, because the
-- player was traded before the auction ran and a bid placed against the previous
-- rights holder was later cancelled. In both cases the stale value appears only
-- on cancelled rows, so the live bids are the authority and the filtered
-- aggregate below takes them, falling back to the unfiltered value for a group
-- whose bids were all cancelled.
--
-- The window timestamps are populated on a single bid per group, which is the
-- defect this table exists to remove, so max() collapses them to the group. They
-- are deliberately not filtered on cancellation: the nominating team may cancel
-- its own bid, and the announcement still happened.
INSERT INTO public.restricted_free_agency_nominations (
  league_id,
  player_id,
  season_year,
  original_team_id,
  nominated_at,
  announced_at,
  processed_at,
  winning_bid_id
)
SELECT
  bids.lid,
  bids.pid,
  bids.year,
  COALESCE(
    MIN(bids.player_tid) FILTER (WHERE bids.cancelled IS NULL),
    MIN(bids.player_tid)
  ),
  TO_TIMESTAMP(MAX(bids.nominated)),
  TO_TIMESTAMP(MAX(bids.announced)),
  TO_TIMESTAMP(MAX(bids.processed)),
  MAX(bids.uid) FILTER (WHERE bids.succ IS TRUE)
FROM public.restricted_free_agency_bids AS bids
WHERE bids.pid IS NOT NULL
  AND bids.year IS NOT NULL
GROUP BY bids.lid, bids.pid, bids.year;

ALTER TABLE public.restricted_free_agency_bids
  ADD COLUMN nomination_id integer,
  ADD COLUMN outcome character varying(32),
  ADD COLUMN outcome_detail text;

UPDATE public.restricted_free_agency_bids AS bids
SET nomination_id = nominations.nomination_id
FROM public.restricted_free_agency_nominations AS nominations
WHERE nominations.league_id = bids.lid
  AND nominations.player_id = bids.pid
  AND nominations.season_year = bids.year;

CREATE INDEX idx_restricted_free_agency_bids_nomination_id
  ON public.restricted_free_agency_bids
  USING btree (nomination_id);

ANALYZE public.restricted_free_agency_nominations;
ANALYZE public.restricted_free_agency_bids;
