-- ROLLBACK for the nfl-plays-snaps conform migration
-- (inverse of db/adhoc/2026-07-24-conform-nfl-plays-snaps.sql).
--
-- Authored BEFORE the apply, deliberately, so the inverse is reviewed rather than written
-- under incident pressure. Mechanically generated by inverting the forward file's 63 column
-- renames and 10 index renames in reverse order, then reviewed.
--
-- SCOPE AND LIMITS -- read before running:
--
-- 1. This reverses the SCHEMA only. The lockstep code deploy must be reverted too
--    (git revert of the repoint commits + yarn deploy + yarn build && yarn deploy:dist),
--    or the running code will name columns that no longer exist. Revert code FIRST if the
--    API is already serving the new code, otherwise you trade one 42703 storm for another.
--
-- 2. The saved-view filter-param migration is reversed by the companion file
--    2026-07-24-rollback-saved-views-plays-filter-params.sql. That inverse is only
--    unambiguous while no NEW view has been saved under the new key names -- verified 0
--    rows contained the new keys before the apply. Once the deployed UI writes views with
--    offense_nfl_team/defense_nfl_team/possession_nfl_team, a blind inverse replace cannot
--    distinguish a migrated key from a natively-new one, and forward-fix becomes the only
--    sane path. In practice that means: rollback is clean up to the deploy, ambiguous after.
--
-- 3. Same lock discipline as the forward migration -- see the SET LOCAL below.
--
-- yarn db:exec db/adhoc/2026-07-24-rollback-nfl-plays-snaps.sql
-- yarn export:schema

BEGIN;

SET LOCAL lock_timeout = '3s';
SET LOCAL statement_timeout = '60s';

-- ---- indexes (inverse, reverse order) ----
ALTER INDEX public.nfl_plays_current_week_esbid_play_id RENAME TO "nfl_plays_current_week_esbid_playId";
ALTER INDEX public.nfl_plays_current_week_play_id RENAME TO "nfl_plays_current_week_playId";
ALTER INDEX public.idx_nfl_plays_season_year_esbid_play_id RENAME TO idx_nfl_plays_year_esbid_play_id;
ALTER INDEX public.idx_nfl_plays_season_year_esbid RENAME TO idx_nfl_plays_year_esbid;
ALTER INDEX public.idx_nfl_plays_season_type RENAME TO idx_nfl_plays_seas_type;
ALTER INDEX public.idx_nfl_plays_offense_nfl_team_week RENAME TO idx_nfl_plays_off_week;
ALTER INDEX public.idx_nfl_plays_offense_nfl_team RENAME TO idx_nfl_plays_off;
ALTER INDEX public.idx_nfl_plays_target_pid RENAME TO idx_nfl_plays_trg_pid;
ALTER INDEX public.idx_nfl_plays_passer_pid RENAME TO idx_nfl_plays_psr_pid;
ALTER INDEX public.idx_nfl_plays_ball_carrier_pid RENAME TO idx_nfl_plays_bc_pid;

-- ---- columns (inverse, reverse order) ----
ALTER TABLE public.nfl_play_stats_current_week RENAME COLUMN nfl_team_id TO teamid;
ALTER TABLE public.nfl_play_stats_current_week RENAME COLUMN smart_player_id TO gsispid;
ALTER TABLE public.nfl_play_stats_current_week RENAME COLUMN gsis_player_id TO "gsisId";
ALTER TABLE public.nfl_play_stats_current_week RENAME COLUMN stat_id TO "statId";
ALTER TABLE public.nfl_play_stats_current_week RENAME COLUMN player_name TO "playerName";
ALTER TABLE public.nfl_play_stats_current_week RENAME COLUMN nfl_team TO "clubCode";
ALTER TABLE public.nfl_play_stats_current_week RENAME COLUMN play_id TO "playId";
ALTER TABLE public.nfl_play_stats RENAME COLUMN nfl_team_id TO teamid;
ALTER TABLE public.nfl_play_stats RENAME COLUMN smart_player_id TO gsispid;
ALTER TABLE public.nfl_play_stats RENAME COLUMN gsis_player_id TO "gsisId";
ALTER TABLE public.nfl_play_stats RENAME COLUMN stat_id TO "statId";
ALTER TABLE public.nfl_play_stats RENAME COLUMN player_name TO "playerName";
ALTER TABLE public.nfl_play_stats RENAME COLUMN nfl_team TO "clubCode";
ALTER TABLE public.nfl_play_stats RENAME COLUMN play_id TO "playId";
ALTER TABLE public.nfl_snaps RENAME COLUMN season_year TO year;
ALTER TABLE public.nfl_snaps RENAME COLUMN play_id TO "playId";
ALTER TABLE public.nfl_plays_player RENAME COLUMN player_position TO "position";
ALTER TABLE public.nfl_plays_player RENAME COLUMN gsis_player_id TO gsis_id;
ALTER TABLE public.nfl_plays_player RENAME COLUMN season_year TO year;
ALTER TABLE public.nfl_plays_player RENAME COLUMN play_id TO "playId";
ALTER TABLE public.nfl_plays_rusher RENAME COLUMN gsis_player_id TO gsis_id;
ALTER TABLE public.nfl_plays_rusher RENAME COLUMN season_year TO year;
ALTER TABLE public.nfl_plays_rusher RENAME COLUMN play_id TO "playId";
ALTER TABLE public.nfl_plays_receiver RENAME COLUMN gsis_player_id TO gsis_id;
ALTER TABLE public.nfl_plays_receiver RENAME COLUMN season_year TO year;
ALTER TABLE public.nfl_plays_receiver RENAME COLUMN play_id TO "playId";
ALTER TABLE public.nfl_plays_passer RENAME COLUMN gsis_player_id TO gsis_id;
ALTER TABLE public.nfl_plays_passer RENAME COLUMN season_year TO year;
ALTER TABLE public.nfl_plays_passer RENAME COLUMN play_id TO "playId";
ALTER TABLE public.nfl_plays_current_week RENAME COLUMN fumbles_lost TO fuml;
ALTER TABLE public.nfl_plays_current_week RENAME COLUMN interceptor_pid TO intp_pid;
ALTER TABLE public.nfl_plays_current_week RENAME COLUMN target_pid TO trg_pid;
ALTER TABLE public.nfl_plays_current_week RENAME COLUMN passer_pid TO psr_pid;
ALTER TABLE public.nfl_plays_current_week RENAME COLUMN ball_carrier_pid TO bc_pid;
ALTER TABLE public.nfl_plays_current_week RENAME COLUMN possession_nfl_team_id TO pos_team_id;
ALTER TABLE public.nfl_plays_current_week RENAME COLUMN possession_nfl_team TO pos_team;
ALTER TABLE public.nfl_plays_current_week RENAME COLUMN defense_nfl_team TO def;
ALTER TABLE public.nfl_plays_current_week RENAME COLUMN offense_nfl_team TO off;
ALTER TABLE public.nfl_plays_current_week RENAME COLUMN play_time_of_day TO "timestamp";
ALTER TABLE public.nfl_plays_current_week RENAME COLUMN timeout_team TO to_team;
ALTER TABLE public.nfl_plays_current_week RENAME COLUMN timeouts TO "to";
ALTER TABLE public.nfl_plays_current_week RENAME COLUMN interceptions TO "int";
ALTER TABLE public.nfl_plays_current_week RENAME COLUMN play_description TO "desc";
ALTER TABLE public.nfl_plays_current_week RENAME COLUMN play_id TO "playId";
ALTER TABLE public.nfl_plays_current_week RENAME COLUMN season_type TO seas_type;
ALTER TABLE public.nfl_plays_current_week RENAME COLUMN season_year TO year;
ALTER TABLE public.nfl_plays RENAME COLUMN fumbles_lost TO fuml;
ALTER TABLE public.nfl_plays RENAME COLUMN interceptor_pid TO intp_pid;
ALTER TABLE public.nfl_plays RENAME COLUMN target_pid TO trg_pid;
ALTER TABLE public.nfl_plays RENAME COLUMN passer_pid TO psr_pid;
ALTER TABLE public.nfl_plays RENAME COLUMN ball_carrier_pid TO bc_pid;
ALTER TABLE public.nfl_plays RENAME COLUMN possession_nfl_team_id TO pos_team_id;
ALTER TABLE public.nfl_plays RENAME COLUMN possession_nfl_team TO pos_team;
ALTER TABLE public.nfl_plays RENAME COLUMN defense_nfl_team TO def;
ALTER TABLE public.nfl_plays RENAME COLUMN offense_nfl_team TO off;
ALTER TABLE public.nfl_plays RENAME COLUMN play_time_of_day TO "timestamp";
ALTER TABLE public.nfl_plays RENAME COLUMN timeout_team TO to_team;
ALTER TABLE public.nfl_plays RENAME COLUMN timeouts TO "to";
ALTER TABLE public.nfl_plays RENAME COLUMN interceptions TO "int";
ALTER TABLE public.nfl_plays RENAME COLUMN play_description TO "desc";
ALTER TABLE public.nfl_plays RENAME COLUMN play_id TO "playId";
ALTER TABLE public.nfl_plays RENAME COLUMN season_type TO seas_type;
ALTER TABLE public.nfl_plays RENAME COLUMN season_year TO year;

COMMIT;
