-- STATUS: APPLIED 2026-08-13 against league_production
--
-- A league-wide pause: while one is open, no transaction may be written and no
-- processor runs for that league, by any actor through any transport.
--
-- Each row is one pause INTERVAL, and the table is both the current state and
-- the ledger. A league is paused exactly when it has a row with `resumed_at IS
-- NULL`; there is no denormalized boolean to drift.
--
-- Interval rows rather than a stored accumulator on `seasons`: a "total paused
-- time" column is computed under whatever daily-window bounds were in force
-- when it was written, so changing `draft_hour_min`/`draft_hour_max` mid-season
-- would silently invalidate it. Intervals recompute against the current bounds
-- every time, and a second domain that later wants its own credit gets the
-- history for free instead of needing its own accumulator.
--
-- No `resumed_by_user_id`: nothing consumes it, and the narrower RFA pause
-- precedent (`seasons.restricted_free_agency_processing_paused_at`) records no
-- actor at all.

CREATE TABLE public.league_pauses (
    pause_id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    league_id         integer NOT NULL,
    paused_at         timestamp with time zone NOT NULL,
    resumed_at        timestamp with time zone,
    pause_reason      text NOT NULL,
    paused_by_user_id integer NOT NULL
);

-- At most one OPEN pause per league. This is the invariant the whole feature
-- rests on: `get_open_league_pause` returns a row or null, never a set, so a
-- double-pause cannot produce two intervals that both look current and get
-- double-credited to the draft clock.
CREATE UNIQUE INDEX league_pauses_one_open_per_league
    ON public.league_pauses (league_id) WHERE resumed_at IS NULL;

-- The draft credit and the pause history are both read per league, ordered by
-- when the pause began.
CREATE INDEX league_pauses_league_id_paused_at_idx
    ON public.league_pauses (league_id, paused_at);

GRANT SELECT ON TABLE public.league_pauses TO league_reader;
