-- STATUS: APPLIED 2026-09-02 against league_production
--
-- Attribute the 3,248 CAESARS GAME_TEAM_TOTAL selections whose team was never
-- recorded, by deriving it from the team prefix on the market name.
--
-- THE DEFECT, which is live in production today. Caesars publishes a team total
-- as one market per team in the same game, from one template, and the
-- selections are a bare over/under:
--
--   Miami Dolphins at New York Jets - MIA Total Points  over 20.5 / under 20.5
--   Miami Dolphins at New York Jets - NYJ Total Points  over 19.5 / under 19.5
--
-- The only thing that says whose line it is, is the team prefix on the market
-- name. With selection_pid null the two markets are one key for anything
-- joining on (esbid, market_type, selection_name) -- which the data-view
-- betting columns and the historical hit-rate calculation both do. Two
-- different lines land in one cell and the observed_at dedup in
-- libs-server/market-row-dedup.mjs picks arbitrarily. Measured before this
-- file: 1,620 such groups, 1,544 of them holding conflicting metric lines.
--
-- Settlement never catches it, because GAME_TEAM_TOTAL resolves to UNSUPPORTED
-- in libs-server/prop-market-settlement/market-type-mappings.mjs. The failure
-- surfaces as a plausible wrong number rather than an error, which is why it
-- sat unnoticed since 2023-11-09.
--
-- THE FORWARD HALF SHIPS WITH THIS. private/scripts/import-caesars-odds-v4.mjs
-- now derives selection_pid from the market-name team prefix for every
-- TEAM-grain market type, so a market Caesars publishes again arrives
-- attributed and this repair does not decay. Exercised on a real payload rather
-- than read: a --dry run on base-storage over the 2026 week-1 events populated
-- 128 of 128 team-grain selections against 24 of 128 on the same payload with
-- the branch disabled.
--
-- WHY THE TEAM MAP IS MATERIALIZED HERE rather than parsed in SQL. The mapping
-- from a Caesars team token to the canonical abbreviation is fixTeam's, and
-- reproducing it in SQL would be a second implementation that can drift. The 64
-- pairs below were GENERATED by calling libs-shared/fix-team.mjs on each of the
-- 64 distinct team tokens actually stored, never hand-typed. Three of them are
-- not the canonical form -- WSC for Washington, LVR for Las Vegas, NOR for New
-- Orleans -- and WSC is an alias fixTeam gained in the same change as this file.
--
-- Caesars writes the token in two forms across eras: the 2-3 letter
-- abbreviation on the 2023-2025 'Total Home Points' and 'Total Away Points'
-- templates, and the full team name on 'Team Total Points', which is the live
-- one. Both forms are in the map.
--
-- AFC AND NFC ARE DELIBERATELY LEFT UNATTRIBUTED. Eight Pro Bowl markets, one
-- selection each. fixTeam resolves both tokens, but neither is an NFL team and
-- neither is a valid pid, and all four markets carry a null esbid, so they are
-- invisible to every consumer already. Attributing them would invent a pid that
-- joins to nothing.
--
-- WHAT THIS FILE DOES NOT CLAIM TO FIX. Sixteen selection rows still share a
-- key after the repair, and they are a different defect: Caesars listed two
-- rescheduled games -- esbid 2025010511 and 2025011300 -- under two separate
-- event ids each, so the same team has two markets in one game. The observed_at
-- dedup resolves those correctly by taking the later listing. The
-- post-condition asserts the residual is exactly those, rather than asserting a
-- zero this file cannot honestly reach.
--
-- THIS WRITE IS NOT DURABLE AGAINST A RE-OBSERVATION on its own.
-- insert-prop-markets.mjs upserts prop_market_selections_index with a bare
-- .merge(), so an incoming import overwrites selection_pid unconditionally. It
-- is durable for the right reason instead: the importer now derives the same
-- value. The two extinct templates are a belt as well, last observed 2025-10-06.

CREATE TEMP TABLE caesars_team_total_baseline ON COMMIT DROP AS
SELECT
  count(*) FILTER (WHERE i.source_id = 'CAESARS' AND i.market_type = 'GAME_TEAM_TOTAL')
    AS caesars_team_total_selections,
  count(*) FILTER (WHERE i.source_id = 'CAESARS' AND i.market_type = 'GAME_TEAM_TOTAL'
                     AND s.selection_pid IS NULL) AS null_pid,
  count(*) FILTER (WHERE s.selection_pid IS NULL) AS null_pid_all_sources,
  (SELECT count(*) FILTER (WHERE is_market_settled) FROM public.prop_markets_index)
    AS settled_markets
FROM public.prop_market_selections_index AS s
JOIN public.prop_markets_index AS i
  ON i.source_id = s.source_id
 AND i.source_market_id = s.source_market_id
 AND i.time_type = s.time_type;

-- The team a market belongs to, derived once and reused by the update and by
-- every post-condition, so a post-condition cannot pass against a different
-- derivation than the one that wrote.
CREATE TEMP TABLE caesars_team_total_attribution ON COMMIT DROP AS
WITH caesars_team_token (team_token, nfl_team) AS (
  VALUES
    ('ARI', 'ARI'),
    ('Arizona Cardinals', 'ARI'),
    ('ATL', 'ATL'),
    ('Atlanta Falcons', 'ATL'),
    ('BAL', 'BAL'),
    ('Baltimore Ravens', 'BAL'),
    ('BUF', 'BUF'),
    ('Buffalo Bills', 'BUF'),
    ('CAR', 'CAR'),
    ('Carolina Panthers', 'CAR'),
    ('CHI', 'CHI'),
    ('Chicago Bears', 'CHI'),
    ('CIN', 'CIN'),
    ('Cincinnati Bengals', 'CIN'),
    ('CLE', 'CLE'),
    ('Cleveland Browns', 'CLE'),
    ('DAL', 'DAL'),
    ('Dallas Cowboys', 'DAL'),
    ('DEN', 'DEN'),
    ('Denver Broncos', 'DEN'),
    ('DET', 'DET'),
    ('Detroit Lions', 'DET'),
    ('GB', 'GB'),
    ('Green Bay Packers', 'GB'),
    ('HOU', 'HOU'),
    ('Houston Texans', 'HOU'),
    ('IND', 'IND'),
    ('Indianapolis Colts', 'IND'),
    ('Jacksonville Jaguars', 'JAX'),
    ('JAX', 'JAX'),
    ('Kansas City Chiefs', 'KC'),
    ('KC', 'KC'),
    ('LA', 'LA'),
    ('LAC', 'LAC'),
    ('Las Vegas Raiders', 'LV'),
    ('Los Angeles Chargers', 'LAC'),
    ('Los Angeles Rams', 'LA'),
    ('LVR', 'LV'),
    ('MIA', 'MIA'),
    ('Miami Dolphins', 'MIA'),
    ('MIN', 'MIN'),
    ('Minnesota Vikings', 'MIN'),
    ('NE', 'NE'),
    ('New England Patriots', 'NE'),
    ('New Orleans Saints', 'NO'),
    ('New York Giants', 'NYG'),
    ('New York Jets', 'NYJ'),
    ('NOR', 'NO'),
    ('NYG', 'NYG'),
    ('NYJ', 'NYJ'),
    ('PHI', 'PHI'),
    ('Philadelphia Eagles', 'PHI'),
    ('PIT', 'PIT'),
    ('Pittsburgh Steelers', 'PIT'),
    ('San Francisco 49ers', 'SF'),
    ('SEA', 'SEA'),
    ('Seattle Seahawks', 'SEA'),
    ('SF', 'SF'),
    ('Tampa Bay Buccaneers', 'TB'),
    ('TB', 'TB'),
    ('TEN', 'TEN'),
    ('Tennessee Titans', 'TEN'),
    ('Washington Commanders', 'WAS'),
    ('WSC', 'WAS')
), template_suffix (template, name_suffix) AS (
  VALUES
    ('Total Away Points', 'Total Points'),
    ('Total Home Points', 'Total Points'),
    ('Team Total Points', 'Total Points')
), market_name AS (
  SELECT
    i.source_id,
    i.source_market_id,
    i.time_type,
    i.esbid,
    i.source_event_id,
    split_part(i.source_market_name, ' — ', 2) AS template,
    -- The stored name is `${event.name} - ${market.name} — ${template} — ${category}`,
    -- so the market name is what follows the LAST ' - ' in the first segment.
    reverse(split_part(reverse(split_part(i.source_market_name, ' — ', 1)), ' - ', 1))
      AS market_name
  FROM public.prop_markets_index AS i
  WHERE i.source_id = 'CAESARS'
    AND i.market_type = 'GAME_TEAM_TOTAL'
)
SELECT
  m.source_id,
  m.source_market_id,
  m.time_type,
  m.esbid,
  m.source_event_id,
  k.nfl_team
FROM market_name AS m
JOIN template_suffix AS t USING (template)
LEFT JOIN caesars_team_token AS k
  ON k.team_token = left(m.market_name, length(m.market_name) - length(t.name_suffix) - 1);

-- Pre-conditions.
DO $$
DECLARE
  baseline record;
  index_rows integer;
  unresolved integer;
  team_not_in_game integer;
  existing_pid_disagrees integer;
  colliding_groups integer;
BEGIN
  SELECT * INTO baseline FROM caesars_team_total_baseline;

  IF baseline.caesars_team_total_selections <> 3264 THEN
    RAISE EXCEPTION
      'expected 3264 CAESARS GAME_TEAM_TOTAL selections, found %; the population moved and the counts in this file are about a different one, rolling back',
      baseline.caesars_team_total_selections;
  END IF;

  SELECT count(*) INTO index_rows FROM caesars_team_total_attribution;
  IF index_rows <> 1716 THEN
    RAISE EXCEPTION
      'expected 1716 CAESARS GAME_TEAM_TOTAL index rows, found %; rolling back', index_rows;
  END IF;

  -- Exactly the eight Pro Bowl markets -- two templates, two tokens, two
  -- time_types -- whose token is AFC or NFC and which are deliberately absent
  -- from the map above. They carry one selection each.
  SELECT count(*) INTO unresolved
    FROM caesars_team_total_attribution WHERE nfl_team IS NULL;
  IF unresolved <> 8 THEN
    RAISE EXCEPTION
      'expected exactly 8 index rows with no resolvable team (the Pro Bowl AFC/NFC markets), found %; a market name shape has drifted and the derivation below would be attributing on a guess, rolling back',
      unresolved;
  END IF;

  -- THE CHECK THAT MAKES THE DERIVATION HONEST rather than a parse that cannot
  -- report failure. Every team read off a market name must be one of the two
  -- teams the game actually holds. Validated to go red: repointing one token at
  -- another team raises this from 0 to 342.
  SELECT count(*) INTO team_not_in_game
    FROM caesars_team_total_attribution AS a
    JOIN public.nfl_games AS g ON g.esbid = a.esbid
   WHERE a.nfl_team IS NOT NULL
     AND a.nfl_team NOT IN (g.home_nfl_team, g.away_nfl_team);
  IF team_not_in_game <> 0 THEN
    RAISE EXCEPTION
      '% markets resolved to a team the game does not hold; rolling back', team_not_in_game;
  END IF;

  -- Eight selections on one 2026 preseason game already carry a pid, written by
  -- the importer's player lookup resolving the full team name to a DST pid.
  -- That path covers 24 of 128 team-grain selections on a live payload, so it
  -- is not the fix -- but where it did fire it is an INDEPENDENT derivation of
  -- the same answer, and it must agree.
  SELECT count(*) INTO existing_pid_disagrees
    FROM caesars_team_total_attribution AS a
    JOIN public.prop_market_selections_index AS s
      ON s.source_id = a.source_id
     AND s.source_market_id = a.source_market_id
     AND s.time_type = a.time_type
   WHERE s.selection_pid IS NOT NULL
     AND a.nfl_team IS NOT NULL
     AND s.selection_pid <> a.nfl_team;
  IF existing_pid_disagrees <> 0 THEN
    RAISE EXCEPTION
      '% already-attributed selections disagree with the derived team; rolling back',
      existing_pid_disagrees;
  END IF;

  -- The defect, measured rather than asserted from the plan. This is the number
  -- the post-condition has to move.
  SELECT count(*) INTO colliding_groups FROM (
    SELECT 1
      FROM caesars_team_total_attribution AS a
      JOIN public.prop_market_selections_index AS s
        ON s.source_id = a.source_id
       AND s.source_market_id = a.source_market_id
       AND s.time_type = a.time_type
     WHERE a.esbid IS NOT NULL
     GROUP BY a.esbid, a.time_type, s.selection_name
    HAVING count(*) > 1
  ) AS g;
  IF colliding_groups <> 1620 THEN
    RAISE EXCEPTION
      'expected 1620 colliding (esbid, time_type, selection_name) groups before the repair, found %; rolling back',
      colliding_groups;
  END IF;

  RAISE NOTICE 'baseline: % selections, % with a null pid, % colliding groups',
    baseline.caesars_team_total_selections, baseline.null_pid, colliding_groups;
END $$;

DO $$
DECLARE
  updated integer;
BEGIN
  UPDATE public.prop_market_selections_index AS s
     SET selection_pid = a.nfl_team
    FROM caesars_team_total_attribution AS a
   WHERE s.source_id = a.source_id
     AND s.source_market_id = a.source_market_id
     AND s.time_type = a.time_type
     AND s.selection_pid IS NULL
     AND a.nfl_team IS NOT NULL;

  GET DIAGNOSTICS updated = ROW_COUNT;

  -- Exactly, not at least.
  IF updated <> 3248 THEN
    RAISE EXCEPTION
      'expected to attribute exactly 3248 selections, attributed %; rolling back', updated;
  END IF;

  RAISE NOTICE 'attributed % CAESARS GAME_TEAM_TOTAL selections', updated;
END $$;

-- Post-conditions, inside the same transaction.
DO $$
DECLARE
  baseline record;
  still_null integer;
  wrong_team integer;
  colliding_groups integer;
  residual_on_duplicate_events integer;
  null_pid_all_sources integer;
  settled_markets integer;
BEGIN
  SELECT * INTO baseline FROM caesars_team_total_baseline;

  -- Only the eight Pro Bowl selections may remain unattributed.
  SELECT count(*) INTO still_null
    FROM caesars_team_total_attribution AS a
    JOIN public.prop_market_selections_index AS s
      ON s.source_id = a.source_id
     AND s.source_market_id = a.source_market_id
     AND s.time_type = a.time_type
   WHERE s.selection_pid IS NULL;
  IF still_null <> 8 THEN
    RAISE EXCEPTION
      'expected exactly 8 selections left unattributed (the Pro Bowl AFC/NFC markets), found %; rolling back',
      still_null;
  END IF;

  SELECT count(*) INTO wrong_team
    FROM caesars_team_total_attribution AS a
    JOIN public.prop_market_selections_index AS s
      ON s.source_id = a.source_id
     AND s.source_market_id = a.source_market_id
     AND s.time_type = a.time_type
    JOIN public.nfl_games AS g ON g.esbid = a.esbid
   WHERE s.selection_pid IS NOT NULL
     AND s.selection_pid NOT IN (g.home_nfl_team, g.away_nfl_team);
  IF wrong_team <> 0 THEN
    RAISE EXCEPTION
      '% attributed selections name a team their game does not hold; rolling back', wrong_team;
  END IF;

  -- The collapse is gone: keying on selection_pid as well takes 1,620 groups
  -- to 16.
  SELECT count(*) INTO colliding_groups FROM (
    SELECT 1
      FROM caesars_team_total_attribution AS a
      JOIN public.prop_market_selections_index AS s
        ON s.source_id = a.source_id
       AND s.source_market_id = a.source_market_id
       AND s.time_type = a.time_type
     WHERE a.esbid IS NOT NULL
     GROUP BY a.esbid, a.time_type, s.selection_pid, s.selection_name
    HAVING count(*) > 1
  ) AS g;
  IF colliding_groups <> 16 THEN
    RAISE EXCEPTION
      'expected 16 residual colliding groups, found %; rolling back', colliding_groups;
  END IF;

  -- And the 16 are the OTHER defect, not this one: every remaining group sits
  -- on an esbid Caesars listed under more than one event id. Asserting the
  -- residual's cause, not just its size.
  SELECT count(*) INTO residual_on_duplicate_events FROM (
    SELECT a.esbid
      FROM caesars_team_total_attribution AS a
      JOIN public.prop_market_selections_index AS s
        ON s.source_id = a.source_id
       AND s.source_market_id = a.source_market_id
       AND s.time_type = a.time_type
     WHERE a.esbid IS NOT NULL
     GROUP BY a.esbid, a.time_type, s.selection_pid, s.selection_name
    HAVING count(*) > 1
       AND count(DISTINCT a.source_event_id) < 2
  ) AS g;
  IF residual_on_duplicate_events <> 0 THEN
    RAISE EXCEPTION
      '% residual colliding groups are NOT explained by a duplicate Caesars event listing; rolling back',
      residual_on_duplicate_events;
  END IF;

  -- No other source moved. Compared against the baseline rather than a literal,
  -- because a concurrent importer legitimately moves that number.
  SELECT count(*) FILTER (WHERE s.selection_pid IS NULL)
    INTO null_pid_all_sources
    FROM public.prop_market_selections_index AS s
    JOIN public.prop_markets_index AS i
      ON i.source_id = s.source_id
     AND i.source_market_id = s.source_market_id
     AND i.time_type = s.time_type;
  IF baseline.null_pid_all_sources - null_pid_all_sources <> 3248 THEN
    RAISE EXCEPTION
      'the all-source null-pid count fell by % rather than 3248, so this file touched rows outside its scope; rolling back',
      baseline.null_pid_all_sources - null_pid_all_sources;
  END IF;

  -- Attribution makes a market readable, not graded. GAME_TEAM_TOTAL resolves
  -- to UNSUPPORTED, and nothing here settles anything.
  SELECT count(*) FILTER (WHERE is_market_settled) INTO settled_markets
    FROM public.prop_markets_index;
  IF settled_markets <> baseline.settled_markets THEN
    RAISE EXCEPTION
      'the settled-market count moved (% vs %); rolling back',
      settled_markets, baseline.settled_markets;
  END IF;

  RAISE NOTICE 'CAESARS GAME_TEAM_TOTAL: % unattributed left, % residual colliding groups',
    still_null, colliding_groups;
END $$;
