-- STATUS: APPLIED 2026-09-02 against league_production
--
-- Set market_type on 13,602 CAESARS rows in prop_markets_index across 13
-- templates: the kicking family and the period-scoped game lines. The mapper
-- learned these templates in league 9eeaf575a and 5e4887c1e; this file applies
-- the same mapping to names already stored.
--
-- This is the historical half of increment two of
-- user:task/league/close-caesars-market-type-coverage.md. The forward half is
-- the mapper change itself, which types these templates at write time from the
-- next importer run onward.
--
-- WHY THE MAPPING IS MATERIALIZED HERE rather than replayed by a script calling
-- get_market_type. Same reasoning as
-- db/adhoc/2026-09-01-type-caesars-markets-the-deployed-mapper-already-knows.sql:
-- it decouples the apply from getting a checkout updated, and it makes the file
-- state which template became which type, which a script deleted after its run
-- does not. The 13 pairs were GENERATED by calling the new get_market_type on
-- every distinct stored Caesars template and DIFFING against the mapper as it
-- stood before increment two, so the list is exactly what changed. The
-- generator raised on any template whose type CHANGED rather than appeared;
-- none did, so this file cannot be silently re-typing a row that already had an
-- answer.
--
-- THE TEMPLATE MUST BE WRAPPED IN PIPES BEFORE THE MAPPER SEES IT. The importer
-- stores templateName.replaceAll('|',''), so the stored segment has the pipes
-- STRIPPED while the table keys carry them. Passing the stored segment verbatim
-- matches nothing. That trap is why the pairs above were derived by calling the
-- mapper with the wrap applied, and why this file joins on the bare stored form
-- rather than trying to reproduce the mapper in SQL.
--
-- THREE TEMPLATES THE MAPPER NOW KNOWS HAVE NO ROWS HERE, deliberately.
-- '2nd Half Money Line', '2nd Half Spread' and '2nd Half Total Points' are the
-- names the live v4 feed uses today; the stored history carries the older
-- '(Inc. OT)' forms, which are in the list below. The mapper keys both forms to
-- one constant, so this file backfills the history and the importer types the
-- feed.
--
-- THE SECOND, THIRD AND FOURTH QUARTER LINES ARE DELIBERATELY NOT HERE. Caesars
-- publishes them and they are the obvious symmetric completion of the first
-- quarter lines that are here, but they hold four stored rows each and nothing
-- has been written since 2025-02-07. They stay untyped, and that is a decision
-- rather than an oversight.
--
-- LIVE MARKETS FALL OUT BY CONSTRUCTION. The table is exact-match, so a
-- template carrying a trailing ' Live' matches no key. None of the 13 pairs
-- below ends in ' Live', and the post-condition asserts that no live-suffixed
-- template acquired a type.
--
-- THIS WRITE IS NOT DURABLE AGAINST A RE-OBSERVATION on its own. market_type is
-- in MARKET_INDEX_MERGE_COLUMNS in libs-server/insert-prop-markets.mjs and
-- build_market_index_merge maps it to excluded.market_type, so an incoming
-- import value wins unconditionally on conflict. Unlike the 2026-09-01 file,
-- which relied on the population being historical, this one is durable for the
-- right reason: the mapper now types these templates, so a re-observation
-- writes the same value rather than reverting it. The historical population is
-- a belt as well -- these rows were last observed 2026-01-11 and 2025-02-09,
-- and the importer only fetches current-week events.
--
-- WHAT THIS MAKES VISIBLE, AND WHAT IT DOES NOT. market_type is what the
-- data-view betting columns and historical hit-rate calculation key on, and a
-- null type is excluded by both. None of the eight new period constants and
-- none of the kicking constants except GAME_ALT_FIELD_GOALS_MADE is settleable
-- -- they resolve to UNSUPPORTED -- so this changes what is READABLE without
-- changing what is GRADED. The settled-market count must not move, and the
-- post-condition asserts it.
--
-- The Caesars null_type count falls from 128,954 to 115,352. No other source is
-- touched, asserted by comparing the other-source count before and after within
-- this transaction rather than against a literal, because a concurrent importer
-- legitimately moves that number and a literal would read as this file's fault.

CREATE TEMP TABLE caesars_backfill_baseline ON COMMIT DROP AS
SELECT
  count(*) FILTER (WHERE source_id = 'CAESARS' AND market_type IS NULL)
    AS caesars_null_type,
  count(*) FILTER (WHERE source_id <> 'CAESARS' AND market_type IS NULL)
    AS other_sources_null_type,
  count(*) FILTER (WHERE is_market_settled) AS settled_markets
FROM public.prop_markets_index;

DO $$
DECLARE
  baseline record;
BEGIN
  SELECT * INTO baseline FROM caesars_backfill_baseline;

  IF baseline.caesars_null_type <> 128954 THEN
    RAISE EXCEPTION
      'expected 128954 untyped CAESARS rows, found %; the population moved and the counts in this file are about a different one, rolling back',
      baseline.caesars_null_type;
  END IF;
END $$;

DO $$
DECLARE
  updated integer;
BEGIN
  WITH template_market_type (template, market_type) AS (
    VALUES
      ('Player Total Kicking Points', 'GAME_KICKING_POINTS'),
      ('Player Total Made Field Goals', 'GAME_FIELD_GOALS_MADE'),
      ('Player Total Made Extra Points', 'GAME_EXTRA_POINTS_MADE'),
      ('Alt Kicking Points', 'GAME_ALT_KICKING_POINTS'),
      ('Alt Made Field Goals', 'GAME_ALT_FIELD_GOALS_MADE'),
      ('Alt Made Extra Points', 'GAME_ALT_EXTRA_POINTS_MADE'),
      ('1st Half Money Line', 'GAME_FIRST_HALF_MONEYLINE'),
      ('1st Half Total Points', 'GAME_FIRST_HALF_TOTAL'),
      ('2nd Half Spread (Inc. OT)', 'GAME_SECOND_HALF_SPREAD'),
      ('2nd Half Total Points (Inc. OT)', 'GAME_SECOND_HALF_TOTAL'),
      ('1st Quarter Money Line', 'GAME_FIRST_QUARTER_MONEYLINE'),
      ('1st Quarter Spread', 'GAME_FIRST_QUARTER_SPREAD'),
      ('1st Quarter Total Points', 'GAME_FIRST_QUARTER_TOTAL')
  )
  UPDATE public.prop_markets_index AS i
     SET market_type = t.market_type
    FROM template_market_type AS t
   WHERE i.source_id = 'CAESARS'
     AND i.market_type IS NULL
     AND split_part(i.source_market_name, ' — ', 2) = t.template;

  GET DIAGNOSTICS updated = ROW_COUNT;

  -- Exactly, not at least. A larger number means the template census moved
  -- under this file and the per-family counts recorded on the task are about a
  -- different population.
  IF updated <> 13602 THEN
    RAISE EXCEPTION
      'expected to type exactly 13602 rows, typed %; rolling back', updated;
  END IF;

  RAISE NOTICE 'typed % CAESARS rows across 13 templates', updated;
END $$;

-- Post-conditions, inside the same transaction.
DO $$
DECLARE
  baseline record;
  caesars_null_type integer;
  other_sources_null_type integer;
  settled_markets integer;
  live_typed integer;
BEGIN
  SELECT * INTO baseline FROM caesars_backfill_baseline;

  SELECT count(*) FILTER (WHERE source_id = 'CAESARS' AND market_type IS NULL),
         count(*) FILTER (WHERE source_id <> 'CAESARS' AND market_type IS NULL),
         count(*) FILTER (WHERE is_market_settled)
    INTO caesars_null_type, other_sources_null_type, settled_markets
    FROM public.prop_markets_index;

  IF caesars_null_type <> 115352 THEN
    RAISE EXCEPTION
      'expected 115352 untyped CAESARS rows after typing, found %; rolling back',
      caesars_null_type;
  END IF;

  -- A per-source check, not just a Caesars one: a total that fell while another
  -- source rose would read as success on a single number.
  IF other_sources_null_type <> baseline.other_sources_null_type THEN
    RAISE EXCEPTION
      'another source''s untyped count moved (% vs %); rolling back',
      other_sources_null_type, baseline.other_sources_null_type;
  END IF;

  -- Typing makes a market readable, not graded. Every constant this file
  -- writes except GAME_ALT_FIELD_GOALS_MADE resolves to UNSUPPORTED in
  -- libs-server/prop-market-settlement/market-type-mappings.mjs, and nothing
  -- here settles anything, so the settled count must not move at all.
  IF settled_markets <> baseline.settled_markets THEN
    RAISE EXCEPTION
      'the settled-market count moved (% vs %); rolling back',
      settled_markets, baseline.settled_markets;
  END IF;

  -- Nothing carrying a trailing ' Live' may have acquired a type here. The
  -- exact-match table guarantees it; this asserts it rather than trusting it,
  -- because a live row winning the observed_at dedup is how a mid-game price
  -- displaces a pregame one in a data-view cell.
  SELECT count(*)
    INTO live_typed
    FROM public.prop_markets_index
   WHERE source_id = 'CAESARS'
     AND market_type IS NOT NULL
     AND split_part(source_market_name, ' — ', 2) LIKE '% Live';

  IF live_typed <> 0 THEN
    RAISE EXCEPTION
      '% live-suffixed templates carry a market_type; rolling back', live_typed;
  END IF;

  RAISE NOTICE 'CAESARS untyped now %, settled markets %, live-suffixed typed rows %',
    caesars_null_type, settled_markets, live_typed;
END $$;
