-- nfl_coaches own-id migration -- Phase 1 (additive only).
--
-- Task: user:task/league/migrate-nfl-coaches-to-own-id.md
--
-- This migration is FULLY ADDITIVE. It introduces coach_id (deterministic
-- own-id LNAM-FNAM-YYYY-MM-DD) alongside the existing pfr_coach_id PK, and
-- populates the bridge's new *_coach_id columns alongside the existing
-- *_pfr_id columns. The PK swap and old-column drop happen in the Phase 2
-- adhoc (2026-05-31-nfl-coaches-own-id-pk-swap.sql).
--
-- Pre-rewrite importer continues writing to *_pfr_id only during the
-- inter-phase window; Phase 2's first step re-runs the join-populate to
-- repair any drift before old columns are dropped.
--
-- =========================================================================
-- ROLLBACK SKETCH (Phase 1; clean while no production code reads new cols)
-- =========================================================================
--   BEGIN;
--   ALTER TABLE nfl_game_coaches
--     DROP COLUMN IF EXISTS head_coach_id,
--     DROP COLUMN IF EXISTS off_play_caller_id,
--     DROP COLUMN IF EXISTS def_play_caller_id;
--   DELETE FROM nfl_coaches WHERE pfr_coach_id IS NULL;  -- 7 seed rows
--   ALTER TABLE nfl_coaches
--     DROP CONSTRAINT IF EXISTS nfl_coaches_coach_id_unique,
--     DROP CONSTRAINT IF EXISTS nfl_coaches_coach_id_format,
--     DROP CONSTRAINT IF EXISTS nfl_coaches_pfr_coach_id_unique,
--     ALTER COLUMN pfr_coach_id SET NOT NULL,
--     ADD PRIMARY KEY (pfr_coach_id),
--     DROP COLUMN IF EXISTS coach_id,
--     DROP COLUMN IF EXISTS dob;
--   COMMIT;
-- =========================================================================

BEGIN;

-- 1. Additive columns on nfl_coaches (idempotent).
ALTER TABLE nfl_coaches
  ADD COLUMN IF NOT EXISTS coach_id varchar(32),
  ADD COLUMN IF NOT EXISTS dob date;

-- 2. PFR fixture: temp table loaded from static-data/pfr-coaches.json (472 rows).
--    The VALUES block below is generated by:
--      node scripts/build-nfl-coaches-additive-fixture-values.mjs
--    after the Phase 0 scrape completes. The generator computes coach_id
--    via the SAME derive_coach_id helper the importer uses, so SQL and JS
--    cannot drift. Do not hand-edit.
--
--    Null-DOB disposition (2026-05-31 scrape; 6 PFR pages without DOB).
--    Rule (task plan body): bridge-referenced OR present in samhoppen
--    yearly_coaching_history.csv -> keep with sentinel; unreferenced AND
--    absent from YCH -> drop. Bridge = nfl_game_coaches.{head_coach_pfr_id,
--    off_play_caller_pfr_id, def_play_caller_pfr_id}.
--      DoylDe0 Declan Doyle  - not-bridge, YCH=2  -> KEEP sentinel
--      KubiKl1 Klay Kubiak   - not-bridge, YCH=2  -> KEEP sentinel
--      LaFlMi0 Mike LaFleur  - BRIDGE,    YCH=12 -> KEEP sentinel
--      PiolSc0 Scott Pioli   - not-bridge, YCH=0  -> DROP
--      SmitGi0 Giff Smith    - BRIDGE,    YCH=16 -> KEEP sentinel
--      UdinGr0 Grant Udinski - not-bridge, YCH=1  -> KEEP sentinel
--    Sentinel storage convention (matches Rothstein interim seed below):
--    dob column = '1900-01-01' (PostgreSQL date type rejects 0000-00-00);
--    coach_id text carries the literal '0000-00-00' marker. No collisions
--    among the 5 sentinel (LNAM, FNAM) tuples or against real-DOB rows.
--    Fixture row count: 472 scraped - 1 dropped = 471.
CREATE TEMP TABLE pfr_coach_fixture (
  pfr_coach_id varchar(16) PRIMARY KEY,
  full_name varchar(80) NOT NULL,
  dob date,
  coach_id varchar(32) NOT NULL,
  first_season_pfr smallint
) ON COMMIT DROP;

-- BEGIN GENERATED FIXTURE VALUES (regenerate after static-data/pfr-coaches.json)
INSERT INTO pfr_coach_fixture (pfr_coach_id, full_name, dob, coach_id, first_season_pfr) VALUES
  ('AbraDa0', 'Danny Abramowicz', '1945-07-13'::date, 'ABRA-DANN-1945-07-13', 1992),
  ('AdamKl0', 'Klayton Adams', '1983-02-13'::date, 'ADAM-KLAY-1983-02-13', 2005),
  ('AdolDa0', 'Dave Adolph', '1937-06-06'::date, 'ADOL-DAVE-1937-06-06', 1963),
  ('AlleDe0', 'Dennis Allen', '1972-09-22'::date, 'ALLE-DENN-1972-09-22', 1996),
  ('AnarLo0', 'Lou Anarumo', '1966-08-18'::date, 'ANAR-LOU-1966-08-18', 1989),
  ('AndeKe0', 'Ken Anderson', '1949-02-15'::date, 'ANDE-KEN-1949-02-15', 1993),
  ('AnslDe0', 'Derrick Ansley', '1981-12-11'::date, 'ANSL-DERR-1981-12-11', 2005),
  ('AriaBr0', 'Bruce Arians', '1952-10-03'::date, 'ARIA-BRUC-1952-10-03', 1975),
  ('AtkiDa0', 'Dave Atkins', '1949-05-18'::date, 'ATKI-DAVE-1949-05-18', 1979),
  ('AustTe0', 'Teryl Austin', '1965-03-03'::date, 'AUST-TERY-1965-03-03', 1991),
  ('BabiBo0', 'Bob Babich', '1961-02-20'::date, 'BABI-BOB-1961-02-20', 1984),
  ('BabiBo1', 'Bobby Babich', '1983-07-30'::date, 'BABI-BOBB-1983-07-30', 2006),
  ('BankMa0', 'Mark Banker', '1956-01-15'::date, 'BANK-MARK-1956-01-15', 1979),
  ('BarrJo0', 'Joe Barry', '1970-07-05'::date, 'BARR-JOE-1970-07-05', 1994),
  ('BateJe0', 'Jeremy Bates', '1976-08-27'::date, 'BATE-JERE-1976-08-27', 2002),
  ('BateJi0', 'Jim Bates', '1946-05-31'::date, 'BATE-JIM-1946-05-31', 1968),
  ('BeatCh0', 'Chris Beatty', '1973-06-19'::date, 'BEAT-CHRI-1973-06-19', 1998),
  ('BeigLa0', 'Larry Beightol', '1942-11-21'::date, 'BEIG-LARR-1942-11-21', 1977),
  ('BeliBi0', 'Bill Belichick', '1952-04-16'::date, 'BELI-BILL-1952-04-16', 1975),
  ('BennEd0', 'Edgar Bennett', '1969-02-15'::date, 'BENN-EDGA-1969-02-15', 2005),
  ('BettJa0', 'James Bettcher', '1978-05-27'::date, 'BETT-JAME-1978-05-27', 2003),
  ('BeveDa0', 'Darrell Bevell', '1970-01-06'::date, 'BEVE-DARR-1970-01-06', 1996),
  ('BiblDa0', 'Dana Bible', '1953-10-30'::date, 'BIBL-DANA-1953-10-30', 1976),
  ('BienEr0', 'Eric Bieniemy', '1969-08-15'::date, 'BIEN-ERIC-1969-08-15', 2000),
  ('BillBr0', 'Brian Billick', '1954-02-28'::date, 'BILL-BRIA-1954-02-28', 1978),
  ('BisaRi0', 'Rich Bisaccia', '1960-06-03'::date, 'BISA-RICH-1960-06-03', 1983),
  ('BlacDo0', 'Don Blackmon', '1958-03-14'::date, 'BLAC-DON-1958-03-14', 1988),
  ('BlacGr0', 'Greg Blache', '1949-03-09'::date, 'BLAC-GREG-1949-03-09', 1972),
  ('BoraRo0', 'Rob Boras', '1970-09-30'::date, 'BORA-ROB-1970-09-30', 1992),
  ('BoweSh0', 'Shane Bowen', '1986-12-09'::date, 'BOWE-SHAN-1986-12-09', 2009),
  ('BowlTo0', 'Todd Bowles', '1963-11-18'::date, 'BOWL-TODD-1963-11-18', 1997),
  ('BoyeJo0', 'Josh Boyer', '1977-01-21'::date, 'BOYE-JOSH-1977-01-21', 2000),
  ('BradGu0', 'Gus Bradley', '1966-07-05'::date, 'BRAD-GUS-1966-07-05', 1990),
  ('BradJo0', 'Joe Brady', '1989-09-23'::date, 'BRAD-JOE-1989-09-23', 2013),
  ('BradMa0', 'Marcus Brady', '1979-09-24'::date, 'BRAD-MARC-1979-09-24', 2009),
  ('BratBo0', 'Bob Bratkowski', '1955-12-02'::date, 'BRAT-BOB-1955-12-02', 1978),
  ('BrazDa0', 'Dave Brazil', '1936-03-25'::date, 'BRAZ-DAVE-1936-03-25', 1968),
  ('BreaDo0', 'Don Breaux', '1940-08-03'::date, 'BREA-DON-1940-08-03', 1966),
  ('BresCh0', 'Chuck Bresnahan', '1960-09-08'::date, 'BRES-CHUC-1960-09-08', 1983),
  ('BrooRi0', 'Rich Brooks', '1941-08-10'::date, 'BROO-RICH-1941-08-10', 1965),
  ('BrowKi0', 'Kippy Brown', '1955-03-06'::date, 'BROW-KIPP-1955-03-06', 1978),
  ('BrowTh0', 'Thomas Brown', '1986-05-15'::date, 'BROW-THOM-1986-05-15', 2011),
  ('BugeJo0', 'Joe Bugel', '1940-03-10'::date, 'BUGE-JOE-1940-03-10', 1964),
  ('BurkMa0', 'Matt Burke', '1976-03-25'::date, 'BURK-MATT-1976-03-25', 1998),
  ('BurnJa0', 'Jack Burns', '1949-01-03'::date, 'BURN-JACK-1949-01-03', 1978),
  ('BushFr0', 'Frank Bush', '1963-01-10'::date, 'BUSH-FRAN-1963-01-10', 1993),
  ('ButlKe0', 'Keith Butler', '1956-05-16'::date, 'BUTL-KEIT-1956-05-16', 1990),
  ('CablTo0', 'Tom Cable', '1964-11-26'::date, 'CABL-TOM-1964-11-26', 1987),
  ('CaldJi0', 'Jim Caldwell', '1955-01-16'::date, 'CALD-JIM-1955-01-16', 1977),
  ('CaldMi0', 'Mike Caldwell', '1971-08-31'::date, 'CALD-MIKE-1971-08-31', 2008),
  ('CaleNi0', 'Nick Caley', '1983-01-22'::date, 'CALE-NICK-1983-01-22', 2005),
  ('CalhTr0', 'Troy Calhoun', '1966-09-26'::date, 'CALH-TROY-1966-09-26', 1989),
  ('CallBi0', 'Bill Callahan', '1956-07-31'::date, 'CALL-BILL-1956-07-31', 1980),
  ('CallBr0', 'Brian Callahan', '1984-06-10'::date, 'CALL-BRIA-1984-06-10', 2010),
  ('CameCa0', 'Cam Cameron', '1961-02-06'::date, 'CAME-CAM-1961-02-06', 1984),
  ('CampAn0', 'Anthony Campanile', '1982-08-18'::date, 'CAMP-ANTH-1982-08-18', 2005),
  ('CampDa0', 'Dave Campo', '1947-07-18'::date, 'CAMP-DAVE-1947-07-18', 1971),
  ('CampDa1', 'Dan Campbell', '1976-04-13'::date, 'CAMP-DAN-1976-04-13', 2010),
  ('CanaDa0', 'Dave Canales', '1981-05-07'::date, 'CANA-DAVE-1981-05-07', 2004),
  ('CanaMa0', 'Matt Canada', '1972-01-19'::date, 'CANA-MATT-1972-01-19', 1994),
  ('CapeDo0', 'Dom Capers', '1950-08-07'::date, 'CAPE-DOM-1950-08-07', 1972),
  ('CarmPe0', 'Pete Carmichael', '1971-10-06'::date, 'CARM-PETE-1971-10-06', 1994),
  ('CarmPe1', 'Pete Carmichael', '1941-03-04'::date, 'CARM-PETE-1941-03-04', 1973),
  ('CarrPe0', 'Pete Carroll', '1951-09-15'::date, 'CARR-PETE-1951-09-15', 1973),
  ('CartMa0', 'Maurice Carthon', '1961-04-24'::date, 'CART-MAUR-1961-04-24', 1994),
  ('CastJu0', 'Juan Castillo', '1953-10-08'::date, 'CAST-JUAN-1953-10-08', 1982),
  ('CavaMa0', 'Matt Cavanaugh', '1956-10-27'::date, 'CAVA-MATT-1956-10-27', 1992),
  ('CeciCh0', 'Chuck Cecil', '1964-11-08'::date, 'CECI-CHUC-1964-11-08', 2001),
  ('ChilBr0', 'Brad Childress', '1956-06-27'::date, 'CHIL-BRAD-1956-06-27', 1978),
  ('ChowNo0', 'Norm Chow', '1946-05-03'::date, 'CHOW-NORM-1946-05-03', 1973),
  ('ChriCl0', 'Clyde Christensen', '1956-01-28'::date, 'CHRI-CLYD-1956-01-28', 1979),
  ('ChryGe0', 'Geep Chryst', '1962-06-25'::date, 'CHRY-GEEP-1962-06-25', 1987),
  ('ChudRo0', 'Rob Chudzinski', '1968-05-12'::date, 'CHUD-ROB-1968-05-12', 1994),
  ('CignFr0', 'Frank Cignetti', '1965-10-04'::date, 'CIGN-FRAN-1965-10-04', 1989),
  ('ClemTo0', 'Tom Clements', '1953-06-18'::date, 'CLEM-TOM-1953-06-18', 1992),
  ('CoenLi0', 'Liam Coen', '1985-11-08'::date, 'COEN-LIAM-1985-11-08', 2010),
  ('CollJi0', 'Jim Colletto', '1944-10-04'::date, 'COLL-JIM-1944-10-04', 1967),
  ('CootJi0', 'Jim Bob Cooter', '1984-07-03'::date, 'COOT-JIM-1984-07-03', 2007),
  ('CoreWa0', 'Walt Corey', '1938-05-09'::date, 'CORE-WALT-1938-05-09', 1972),
  ('CoslBr0', 'Bruce Coslet', '1946-08-05'::date, 'COSL-BRUC-1946-08-05', 1980),
  ('CottTe0', 'Ted Cottrell', '1947-06-13'::date, 'COTT-TED-1947-06-13', 1973),
  ('CougTo0', 'Tom Coughlin', '1946-08-31'::date, 'COUG-TOM-1946-08-31', 1969),
  ('CoviDe0', 'DeMarcus Covington', '1989-03-30'::date, 'COVI-DEMA-1989-03-30', 2012),
  ('CowhBi0', 'Bill Cowher', '1957-05-08'::date, 'COWH-BILL-1957-05-08', 1985),
  ('CoyeLa0', 'Larry Coyer', '1943-04-19'::date, 'COYE-LARR-1943-04-19', 1973),
  ('CoylKe0', 'Kevin Coyle', '1956-01-14'::date, 'COYL-KEVI-1956-01-14', 1978),
  ('CrenRo0', 'Romeo Crennel', '1947-06-18'::date, 'CREN-ROME-1947-06-18', 1970),
  ('CrooSy0', 'Sylvester Croom', '1954-09-25'::date, 'CROO-SYLV-1954-09-25', 1976),
  ('CrosSt0', 'Steve Crosby', '1950-07-03'::date, 'CROS-STEV-1950-07-03', 1979),
  ('CrowGa0', 'Gary Crowton', '1957-06-14'::date, 'CROW-GARY-1957-06-14', 1982),
  ('CullDa0', 'David Culley', '1955-09-17'::date, 'CULL-DAVI-1955-09-17', 1978),
  ('CullJo0', 'Joe Cullen', '1967-12-15'::date, 'CULL-JOE-1967-12-15', 1990),
  ('CunnGu0', 'Gunther Cunningham', '1946-06-19'::date, 'CUNN-GUNT-1946-06-19', 1969),
  ('DaboBr0', 'Brian Daboll', '1975-04-14'::date, 'DABO-BRIA-1975-04-14', 1997),
  ('DaviBi0', 'Bill Davis', '1965-11-05'::date, 'DAVI-BILL-1965-11-05', 1990),
  ('DaviBu0', 'Butch Davis', '1951-11-17'::date, 'DAVI-BUTC-1951-11-17', 1973),
  ('DaviJe0', 'Jeff Davidson', '1967-10-03'::date, 'DAVI-JEFF-1967-10-03', 1995),
  ('DeFiJo0', 'John DeFilippo', '1978-04-12'::date, 'DEFI-JOHN-1978-04-12', 2000),
  ('DelRJa0', 'Jack Del Rio', '1963-04-04'::date, 'RIO-JACK-1963-04-04', 1997),
  ('DennRi0', 'Rick Dennison', '1958-06-22'::date, 'DENN-RICK-1958-06-22', 1992),
  ('DesaSe0', 'Sean Desai', '1983-04-21'::date, 'DESA-SEAN-1983-04-21', 2006),
  ('DitkMi0', 'Mike Ditka', '1939-10-18'::date, 'DITK-MIKE-1939-10-18', 1973),
  ('DonaEd0', 'Ed Donatell', '1957-02-04'::date, 'DONA-ED-1957-02-04', 1979),
  ('DorsKe0', 'Ken Dorsey', '1981-04-22'::date, 'DORS-KEN-1981-04-22', 2011),
  ('DowhRo0', 'Rod Dowhower', '1943-04-15'::date, 'DOWH-ROD-1943-04-15', 1966),
  ('DownTo0', 'Todd Downing', '1980-07-22'::date, 'DOWN-TODD-1980-07-22', 1999),
  ('DoylDe0', 'Declan Doyle', '1900-01-01'::date, 'DOYL-DECL-0000-00-00', 2016),
  ('DuffMa0', 'Mark Duffner', '1953-07-19'::date, 'DUFF-MARK-1953-07-19', 1975),
  ('DungTo0', 'Tony Dungy', '1955-10-06'::date, 'DUNG-TONY-1955-10-06', 1980),
  ('DurdAd0', 'Aden Durde', '1979-07-10'::date, 'DURD-ADEN-1979-07-10', 2011),
  ('DyerGe0', 'George Dyer', '1940-05-04'::date, 'DYER-GEOR-1940-05-04', 1982),
  ('EberMa0', 'Matt Eberflus', '1970-05-17'::date, 'EBER-MATT-1970-05-17', 1992),
  ('EdwaGe0', 'George Edwards', '1967-01-16'::date, 'EDWA-GEOR-1967-01-16', 1991),
  ('EdwaHe0', 'Herm Edwards', '1954-04-27'::date, 'EDWA-HERM-1954-04-27', 1987),
  ('EngsTa0', 'Tanner Engstrand', '1982-06-18'::date, 'ENGS-TANN-1982-06-18', 2005),
  ('EricDe0', 'Dennis Erickson', '1947-03-24'::date, 'ERIC-DENN-1947-03-24', 1969),
  ('EverEj0', 'Ejiro Evero', '1981-01-06'::date, 'EVER-EJIR-1981-01-06', 2004),
  ('FairSt0', 'Steve Fairchild', '1958-06-21'::date, 'FAIR-STEV-1958-06-21', 1982),
  ('FangVi0', 'Vic Fangio', '1958-08-22'::date, 'FANG-VIC-1958-08-22', 1979),
  ('FassJi0', 'Jim Fassel', '1949-08-31'::date, 'FASS-JIM-1949-08-31', 1974),
  ('FassJo0', 'John Fassel', '1974-01-10'::date, 'FASS-JOHN-1974-01-10', 1999),
  ('FaulEd0', 'Eddie Faulkner', '1977-10-20'::date, 'FAUL-EDDI-1977-10-20', 2002),
  ('FaziFo0', 'Foge Fazio', '1938-02-28'::date, 'FAZI-FOGE-1938-02-28', 1965),
  ('FewePe0', 'Perry Fewell', '1962-09-07'::date, 'FEWE-PERR-1962-09-07', 1985),
  ('FichRa0', 'Randy Fichtner', '1963-11-07'::date, 'FICH-RAND-1963-11-07', 1986),
  ('FiscJe0', 'Jedd Fisch', '1976-05-05'::date, 'FISC-JEDD-1976-05-05', 1997),
  ('FishJe0', 'Jeff Fisher', '1958-02-25'::date, 'FISH-JEFF-1958-02-25', 1986),
  ('FlajKe0', 'Ken Flajole', '1954-10-04'::date, 'FLAJ-KEN-1954-10-04', 1994),
  ('FlorBr0', 'Brian Flores', '1981-02-24'::date, 'FLOR-BRIA-1981-02-24', 2004),
  ('FoerCh0', 'Chris Foerster', '1961-10-12'::date, 'FOER-CHRI-1961-10-12', 1982),
  ('FootLa0', 'Larry Foote', '1980-06-12'::date, 'FOOT-LARR-1980-06-12', 2015),
  ('FoxxJo0', 'John Fox', '1955-02-08'::date, 'FOX-JOHN-1955-02-08', 1978),
  ('FrazLe0', 'Leslie Frazier', '1959-04-03'::date, 'FRAZ-LESL-1959-04-03', 1988),
  ('GailCh0', 'Chan Gailey', '1952-01-05'::date, 'GAIL-CHAN-1952-01-05', 1974),
  ('GannJo0', 'Jonathan Gannon', '1983-04-04'::date, 'GANN-JONA-1983-04-04', 2003),
  ('GanzFr0', 'Frank Gansz', '1938-11-22'::date, 'GANS-FRAN-1938-11-22', 1964),
  ('GarrJa0', 'Jason Garrett', '1966-03-28'::date, 'GARR-JASO-1966-03-28', 2005),
  ('GaseAd0', 'Adam Gase', '1978-03-29'::date, 'GASE-ADAM-1978-03-29', 2000),
  ('GetsLu0', 'Luke Getsy', '1984-02-16'::date, 'GETS-LUKE-1984-02-16', 2007),
  ('GibbGa0', 'Gary Gibbs', '1952-08-13'::date, 'GIBB-GARY-1952-08-13', 1975),
  ('GibbJo0', 'Joe Gibbs', '1940-11-25'::date, 'GIBB-JOE-1940-11-25', 1964),
  ('GilbKe0', 'Kevin Gilbride', '1951-08-27'::date, 'GILB-KEVI-1951-08-27', 1974),
  ('GiunPe0', 'Peter Giunta', '1956-08-11'::date, 'GIUN-PETE-1956-08-11', 1978),
  ('GlenAa0', 'Aaron Glenn', '1972-07-16'::date, 'GLEN-AARO-1972-07-16', 2014),
  ('GodsGe0', 'George Godsey', '1979-01-01'::date, 'GODS-GEOR-1979-01-01', 2004),
  ('GoldAl0', 'Al Golden', '1969-07-04'::date, 'GOLD-AL-1969-07-04', 1993),
  ('GoodHa0', 'Harold Goodwin', '1973-11-14'::date, 'GOOD-HARO-1973-11-14', 1995),
  ('GrabDo0', 'Doug Graber', '1944-09-26'::date, 'GRAB-DOUG-1944-09-26', 1966),
  ('GrahPa0', 'Patrick Graham', '1979-01-24'::date, 'GRAH-PATR-1979-01-24', 2002),
  ('GranTo0', 'Todd Grantham', '1966-09-13'::date, 'GRAN-TODD-1966-09-13', 1990),
  ('GrayJe0', 'Jerry Gray', '1962-12-16'::date, 'GRAY-JERR-1962-12-16', 1995),
  ('GreeDe0', 'Dennis Green', '1949-02-17'::date, 'GREE-DENN-1949-02-17', 1972),
  ('GrizJo0', 'Josh Grizzard', '1990-06-11'::date, 'GRIZ-JOSH-1990-06-11', 2012),
  ('GrohAl0', 'Al Groh', '1944-07-13'::date, 'GROH-AL-1944-07-13', 1967),
  ('GrohMi0', 'Mike Groh', '1971-12-19'::date, 'GROH-MIKE-1971-12-19', 2000),
  ('GrubRy0', 'Ryan Grubb', '1976-04-16'::date, 'GRUB-RYAN-1976-04-16', 2003),
  ('GrudJa0', 'Jay Gruden', '1967-03-04'::date, 'GRUD-JAY-1967-03-04', 1997),
  ('GrudJo0', 'Jon Gruden', '1963-08-17'::date, 'GRUD-JON-1963-08-17', 1986),
  ('GuenPa0', 'Paul Guenther', '1971-11-22'::date, 'GUEN-PAUL-1971-11-22', 1994),
  ('HackNa0', 'Nathaniel Hackett', '1979-12-19'::date, 'HACK-NATH-1979-12-19', 2002),
  ('HackPa0', 'Paul Hackett', '1947-07-05'::date, 'HACK-PAUL-1947-07-05', 1972),
  ('HaflJe0', 'Jeff Hafley', '1979-04-04'::date, 'HAFL-JEFF-1979-04-04', 2001),
  ('HaleTo0', 'Todd Haley', '1967-02-28'::date, 'HALE-TODD-1967-02-28', 1997),
  ('HamiPe0', 'Pep Hamilton', '1974-09-19'::date, 'HAMI-PEP-1974-09-19', 1997),
  ('HaniJi0', 'Jim Hanifan', '1933-09-21'::date, 'HANI-JIM-1933-09-21', 1959),
  ('HarbJi0', 'Jim Harbaugh', '1963-12-23'::date, 'HARB-JIM-1963-12-23', 1994),
  ('HarbJo0', 'John Harbaugh', '1962-09-23'::date, 'HARB-JOHN-1962-09-23', 1984),
  ('HardBo0', 'Bo Hardegree', '1984-07-05'::date, 'HARD-BO-1984-07-05', 2008),
  ('HarrCh0', 'Chick Harris', '1945-09-21'::date, 'HARR-CHIC-1945-09-21', 1981),
  ('HaskGi0', 'Gil Haskell', '1943-09-24'::date, 'HASK-GIL-1943-09-24', 1973),
  ('HaslJi0', 'Jim Haslett', '1955-12-09'::date, 'HASL-JIM-1955-12-09', 1988),
  ('HeimMi0', 'Mike Heimerdinger', '1952-10-13'::date, 'HEIM-MIKE-1952-10-13', 1980),
  ('HelfMa0', 'Mark Helfrich', '1973-10-28'::date, 'HELF-MARK-1973-10-28', 1996),
  ('HendDo0', 'Donnie Henderson', '1957-05-17'::date, 'HEND-DONN-1957-05-17', 1983),
  ('HennDa0', 'Dan Henning', '1942-06-21'::date, 'HENN-DAN-1942-06-21', 1968),
  ('HensGe0', 'George Henshaw', '1948-01-22'::date, 'HENS-GEOR-1948-01-22', 1970),
  ('HillGe0', 'George Hill', '1933-04-28'::date, 'HILL-GEOR-1933-04-28', 1960),
  ('HillRe0', 'Renaldo Hill', '1978-11-12'::date, 'HILL-RENA-1978-11-12', 2012),
  ('HolcAl0', 'Al Holcomb', '1970-10-22'::date, 'HOLC-AL-1970-10-22', 1995),
  ('HolmMi0', 'Mike Holmgren', '1948-06-15'::date, 'HOLM-MIKE-1948-06-15', 1971),
  ('HolzNi0', 'Nick Holz', '1984-03-26'::date, 'HOLZ-NICK-1984-03-26', 2007),
  ('HortRa0', 'Ray Horton', '1960-04-12'::date, 'HORT-RAY-1960-04-12', 1994),
  ('HostJi0', 'Jim Hostler', '1966-11-11'::date, 'HOST-JIM-1966-11-11', 1990),
  ('HufnJo0', 'John Hufnagel', '1951-09-13'::date, 'HUFN-JOHN-1951-09-13', 1988),
  ('HuntHa1', 'Hal Hunter', '1959-07-08'::date, 'HUNT-HAL-1959-07-08', 1982),
  ('HurtCl0', 'Clint Hurtt', '1978-11-07'::date, 'HURT-CLIN-1978-11-07', 2003),
  ('IdziBr0', 'Brad Idzik', '1991-10-20'::date, 'IDZI-BRAD-1991-10-20', 2014),
  ('JackBo0', 'Bobby Jackson', '1940-02-16'::date, 'JACK-BOBB-1940-02-16', 1965),
  ('JackHu0', 'Hue Jackson', '1965-10-22'::date, 'JACK-HUE-1965-10-22', 1987),
  ('JackMi0', 'Milt Jackson', '1943-10-16'::date, 'JACK-MILT-1943-10-16', 1980),
  ('JagoJe0', 'Jeff Jagodzinski', '1963-10-12'::date, 'JAGO-JEFF-1963-10-12', 1985),
  ('JaurDi0', 'Dick Jauron', '1950-10-07'::date, 'JAUR-DICK-1950-10-07', 1985),
  ('JohnBe0', 'Ben Johnson', '1986-05-11'::date, 'JOHN-BEN-1986-05-11', 2009),
  ('JohnBr0', 'Brian Johnson', '1987-02-16'::date, 'JOHN-BRIA-1987-02-16', 2010),
  ('JohnJi0', 'Jimmy Johnson', '1943-07-16'::date, 'JOHN-JIMM-1943-07-16', 1965),
  ('JohnJi1', 'Jim Johnson', '1941-05-26'::date, 'JOHN-JIM-1941-05-26', 1977),
  ('JoneRo0', 'Ronnie Jones', '1955-10-17'::date, 'JONE-RONN-1955-10-17', 1978),
  ('JoseVa0', 'Vance Joseph', '1972-09-20'::date, 'JOSE-VANC-1972-09-20', 1999),
  ('JudgJo0', 'Joe Judge', '1981-12-31'::date, 'JUDG-JOE-1981-12-31', 2005),
  ('KafkMi0', 'Mike Kafka', '1987-07-25'::date, 'KAFK-MIKE-1987-07-25', 2016),
  ('KellCh0', 'Chip Kelly', '1963-11-25'::date, 'KELL-CHIP-1963-11-25', 1990),
  ('KellTi0', 'Tim Kelly', '1986-08-17'::date, 'KELL-TIM-1986-08-17', 2008),
  ('KiffLa0', 'Lane Kiffin', '1975-05-09'::date, 'KIFF-LANE-1975-05-09', 1997),
  ('KiffMo0', 'Monte Kiffin', '1940-02-29'::date, 'KIFF-MONT-1940-02-29', 1966),
  ('KingKl0', 'Kliff Kingsbury', '1979-08-09'::date, 'KING-KLIF-1979-08-09', 2008),
  ('KitcFr0', 'Freddie Kitchens', '1974-11-29'::date, 'KITC-FRED-1974-11-29', 1999),
  ('KnapGr0', 'Greg Knapp', '1963-03-05'::date, 'KNAP-GREG-1963-03-05', 1986),
  ('KoetDi0', 'Dirk Koetter', '1959-02-05'::date, 'KOET-DIRK-1959-02-05', 1983),
  ('KromAa0', 'Aaron Kromer', '1967-04-30'::date, 'KROM-AARO-1967-04-30', 1990),
  ('KrucMi0', 'Mike Kruczek', '1953-03-15'::date, 'KRUC-MIKE-1953-03-15', 1982),
  ('KubiGa0', 'Gary Kubiak', '1961-08-15'::date, 'KUBI-GARY-1961-08-15', 1992),
  ('KubiKl0', 'Klint Kubiak', '1987-02-17'::date, 'KUBI-KLIN-1987-02-17', 2010),
  ('KubiKl1', 'Klay Kubiak', '1900-01-01'::date, 'KUBI-KLAY-0000-00-00', 2013),
  ('KuhlHa0', 'Hank Kuhlmann', '1937-10-06'::date, 'KUHL-HANK-1937-10-06', 1962),
  ('KuhrZa0', 'Zak Kuhr', '1988-04-19'::date, 'KUHR-ZAK-1988-04-19', 2008),
  ('LaFlMa0', 'Matt LaFleur', '1979-11-03'::date, 'LAFL-MATT-1979-11-03', 2003),
  ('LaFlMi0', 'Mike LaFleur', '1900-01-01'::date, 'LAFL-MIKE-0000-00-00', 2009),
  ('LakeJi0', 'Jimmy Lake', '1976-09-17'::date, 'LAKE-JIMM-1976-09-17', 1999),
  ('LawrDo0', 'Don Lawrence', '1937-06-04'::date, 'LAWR-DON-1937-06-04', 1964),
  ('LazoBi0', 'Bill Lazor', '1972-06-14'::date, 'LAZO-BILL-1972-06-14', 1994),
  ('LeBeDi0', 'Dick LeBeau', '1937-09-09'::date, 'LEBE-DICK-1937-09-09', 1973),
  ('LeftBy0', 'Byron Leftwich', '1980-01-14'::date, 'LEFT-BYRO-1980-01-14', 2016),
  ('LevrJo0', 'John Levra', '1937-10-02'::date, 'LEVR-JOHN-1937-10-02', 1966),
  ('LewiMa0', 'Marvin Lewis', '1958-09-23'::date, 'LEWI-MARV-1958-09-23', 1981),
  ('LewiSh0', 'Sherman Lewis', '1942-06-29'::date, 'LEWI-SHER-1942-06-29', 1969),
  ('LewiTi0', 'Tim Lewis', '1961-12-18'::date, 'LEWI-TIM-1961-12-18', 1987),
  ('LindDa0', 'Dale Lindsey', '1943-01-18'::date, 'LIND-DALE-1943-01-18', 1974),
  ('LindJi0', 'Jim Lind', '1947-11-11'::date, 'LIND-JIM-1947-11-11', 1974),
  ('LineSc0', 'Scott Linehan', '1963-09-17'::date, 'LINE-SCOT-1963-09-17', 1987),
  ('LoggDo0', 'Dowell Loggains', '1980-10-01'::date, 'LOGG-DOWE-1980-10-01', 2005),
  ('LombJo0', 'Joe Lombardi', '1971-06-06'::date, 'LOMB-JOE-1971-06-06', 1996),
  ('LombMi1', 'Mick Lombardi', '1988-10-01'::date, 'LOMB-MICK-1988-10-01', 2009),
  ('LoneSt0', 'Steve Loney', '1952-04-26'::date, 'LONE-STEV-1952-04-26', 1974),
  ('LynnAn0', 'Anthony Lynn', '1968-12-21'::date, 'LYNN-ANTH-1968-12-21', 2000),
  ('LynnJo0', 'Johnny Lynn', '1956-12-19'::date, 'LYNN-JOHN-1956-12-19', 1994),
  ('LynnRo0', 'Ron Lynn', '1944-12-06'::date, 'LYNN-RON-1944-12-06', 1967),
  ('MacdMi0', 'Mike Macdonald', '1987-06-26'::date, 'MACD-MIKE-1987-06-26', 2008),
  ('MangEr0', 'Eric Mangini', '1971-01-19'::date, 'MANG-ERIC-1971-01-19', 1995),
  ('MangPe0', 'Pete Mangurian', '1955-06-17'::date, 'MANG-PETE-1955-06-17', 1979),
  ('ManuGr0', 'Greg Manusky', '1966-08-12'::date, 'MANU-GREG-1966-08-12', 2001),
  ('ManuMa0', 'Marquand Manuel', '1979-07-11'::date, 'MANU-MARQ-1979-07-11', 2012),
  ('MariRo0', 'Rod Marinelli', '1949-07-13'::date, 'MARI-ROD-1949-07-13', 1973),
  ('MariSt0', 'Steve Mariucci', '1955-11-04'::date, 'MARI-STEV-1955-11-04', 1978),
  ('MarmLa0', 'Larry Marmie', '1942-10-17'::date, 'MARM-LARR-1942-10-17', 1985),
  ('MarrDo0', 'Doug Marrone', '1964-07-25'::date, 'MARR-DOUG-1964-07-25', 1992),
  ('MarsJo0', 'John Marshall', '1945-10-02'::date, 'MARS-JOHN-1945-10-02', 1967),
  ('MartDo0', 'Don Martindale', '1963-05-19'::date, 'MART-DON-1963-05-19', 1986),
  ('MartMi0', 'Mike Martz', '1951-05-13'::date, 'MART-MIKE-1951-05-13', 1973),
  ('MattGr0', 'Greg Mattison', '1949-11-15'::date, 'MATT-GREG-1949-11-15', 1971),
  ('MayoJe0', 'Jerod Mayo', '1986-02-23'::date, 'MAYO-JERO-1986-02-23', 2019),
  ('McAdBe0', 'Ben McAdoo', '1977-07-09'::date, 'MCAD-BEN-1977-07-09', 2001),
  ('McCaMi0', 'Mike McCarthy', '1963-11-10'::date, 'MCCA-MIKE-1963-11-10', 1987),
  ('McCoMi1', 'Mike McCoy', '1972-04-01'::date, 'MCCO-MIKE-1972-04-01', 2000),
  ('McDaJo0', 'Josh McDaniels', '1976-04-22'::date, 'MCDA-JOSH-1976-04-22', 1999),
  ('McDaMi0', 'Mike McDaniel', '1983-03-06'::date, 'MCDA-MIKE-1983-03-06', 2005),
  ('McDeSe0', 'Sean McDermott', '1974-03-21'::date, 'MCDE-SEAN-1974-03-21', 1998),
  ('McGiDa0', 'Dave McGinnis', '1951-08-07'::date, 'MCGI-DAVE-1951-08-07', 1973),
  ('McMaGr0', 'Greg McMackin', '1945-04-24'::date, 'MCMA-GREG-1945-04-24', 1968),
  ('McVaSe0', 'Sean McVay', '1986-01-24'::date, 'MCVA-SEAN-1986-01-24', 2008),
  ('MeekRo0', 'Ron Meeks', '1954-08-27'::date, 'MEEK-RON-1954-08-27', 1984),
  ('MeyeUr0', 'Urban Meyer', '1964-07-10'::date, 'MEYE-URBA-1964-07-10', 1985),
  ('MichJa0', 'Jason Michael', '1978-10-15'::date, 'MICH-JASO-1978-10-15', 2003),
  ('MillKe0', 'Keith Millard', '1962-03-18'::date, 'MILL-KEIT-1962-03-18', 2000),
  ('MillMi0', 'Mike Miller', '1970-04-09'::date, 'MILL-MIKE-1970-04-09', 1999),
  ('MintJe0', 'Jesse Minter', '1983-05-09'::date, 'MINT-JESS-1983-05-09', 2006),
  ('ModkCu0', 'Curtis Modkins', '1970-11-15'::date, 'MODK-CURT-1970-11-15', 1995),
  ('MoelGa0', 'Gary Moeller', '1941-01-26'::date, 'MOEL-GARY-1941-01-26', 1967),
  ('MonaTe0', 'Ted Monachino', '1966-10-15'::date, 'MONA-TED-1966-10-15', 1991),
  ('MonkTo0', 'Todd Monken', '1966-02-05'::date, 'MONK-TODD-1966-02-05', 1989),
  ('MoorKe0', 'Kellen Moore', '1989-07-12'::date, 'MOOR-KELL-1989-07-12', 2018),
  ('MoorTo0', 'Tom Moore', '1938-11-07'::date, 'MOOR-TOM-1938-11-07', 1961),
  ('MoraJi0', 'Jim Mora', '1935-05-24'::date, 'MORA-JIM-1935-05-24', 1961),
  ('MoraJi1', 'Jim Mora', '1961-11-19'::date, 'MORA-JIM-1961-11-19', 1984),
  ('MornMa0', 'Marty Mornhinweg', '1962-03-29'::date, 'MORN-MART-1962-03-29', 1985),
  ('MorrRa0', 'Raheem Morris', '1976-09-03'::date, 'MORR-RAHE-1976-09-03', 1998),
  ('MortJo0', 'John Morton', '1969-09-24'::date, 'MORT-JOHN-1969-09-24', 2002),
  ('MuirBi0', 'Bill Muir', '1942-10-26'::date, 'MUIR-BILL-1942-10-26', 1982),
  ('MulaMi0', 'Mike Mularkey', '1961-11-19'::date, 'MULA-MIKE-1961-11-19', 1993),
  ('MuncMi0', 'Mike Munchak', '1960-03-05'::date, 'MUNC-MIKE-1960-03-05', 1994),
  ('MusgBi0', 'Bill Musgrave', '1967-11-11'::date, 'MUSG-BILL-1967-11-11', 1997),
  ('NagyMa0', 'Matt Nagy', '1978-04-24'::date, 'NAGY-MATT-1978-04-24', 2008),
  ('NeuhRi0', 'Rick Neuheisel', '1961-02-07'::date, 'NEUH-RICK-1961-02-07', 1986),
  ('NielRy0', 'Ryan Nielsen', '1979-03-20'::date, 'NIEL-RYAN-1979-03-20', 2002),
  ('NixoJe0', 'Jeff Nixon', '1974-10-16'::date, 'NIXO-JEFF-1974-10-16', 1997),
  ('NolaMi0', 'Mike Nolan', '1959-03-07'::date, 'NOLA-MIKE-1959-03-07', 1981),
  ('NortKe0', 'Ken Norton Jr.', '1966-09-29'::date, 'NORT-KEN-1966-09-29', 2004),
  ('NussDo0', 'Doug Nussmeier', '1970-12-11'::date, 'NUSS-DOUG-1970-12-11', 2001),
  ('O''LeGe0', 'George O''Leary', '1946-08-17'::date, 'OLEA-GEOR-1946-08-17', 1968),
  ('OBriBi0', 'Bill O''Brien', '1969-10-23'::date, 'OBRI-BILL-1969-10-23', 1993),
  ('OConKe0', 'Kevin O''Connell', '1985-05-25'::date, 'OCON-KEVI-1985-05-25', 2015),
  ('OlivTo0', 'Tom Olivadotti', '1945-09-22'::date, 'OLIV-TOM-1945-09-22', 1981),
  ('OlsoGr0', 'Greg Olson', '1963-03-01'::date, 'OLSO-GREG-1963-03-01', 1987),
  ('OlsoRi0', 'Rich Olson', '1948-07-07'::date, 'OLSO-RICH-1948-07-07', 1984),
  ('ONeiJi0', 'Jim O''Neil', '1978-10-26'::date, 'ONEI-JIM-1978-10-26', 2001),
  ('OrrxZa0', 'Zach Orr', '1992-06-09'::date, 'ORR-ZACH-1992-06-09', 2017),
  ('OSheCh0', 'Chad O''Shea', '1972-12-18'::date, 'OSHE-CHAD-1972-12-18', 1996),
  ('OuttJu0', 'Justin Outten', '1983-10-26'::date, 'OUTT-JUST-1983-10-26', 2007),
  ('PagaCh0', 'Chuck Pagano', '1960-10-02'::date, 'PAGA-CHUC-1960-10-02', 1984),
  ('PagaFr0', 'Fred Pagac', '1952-04-26'::date, 'PAGA-FRED-1952-04-26', 1978),
  ('PagaJo0', 'John Pagano', '1967-03-30'::date, 'PAGA-JOHN-1967-03-30', 1994),
  ('PalmCh0', 'Chris Palmer', '1949-09-23'::date, 'PALM-CHRI-1949-09-23', 1972),
  ('ParcBi0', 'Bill Parcells', '1941-08-22'::date, 'PARC-BILL-1941-08-22', 1964),
  ('PascJo0', 'Joe Pascale', '1946-04-17'::date, 'PASC-JOE-1946-04-17', 1976),
  ('PasqPa0', 'Paul Pasqualoni', '1949-08-16'::date, 'PASQ-PAUL-1949-08-16', 1972),
  ('PatrMa0', 'Matt Patricia', '1974-09-13'::date, 'PATR-MATT-1974-09-13', 1996),
  ('PattAn0', 'Andre Patterson', '1960-06-12'::date, 'PATT-ANDR-1960-06-12', 1982),
  ('PatuKe0', 'Kevin Patullo', '1981-07-14'::date, 'PATU-KEVI-1981-07-14', 2003),
  ('PaytSe0', 'Sean Payton', '1963-12-29'::date, 'PAYT-SEAN-1963-12-29', 1988),
  ('PeasJo0', 'John Pease', '1943-10-14'::date, 'PEAS-JOHN-1943-10-14', 1968),
  ('PeccLa0', 'Larry Peccatiello', '1935-12-21'::date, 'PECC-LARR-1935-12-21', 1961),
  ('PedeDo0', 'Doug Pederson', '1968-01-31'::date, 'PEDE-DOUG-1968-01-31', 2005),
  ('PeesDe0', 'Dean Pees', '1949-09-04'::date, 'PEES-DEAN-1949-09-04', 1979),
  ('PendCl0', 'Clancy Pendergast', '1967-11-29'::date, 'PEND-CLAN-1967-11-29', 1991),
  ('PendJo0', 'Joe Pendry', '1947-08-05'::date, 'PEND-JOE-1947-08-05', 1970),
  ('PerkRa0', 'Ray Perkins', '1941-11-06'::date, 'PERK-RAY-1941-11-06', 1973),
  ('PetrBo0', 'Bobby Petrino', '1961-03-10'::date, 'PETR-BOBB-1961-03-10', 1983),
  ('PettMi0', 'Mike Pettine', '1966-09-25'::date, 'PETT-MIKE-1966-09-25', 1988),
  ('PetzDr0', 'Drew Petzing', '1987-03-12'::date, 'PETZ-DREW-1987-03-12', 2009),
  ('PhilJo0', 'Joe Philbin', '1961-07-02'::date, 'PHIL-JOE-1961-07-02', 1984),
  ('PhilWa0', 'Wade Phillips', '1947-06-21'::date, 'PHIL-WADE-1947-06-21', 1969),
  ('PhilWe0', 'Wes Phillips', '1979-02-17'::date, 'PHIL-WES-1979-02-17', 2003),
  ('PierAn0', 'Antonio Pierce', '1978-10-26'::date, 'PIER-ANTO-1978-10-26', 2014),
  ('PitcDa0', 'Dan Pitcher', '1987-01-13'::date, 'PITC-DAN-1987-01-13', 2012),
  ('PopeMi0', 'Mike Pope', '1942-03-14'::date, 'POPE-MIKE-1942-03-14', 1983),
  ('QuinDa0', 'Dan Quinn', '1970-09-11'::date, 'QUIN-DAN-1970-09-11', 1994),
  ('RagoDa0', 'Dave Ragone', '1979-10-03'::date, 'RAGO-DAVE-1979-10-03', 2010),
  ('RallNi0', 'Nick Rallis', '1993-07-13'::date, 'RALL-NICK-1993-07-13', 2017),
  ('RayeJi0', 'Jimmy Raye', '1946-03-26'::date, 'RAYE-JIMM-1946-03-26', 1971),
  ('ReesTo0', 'Tommy Rees', '1992-05-22'::date, 'REES-TOMM-1992-05-22', 2015),
  ('ReevDa0', 'Dan Reeves', '1944-01-19'::date, 'REEV-DAN-1944-01-19', 1975),
  ('ReicFr0', 'Frank Reich', '1961-12-04'::date, 'REIC-FRAN-1961-12-04', 2006),
  ('ReidAn0', 'Andy Reid', '1958-03-19'::date, 'REID-ANDY-1958-03-19', 1982),
  ('ReilJa0', 'Jack Reilly', '1946-05-22'::date, 'REIL-JACK-1946-05-22', 1980),
  ('RhodRa0', 'Ray Rhodes', '1950-10-20'::date, 'RHOD-RAY-1950-10-20', 1981),
  ('RhomJe0', 'Jerry Rhome', '1942-03-06'::date, 'RHOM-JERR-1942-03-06', 1973),
  ('RhulMa0', 'Matt Rhule', '1975-01-31'::date, 'RHUL-MATT-1975-01-31', 1998),
  ('RichKr0', 'Kris Richard', '1978-10-28'::date, 'RICH-KRIS-1978-10-28', 2008),
  ('RileMi0', 'Mike Riley', '1953-07-06'::date, 'RILE-MIKE-1953-07-06', 1975),
  ('RiveRo0', 'Ron Rivera', '1962-01-07'::date, 'RIVE-RON-1962-01-07', 1997),
  ('RizzDa0', 'Darren Rizzi', '1970-07-21'::date, 'RIZZ-DARR-1970-07-21', 1993),
  ('RobiGr0', 'Greg Robinson', '1951-10-09'::date, 'ROBI-GREG-1951-10-09', 1975),
  ('RobiTe0', 'Terry Robiskie', '1954-11-12'::date, 'ROBI-TERR-1954-11-12', 1982),
  ('RobiWi0', 'Willy Robinson', '1956-02-10'::date, 'ROBI-WILL-1956-02-10', 1992),
  ('RobiZa0', 'Zac Robinson', '1986-09-29'::date, 'ROBI-ZAC-1986-09-29', 2019),
  ('RodgKa0', 'Kacy Rodgers', '1969-06-24'::date, 'RODG-KACY-1969-06-24', 1994),
  ('RomaGr0', 'Greg Roman', '1972-08-19'::date, 'ROMA-GREG-1972-08-19', 1995),
  ('RosbJe0', 'Jerry Rosburg', '1955-11-24'::date, 'ROSB-JERR-1955-11-24', 1979),
  ('RossBo0', 'Bobby Ross', '1935-12-23'::date, 'ROSS-BOBB-1935-12-23', 1965),
  ('RossTo0', 'Tom Rossley', '1946-08-09'::date, 'ROSS-TOM-1946-08-09', 1976),
  ('RoweKe0', 'Keith Rowen', '1952-09-02'::date, 'ROWE-KEIT-1952-09-02', 1977),
  ('RustRo0', 'Rod Rust', '1928-08-02'::date, 'RUST-ROD-1928-08-02', 1960),
  ('RyanDe0', 'DeMeco Ryans', '1984-07-28'::date, 'RYAN-DEME-1984-07-28', 2017),
  ('RyanRe0', 'Rex Ryan', '1962-12-13'::date, 'RYAN-REX-1962-12-13', 1987),
  ('RyanRo0', 'Rob Ryan', '1962-12-13'::date, 'RYAN-ROB-1962-12-13', 1987),
  ('SabaNi0', 'Nick Saban', '1951-10-31'::date, 'SABA-NICK-1951-10-31', 1973),
  ('SaleRo0', 'Robert Saleh', '1979-01-31'::date, 'SALE-ROBE-1979-01-31', 2002),
  ('SandBo0', 'Bob Sanders', '1953-12-05'::date, 'SAND-BOB-1953-12-05', 1978),
  ('SarkSt0', 'Steve Sarkisian', '1974-03-08'::date, 'SARK-STEV-1974-03-08', 2000),
  ('SatuJe0', 'Jeff Saturday', '1975-06-18'::date, 'SATU-JEFF-1975-06-18', 2017),
  ('SaunAl0', 'Al Saunders', '1947-02-01'::date, 'SAUN-AL-1947-02-01', 1970),
  ('ScanRi0', 'Rich Scangarello', '1972-04-15'::date, 'SCAN-RICH-1972-04-15', 1998),
  ('SchiGr0', 'Greg Schiano', '1966-06-01'::date, 'SCHI-GREG-1966-06-01', 1989),
  ('SchoBr0', 'Brian Schottenheimer', '1973-10-16'::date, 'SCHO-BRIA-1973-10-16', 1997),
  ('SchoKu0', 'Kurt Schottenheimer', '1949-10-01'::date, 'SCHO-KURT-1949-10-01', 1974),
  ('SchoMa0', 'Marty Schottenheimer', '1943-09-23'::date, 'SCHO-MART-1943-09-23', 1974),
  ('SchoTu0', 'Turk Schonert', '1957-01-15'::date, 'SCHO-TURK-1957-01-15', 1992),
  ('SchwJi0', 'Jim Schwartz', '1966-06-02'::date, 'SCHW-JIM-1966-06-02', 1989),
  ('SefcGe0', 'George Sefcik', '1939-12-27'::date, 'SEFC-GEOR-1939-12-27', 1964),
  ('SeifGe0', 'George Seifert', '1940-01-22'::date, 'SEIF-GEOR-1940-01-22', 1964),
  ('ShanKy0', 'Kyle Shanahan', '1979-12-14'::date, 'SHAN-KYLE-1979-12-14', 2003),
  ('ShanMi0', 'Mike Shanahan', '1952-08-24'::date, 'SHAN-MIKE-1952-08-24', 1975),
  ('ShawWi0', 'Willie Shaw', '1944-01-11'::date, 'SHAW-WILL-1944-01-11', 1974),
  ('SheaTe0', 'Terry Shea', '1946-06-12'::date, 'SHEA-TERR-1946-06-12', 1968),
  ('ShelAr0', 'Art Shell', '1946-11-26'::date, 'SHEL-ART-1946-11-26', 1983),
  ('ShelCl0', 'Clarence Shelmon', '1952-09-17'::date, 'SHEL-CLAR-1952-09-17', 1975),
  ('ShepKe0', 'Kelvin Sheppard', '1988-01-02'::date, 'SHEP-KELV-1988-01-02', 2021),
  ('ShepMi0', 'Mike Sheppard', '1951-10-29'::date, 'SHEP-MIKE-1951-10-29', 1977),
  ('SherBi0', 'Bill Sheridan', '1959-01-27'::date, 'SHER-BILL-1959-01-27', 1981),
  ('SherMi0', 'Mike Sherman', '1954-12-19'::date, 'SHER-MIKE-1954-12-19', 1978),
  ('SherRa0', 'Ray Sherman', '1951-11-27'::date, 'SHER-RAY-1951-11-27', 1974),
  ('ShooJo0', 'John Shoop', '1969-08-01'::date, 'SHOO-JOHN-1969-08-01', 1991),
  ('ShulCh0', 'Chris Shula', '1986-02-05'::date, 'SHUL-CHRI-1986-02-05', 2010),
  ('ShulMi0', 'Mike Shula', '1965-06-03'::date, 'SHUL-MIKE-1965-06-03', 1988),
  ('ShurPa0', 'Pat Shurmur', '1965-04-14'::date, 'SHUR-PAT-1965-04-14', 1990),
  ('SidwSt0', 'Steve Sidwell', '1944-08-30'::date, 'SIDW-STEV-1944-08-30', 1966),
  ('SingMi0', 'Mike Singletary', '1958-10-09'::date, 'SING-MIKE-1958-10-09', 2003),
  ('SiriNi0', 'Nick Sirianni', '1981-06-15'::date, 'SIRI-NICK-1981-06-15', 2004),
  ('SkipJi0', 'Jim Skipper', '1949-01-23'::date, 'SKIP-JIM-1949-01-23', 1977),
  ('SlowBo0', 'Bob Slowik', '1954-05-16'::date, 'SLOW-BOB-1954-05-16', 1984),
  ('SlowBo1', 'Bobby Slowik', '1987-06-09'::date, 'SLOW-BOBB-1987-06-09', 2011),
  ('SmitAr0', 'Arthur Smith', '1982-05-27'::date, 'SMIT-ARTH-1982-05-27', 2006),
  ('SmitCa0', 'Carl Smith', '1948-04-26'::date, 'SMIT-CARL-1948-04-26', 1971),
  ('SmitFr0', 'Frank Smith', '1981-02-21'::date, 'SMIT-FRAN-1981-02-21', 2004),
  ('SmitGi0', 'Giff Smith', '1900-01-01'::date, 'SMIT-GIFF-0000-00-00', 1991),
  ('SmitLo0', 'Lovie Smith', '1958-05-08'::date, 'SMIT-LOVI-1958-05-08', 1980),
  ('SmitMi0', 'Mike Smith', '1959-06-13'::date, 'SMIT-MIKE-1959-06-13', 1982),
  ('SmitRi0', 'Richard Smith', '1955-10-17'::date, 'SMIT-RICH-1955-10-17', 1979),
  ('SmitSh0', 'Sherman Smith', '1954-11-01'::date, 'SMIT-SHER-1954-11-01', 1984),
  ('SnowPh0', 'Phil Snow', '1955-12-22'::date, 'SNOW-PHIL-1955-12-22', 1976),
  ('SolaMi0', 'Mike Solari', '1955-01-16'::date, 'SOLA-MIKE-1955-01-16', 1986),
  ('SoreNi0', 'Nick Sorensen', '1978-07-31'::date, 'SORE-NICK-1978-07-31', 2012),
  ('SpagSt0', 'Steve Spagnuolo', '1959-12-21'::date, 'SPAG-STEV-1959-12-21', 1981),
  ('SparTo0', 'Tony Sparano', '1961-10-07'::date, 'SPAR-TONY-1961-10-07', 1984),
  ('SpurSt0', 'Steve Spurrier', '1945-04-20'::date, 'SPUR-STEV-1945-04-20', 1978),
  ('StalBr0', 'Brandon Staley', '1982-12-10'::date, 'STAL-BRAN-1982-12-10', 2006),
  ('StecLe0', 'Les Steckel', '1946-07-01'::date, 'STEC-LES-1946-07-01', 1973),
  ('StefKe0', 'Kevin Stefanski', '1982-05-08'::date, 'STEF-KEVI-1982-05-08', 2006),
  ('SteiSh0', 'Shane Steichen', '1985-05-11'::date, 'STEI-SHAN-1985-05-11', 2010),
  ('StenAd0', 'Adam Stenavich', '1983-03-11'::date, 'STEN-ADAM-1983-03-11', 2012),
  ('StevGa0', 'Gary Stevens', '1943-03-19'::date, 'STEV-GARY-1943-03-19', 1976),
  ('StewBr0', 'Brian Stewart', '1964-12-04'::date, 'STEW-BRIA-1964-12-04', 1993),
  ('StudEr0', 'Eric Studesville', '1967-05-29'::date, 'STUD-ERIC-1967-05-29', 1991),
  ('SullJe0', 'Jerry Sullivan', '1944-07-13'::date, 'SULL-JERR-1944-07-13', 1971),
  ('SullMi0', 'Mike Sullivan', '1967-01-28'::date, 'SULL-MIKE-1967-01-28', 1993),
  ('SuttBo0', 'Bob Sutton', '1951-01-28'::date, 'SUTT-BOB-1951-01-28', 1972),
  ('TaboCh0', 'Chris Tabor', '1971-03-04'::date, 'TABO-CHRI-1971-03-04', 1993),
  ('TarvJa0', 'Jason Tarver', '1974-08-28'::date, 'TARV-JASO-1974-08-28', 1996),
  ('TaylPr0', 'Press Taylor', '1988-01-13'::date, 'TAYL-PRES-1988-01-13', 2011),
  ('TaylZa0', 'Zac Taylor', '1983-05-10'::date, 'TAYL-ZAC-1983-05-10', 2008),
  ('TedfJe0', 'Jeff Tedford', '1961-11-02'::date, 'TEDF-JEFF-1961-11-02', 1989),
  ('ThomEm0', 'Emmitt Thomas', '1943-06-03'::date, 'THOM-EMMI-1943-06-03', 1979),
  ('ThurDe0', 'Dennis Thurman', '1956-04-13'::date, 'THUR-DENN-1956-04-13', 1988),
  ('TiceMi0', 'Mike Tice', '1959-02-02'::date, 'TICE-MIKE-1959-02-02', 1996),
  ('TillRu0', 'Rusty Tillman', '1946-02-27'::date, 'TILL-RUST-1946-02-27', 1979),
  ('TobiVi0', 'Vince Tobin', '1943-09-29'::date, 'TOBI-VINC-1943-09-29', 1965),
  ('TollTe0', 'Ted Tollner', '1940-05-29'::date, 'TOLL-TED-1940-05-29', 1981),
  ('TomlMi0', 'Mike Tomlin', '1972-03-15'::date, 'TOML-MIKE-1972-03-15', 1995),
  ('TomsJi0', 'Jim Tomsula', '1968-04-14'::date, 'TOMS-JIM-1968-04-14', 1989),
  ('TresMa0', 'Marc Trestman', '1956-01-15'::date, 'TRES-MARC-1956-01-15', 1981),
  ('TrgoMi0', 'Mike Trgovac', '1959-02-27'::date, 'TRGO-MIKE-1959-02-27', 1984),
  ('TuckMe0', 'Mel Tucker', '1972-01-04'::date, 'TUCK-MEL-1972-01-04', 1997),
  ('TurnNo0', 'Norv Turner', '1952-05-17'::date, 'TURN-NORV-1952-05-17', 1975),
  ('TurnRo0', 'Ron Turner', '1953-12-05'::date, 'TURN-RON-1953-12-05', 1978),
  ('TurnSc0', 'Scott Turner', '1982-08-07'::date, 'TURN-SCOT-1982-08-07', 2005),
  ('UdinGr0', 'Grant Udinski', '1900-01-01'::date, 'UDIN-GRAN-0000-00-00', 2019),
  ('UlbrJe0', 'Jeff Ulbrich', '1977-02-17'::date, 'ULBR-JEFF-1977-02-17', 2010),
  ('UndlCo0', 'Cory Undlin', '1971-06-29'::date, 'UNDL-CORY-1971-06-29', 1998),
  ('VanGBr0', 'Brian VanGorder', '1959-04-17'::date, 'VANG-BRIA-1959-04-17', 1995),
  ('VanPAl0', 'Alex Van Pelt', '1970-05-01'::date, 'PELT-ALEX-1970-05-01', 2005),
  ('VechJi0', 'Jim Vechiarella', '1937-02-20'::date, 'VECH-JIM-1937-02-20', 1978),
  ('VentRi0', 'Rick Venturi', '1946-02-23'::date, 'VENT-RICK-1946-02-23', 1973),
  ('VermDi0', 'Dick Vermeil', '1936-10-30'::date, 'VERM-DICK-1936-10-30', 1969),
  ('VittJo0', 'Joe Vitt', '1954-08-23'::date, 'VITT-JOE-1954-08-23', 1979),
  ('VrabMi0', 'Mike Vrabel', '1975-08-14'::date, 'VRAB-MIKE-1975-08-14', 2011),
  ('WaldSh0', 'Shane Waldron', '1979-08-17'::date, 'WALD-SHAN-1979-08-17', 2005),
  ('WalsTo0', 'Tom Walsh', '1949-04-16'::date, 'WALS-TOM-1949-04-16', 1979),
  ('WaltTi0', 'Tim Walton', '1971-03-11'::date, 'WALT-TIM-1971-03-11', 1995),
  ('WannDa0', 'Dave Wannstedt', '1952-05-21'::date, 'WANN-DAVE-1952-05-21', 1975),
  ('WashEr0', 'Eric Washington', '1969-10-29'::date, 'WASH-ERIC-1969-10-29', 1997),
  ('WashTo0', 'Todd Wash', '1968-07-19'::date, 'WASH-TODD-1968-07-19', 1996),
  ('WeavAn0', 'Anthony Weaver', '1980-08-28'::date, 'WEAV-ANTH-1980-08-28', 2010),
  ('WeisCh0', 'Charlie Weis', '1956-03-30'::date, 'WEIS-CHAR-1956-03-30', 1980),
  ('WhisKe0', 'Ken Whisenhunt', '1962-02-28'::date, 'WHIS-KEN-1962-02-28', 1995),
  ('WhitJo0', 'Joe Whitt Jr.', '1978-07-19'::date, 'WHIT-JOE-1978-07-19', 2000),
  ('WhitMi0', 'Mike White', '1936-01-04'::date, 'WHIT-MIKE-1936-01-04', 1958),
  ('WilkSt0', 'Steve Wilks', '1969-08-08'::date, 'WILK-STEV-1969-08-08', 1995),
  ('WillAl0', 'Alan Williams', '1969-11-04'::date, 'WILL-ALAN-1969-11-04', 1992),
  ('WillGr0', 'Gregg Williams', '1958-07-15'::date, 'WILL-GREG-1958-07-15', 1984),
  ('WillRi0', 'Richard Williamson', '1941-04-13'::date, 'WILL-RICH-1941-04-13', 1963),
  ('WillTe0', 'Terrell Williams', '1974-06-19'::date, 'WILL-TERR-1974-06-19', 1998),
  ('WilsDe0', 'Dennard Wilson', '1982-03-21'::date, 'WILS-DENN-1982-03-21', 2004),
  ('WoodAl0', 'Alex Wood', '1955-03-14'::date, 'WOOD-ALEX-1955-03-14', 1989),
  ('WoodJo0', 'Joe Woods', '1970-06-25'::date, 'WOOD-JOE-1970-06-25', 1992),
  ('WychSa0', 'Sam Wyche', '1945-01-05'::date, 'WYCH-SAM-1945-01-05', 1979),
  ('YaraZa0', 'Zaven Yaralian', '1952-02-05'::date, 'YARA-ZAVE-1952-02-05', 1975),
  ('ZampEr0', 'Ernie Zampese', '1936-03-12'::date, 'ZAMP-ERNI-1936-03-12', 1962),
  ('ZampKe0', 'Ken Zampese', '1967-07-19'::date, 'ZAMP-KEN-1967-07-19', 1990),
  ('ZimmAd0', 'Adam Zimmer', '1984-01-13'::date, 'ZIMM-ADAM-1984-01-13', 2006),
  ('ZimmMi0', 'Mike Zimmer', '1956-06-05'::date, 'ZIMM-MIKE-1956-06-05', 1979),
  ('ZookRo0', 'Ron Zook', '1954-04-28'::date, 'ZOOK-RON-1954-04-28', 1978),
  ('ZornJi0', 'Jim Zorn', '1953-05-10'::date, 'ZORN-JIM-1953-05-10', 1988);
-- END GENERATED FIXTURE VALUES

-- 3. Apply PFR-canonical full_name (PFR wins on mismatch; log drift), dob,
--    and pre-derived coach_id. Coaches in nfl_coaches that the fixture
--    lacks (should be zero after the Phase 0 coverage check) are left
--    with their existing full_name, NULL dob, NULL coach_id, surfacing as
--    a post-condition failure below.
DO $$
DECLARE
  drift_count int;
BEGIN
  SELECT COUNT(*) INTO drift_count
  FROM nfl_coaches c
  JOIN pfr_coach_fixture f ON f.pfr_coach_id = c.pfr_coach_id
  WHERE c.full_name IS DISTINCT FROM f.full_name;
  IF drift_count > 0 THEN
    RAISE NOTICE 'PFR full_name drift: % rows will be overwritten (PFR wins)', drift_count;
  END IF;
END $$;

UPDATE nfl_coaches c
SET full_name = f.full_name,
    dob = f.dob,
    coach_id = f.coach_id
FROM pfr_coach_fixture f
WHERE f.pfr_coach_id = c.pfr_coach_id;

-- 4a. Drop the dim row(s) flagged for removal by the null-DOB disposition.
--     PiolSc0 (Scott Pioli) has no bridge references and no YCH presence;
--     keeping him would block post-condition (a) below (coach_id NOT NULL).
DELETE FROM nfl_coaches WHERE pfr_coach_id IN ('PiolSc0');

-- 4b. Demote pfr_coach_id from PK to nullable UNIQUE alternate key so the
--     interim-coordinator seed rows below (NULL pfr_coach_id) can be inserted.
--     PostgreSQL FK constraints reference a specific unique index/PK by name,
--     not just "any unique on this column," so we must drop and re-add the
--     bridge FKs to retarget them at the new UNIQUE constraint. The drop+
--     re-add happens in the same transaction so referential integrity is
--     never observable as broken.
--     Phase 2 will swap the PK to coach_id; in the inter-phase window
--     nfl_coaches has UNIQUE on both pfr_coach_id and coach_id and no PK.
--     The basename CHECK constraint admits NULL implicitly (UNKNOWN regex
--     result does not fail a CHECK), so no relaxation needed.
ALTER TABLE nfl_game_coaches
  DROP CONSTRAINT nfl_game_coaches_head_coach_pfr_id_fkey,
  DROP CONSTRAINT nfl_game_coaches_off_play_caller_pfr_id_fkey,
  DROP CONSTRAINT nfl_game_coaches_def_play_caller_pfr_id_fkey;
ALTER TABLE nfl_coaches DROP CONSTRAINT IF EXISTS nfl_coaches_pkey;
ALTER TABLE nfl_coaches ALTER COLUMN pfr_coach_id DROP NOT NULL;
ALTER TABLE nfl_coaches
  ADD CONSTRAINT nfl_coaches_pfr_coach_id_unique UNIQUE (pfr_coach_id);
ALTER TABLE nfl_game_coaches
  ADD CONSTRAINT nfl_game_coaches_head_coach_pfr_id_fkey
    FOREIGN KEY (head_coach_pfr_id) REFERENCES nfl_coaches(pfr_coach_id),
  ADD CONSTRAINT nfl_game_coaches_off_play_caller_pfr_id_fkey
    FOREIGN KEY (off_play_caller_pfr_id) REFERENCES nfl_coaches(pfr_coach_id),
  ADD CONSTRAINT nfl_game_coaches_def_play_caller_pfr_id_fkey
    FOREIGN KEY (def_play_caller_pfr_id) REFERENCES nfl_coaches(pfr_coach_id);

-- 5. Insert 7 interim-coordinator seed rows (NULL pfr_coach_id; explicit
--    coach_id matching scripts/import-nfl-coaches.mjs INTERIM_COORDINATOR_SEEDS).
--    Sean Ryan was dropped from the seed list: bridge data shows Cory Undlin
--    (UndlCo0, real PFR pid) as DET 2020 DC weeks 1-15 and 17, with week 16
--    NULL as a PFR data gap, not a real interim role. The week-16 cell is
--    backfilled to Undlin in section 9 below.
INSERT INTO nfl_coaches (pfr_coach_id, full_name, dob, coach_id, updated_at)
VALUES
  (NULL, 'Blake Williams',   '1984-12-30', 'WILL-BLAK-1984-12-30', now()),
  (NULL, 'Mike Johnson',     '1967-05-02', 'JOHN-MIKE-1967-05-02', now()),
  (NULL, 'Parks Frazier',    '1991-11-20', 'FRAZ-PARK-1991-11-20', now()),
  (NULL, 'Mike Murphy',      '1944-09-25', 'MURP-MIKE-1944-09-25', now()),
  (NULL, 'Scott Milanovich', '1973-01-25', 'MILA-SCOT-1973-01-25', now()),
  (NULL, 'Spencer Whipple',  '1989-03-18', 'WHIP-SPEN-1989-03-18', now()),
  -- Evan Rothstein DOB unknown publicly; sentinel '0000-00-00' (PostgreSQL
  -- requires a valid date, so we use 1900-01-01 as the sentinel storage
  -- value and the coach_id carries the textual '0000-00-00' marker).
  (NULL, 'Evan Rothstein',   '1900-01-01', 'ROTH-EVAN-0000-00-00', now())
ON CONFLICT DO NOTHING;

-- 6. Constraints on coach_id (UNIQUE; format CHECK with optional discriminator).
ALTER TABLE nfl_coaches
  ADD CONSTRAINT nfl_coaches_coach_id_unique UNIQUE (coach_id);

ALTER TABLE nfl_coaches
  ADD CONSTRAINT nfl_coaches_coach_id_format
  CHECK (coach_id ~ '^[A-Z]{1,4}-[A-Z]{1,4}-[0-9]{4}-[0-9]{2}-[0-9]{2}(-[0-9]{2})?$');

-- 7. Additive *_coach_id columns on the bridge.
ALTER TABLE nfl_game_coaches
  ADD COLUMN IF NOT EXISTS head_coach_id varchar(32),
  ADD COLUMN IF NOT EXISTS off_play_caller_id varchar(32),
  ADD COLUMN IF NOT EXISTS def_play_caller_id varchar(32);

-- 8. JOIN-populate bridge *_coach_id from existing *_pfr_id via nfl_coaches.
UPDATE nfl_game_coaches b
SET head_coach_id = c.coach_id
FROM nfl_coaches c
WHERE c.pfr_coach_id = b.head_coach_pfr_id
  AND b.head_coach_id IS NULL
  AND b.head_coach_pfr_id IS NOT NULL;

UPDATE nfl_game_coaches b
SET off_play_caller_id = c.coach_id
FROM nfl_coaches c
WHERE c.pfr_coach_id = b.off_play_caller_pfr_id
  AND b.off_play_caller_id IS NULL
  AND b.off_play_caller_pfr_id IS NOT NULL;

UPDATE nfl_game_coaches b
SET def_play_caller_id = c.coach_id
FROM nfl_coaches c
WHERE c.pfr_coach_id = b.def_play_caller_pfr_id
  AND b.def_play_caller_id IS NULL
  AND b.def_play_caller_pfr_id IS NOT NULL;

-- 9. Backfill the 47 NULL bridge cells via (team, year, role) targeted UPDATEs.
--    Distribution validated 2026-05-31: 9 + 6 + 16 + 5 + 1 + 1 + 1 + 8 = 47.
--    Each UPDATE is scoped by NULL guard so re-running is safe.

-- SF 2010 OC: Mike Johnson (9 cells)
UPDATE nfl_game_coaches b
SET off_play_caller_id = 'JOHN-MIKE-1967-05-02'
FROM nfl_games g
WHERE g.nflverse_game_id = b.nflverse_game_id
  AND g.year = 2010 AND b.team = 'SF'
  AND b.off_play_caller_id IS NULL
  AND b.off_play_caller_pfr_id IS NULL;

-- IND 2011 DC: Mike Murphy (6 cells)
UPDATE nfl_game_coaches b
SET def_play_caller_id = 'MURP-MIKE-1944-09-25'
FROM nfl_games g
WHERE g.nflverse_game_id = b.nflverse_game_id
  AND g.year = 2011 AND b.team = 'IND'
  AND b.def_play_caller_id IS NULL
  AND b.def_play_caller_pfr_id IS NULL;

-- LA 2012 DC: Blake Williams (16 cells)
UPDATE nfl_game_coaches b
SET def_play_caller_id = 'WILL-BLAK-1984-12-30'
FROM nfl_games g
WHERE g.nflverse_game_id = b.nflverse_game_id
  AND g.year = 2012 AND b.team = 'LA'
  AND b.def_play_caller_id IS NULL
  AND b.def_play_caller_pfr_id IS NULL;

-- JAX 2018 OC: Scott Milanovich (5 cells)
UPDATE nfl_game_coaches b
SET off_play_caller_id = 'MILA-SCOT-1973-01-25'
FROM nfl_games g
WHERE g.nflverse_game_id = b.nflverse_game_id
  AND g.year = 2018 AND b.team = 'JAX'
  AND b.off_play_caller_id IS NULL
  AND b.off_play_caller_pfr_id IS NULL;

-- DET 2020 DC: Cory Undlin (1 cell, week 16). Undlin was DET's DC the entire
-- 2020 season per bridge data (weeks 1-15 and 17 both attribute UndlCo0).
-- Week 16 NULL is a PFR data gap, not a real role change, so we fill with
-- Undlin's coach_id rather than fabricating an interim seed.
UPDATE nfl_game_coaches b
SET def_play_caller_id = 'UNDL-CORY-1971-06-29'
FROM nfl_games g
WHERE g.nflverse_game_id = b.nflverse_game_id
  AND g.year = 2020 AND b.team = 'DET'
  AND b.def_play_caller_id IS NULL
  AND b.def_play_caller_pfr_id IS NULL;

-- DET 2020 OC: Evan Rothstein (1 cell)
UPDATE nfl_game_coaches b
SET off_play_caller_id = 'ROTH-EVAN-0000-00-00'
FROM nfl_games g
WHERE g.nflverse_game_id = b.nflverse_game_id
  AND g.year = 2020 AND b.team = 'DET'
  AND b.off_play_caller_id IS NULL
  AND b.off_play_caller_pfr_id IS NULL;

-- ARI 2021 OC: Spencer Whipple (1 cell)
UPDATE nfl_game_coaches b
SET off_play_caller_id = 'WHIP-SPEN-1989-03-18'
FROM nfl_games g
WHERE g.nflverse_game_id = b.nflverse_game_id
  AND g.year = 2021 AND b.team = 'ARI'
  AND b.off_play_caller_id IS NULL
  AND b.off_play_caller_pfr_id IS NULL;

-- IND 2022 OC: Parks Frazier (8 cells)
UPDATE nfl_game_coaches b
SET off_play_caller_id = 'FRAZ-PARK-1991-11-20'
FROM nfl_games g
WHERE g.nflverse_game_id = b.nflverse_game_id
  AND g.year = 2022 AND b.team = 'IND'
  AND b.off_play_caller_id IS NULL
  AND b.off_play_caller_pfr_id IS NULL;

-- 10. Post-condition checks (abort transaction on any failure).

-- (a) All dim rows have non-NULL coach_id.
DO $$
DECLARE
  null_count int;
BEGIN
  SELECT COUNT(*) INTO null_count FROM nfl_coaches WHERE coach_id IS NULL;
  IF null_count > 0 THEN
    RAISE EXCEPTION 'post-condition (a) FAILED: % nfl_coaches rows have NULL coach_id', null_count;
  END IF;
  RAISE NOTICE 'post-condition (a) OK: all nfl_coaches rows have coach_id';
END $$;

-- (b) All dim coach_ids pass the format CHECK regex (constraint catches new
--     inserts; this asserts the regex matched the entire backfilled set too).
DO $$
DECLARE
  bad_count int;
BEGIN
  SELECT COUNT(*) INTO bad_count FROM nfl_coaches
   WHERE coach_id !~ '^[A-Z]{1,4}-[A-Z]{1,4}-[0-9]{4}-[0-9]{2}-[0-9]{2}(-[0-9]{2})?$';
  IF bad_count > 0 THEN
    RAISE EXCEPTION 'post-condition (b) FAILED: % nfl_coaches rows fail coach_id format', bad_count;
  END IF;
  RAISE NOTICE 'post-condition (b) OK: all coach_ids match format';
END $$;

-- (c) Zero bridge rows have any *_pfr_id IS NOT NULL paired with the
--     corresponding *_coach_id IS NULL (catches a missing dim entry from a
--     failed PFR scrape).
DO $$
DECLARE
  bad_count int;
BEGIN
  SELECT COUNT(*) INTO bad_count FROM nfl_game_coaches
   WHERE (head_coach_pfr_id      IS NOT NULL AND head_coach_id      IS NULL)
      OR (off_play_caller_pfr_id IS NOT NULL AND off_play_caller_id IS NULL)
      OR (def_play_caller_pfr_id IS NOT NULL AND def_play_caller_id IS NULL);
  IF bad_count > 0 THEN
    RAISE EXCEPTION 'post-condition (c) FAILED: % bridge rows have *_pfr_id without *_coach_id', bad_count;
  END IF;
  RAISE NOTICE 'post-condition (c) OK: all bridge *_pfr_id rows resolved to *_coach_id';
END $$;

-- (d) Exactly 47 backfill cells touched (the closed interim-coordinator
--     cells where *_pfr_id was NULL but *_coach_id is now populated).
DO $$
DECLARE
  filled_count int;
BEGIN
  SELECT
    SUM(CASE WHEN off_play_caller_pfr_id IS NULL AND off_play_caller_id IS NOT NULL THEN 1 ELSE 0 END)
    + SUM(CASE WHEN def_play_caller_pfr_id IS NULL AND def_play_caller_id IS NOT NULL THEN 1 ELSE 0 END)
    + SUM(CASE WHEN head_coach_pfr_id     IS NULL AND head_coach_id      IS NOT NULL THEN 1 ELSE 0 END)
  INTO filled_count
  FROM nfl_game_coaches;
  IF filled_count <> 47 THEN
    RAISE EXCEPTION 'post-condition (d) FAILED: backfill closed % cells, expected 47', filled_count;
  END IF;
  RAISE NOTICE 'post-condition (d) OK: backfill closed exactly 47 cells';
END $$;

COMMIT;
