-- STATUS: PENDING
--
-- Retype the two play-table row mtimes to timestamptz. Takes the conformance
-- audit 3 -> 1, leaving only league_formats.cap, which belongs to
-- user:task/league/separate-auction-economy-from-format-identity.md.
--
-- NOT APPLIED, and sequenced AFTER
-- 2026-08-08-retype-lifecycle-stamps-to-timestamptz.sql.
--
-- WHY THIS IS ITS OWN APPLY, and it is not the reason the task predicted. The
-- task expected to split the play tables off because they carry "a far larger
-- consumer population". They carry NONE: running
-- db/gates/check-retyped-column-arithmetic.mjs against a candidate schema with
-- all fifteen retypes produces 13 findings and not one of them is on
-- nfl_plays.updated or nfl_plays_current_week.updated. Every consumer finding is
-- on the transaction lifecycle stamps in the companion file.
--
-- The real reason is LOCK DURATION. nfl_plays is 1,483,118 rows across 27
-- partitions at 8,489 MB, and ALTER COLUMN TYPE rewrites the whole table under
-- ACCESS EXCLUSIVE -- so this blocks every read of the schema's most heavily
-- consumed table for the duration, including /api/plays and every data view that
-- touches plays. The companion file's five tables total 11,855 rows and are
-- effectively instant. Fusing them would have put a multi-minute exclusive lock
-- inside a window that otherwise has none.
--
-- nfl_plays_current_week is only 5,969 rows / 8,848 kB and would be instant on
-- its own, but it stays with nfl_plays rather than joining the companion file:
-- both are written by the same statement region of
-- scripts/import-plays-nfl-v1.mjs, so splitting them means editing and
-- re-reviewing that file twice. Same fusion argument the nfl-games cluster used.
--
-- THE WRITERS ARE THE WHOLE CONSUMER RISK HERE, and they are invisible to the
-- gate because an INSERT PAYLOAD is neither a predicate nor a read:
--
--   private/libs-server/ngs.mjs:217,251        const timestamp = Math.round(Date.now() / 1000)
--                                              ... updated: timestamp
--   scripts/import-plays-nfl-v1.mjs:374,403    const timestamp = Math.round(new Date() / 1000)
--                                              ... updated: timestamp
--
-- Both must move to a Date in the same commit as this apply. The failure is LOUD
-- rather than silent, verified empirically on a scratch database rather than
-- reasoned about: `INSERT INTO t (updated) VALUES (1786220000)` against a
-- timestamptz column raises `column "updated" is of type timestamp with time
-- zone but expression is of type integer`. So an unfixed writer does not corrupt
-- data, it stops the plays import outright.
--
-- Deploy urgency is therefore high for worker-1 specifically, but the window is
-- bounded by the offseason: no game is in progress in August, and
-- import-plays-nfl-v1.mjs is invoked by the live plays worker only while games
-- are live. Confirm that before applying rather than inheriting it from here.
--
-- This column is NOT SPA-visible -- unlike the lifecycle stamps, nothing in
-- app/ reads either row mtime.
--
-- DDL rehearsed on a scratch database loaded from the committed schema: applies
-- at exit 0 in one transaction, and the rename cascades to all 27 nfl_plays
-- partitions.
--
-- No BEGIN/COMMIT here -- db-exec.sh runs this under --single-transaction.

ALTER TABLE public.nfl_plays ALTER COLUMN updated TYPE timestamptz USING to_timestamp(updated);
ALTER TABLE public.nfl_plays_current_week ALTER COLUMN updated TYPE timestamptz USING to_timestamp(updated);
