-- STATUS: PENDING
--
-- Drop the 23-column config tuple constraint, now that config_digest is the
-- dedup oracle.
--
-- DO NOT APPLY THIS UNTIL THE DEPLOY LANDS. It is the second half of
-- 2026-08-04-kicking-dst-scoring-config.sql, split off for one reason: deployed
-- production code spells its upsert `ON CONFLICT (<the 23 columns>)`, and that
-- form requires a unique index on exactly those columns. Dropping the
-- constraint while that code is running fails every
-- find_or_create_scoring_format call -- including live external-league import --
-- with "no unique or exclusion constraint matching the ON CONFLICT
-- specification". The deploy is human-gated, so that window is hours, not
-- seconds.
--
-- The precondition is therefore not "the code is committed" but "the code is
-- RUNNING". Check it the way CLAUDE.md prescribes, against the host rather than
-- against origin:
--
--   ssh league 'cd /root/league && git rev-parse --short HEAD'
--
-- and confirm that commit carries `ON CONFLICT (config_digest)` in
-- libs-server/find-or-create-format.mjs before running this file.
--
-- Apply this IMMEDIATELY after the deploy verifies -- minutes, not hours. It is
-- not cleanup. The retained constraint is strictly stricter than the digest, so
-- from the moment the new code is live it rejects legitimately distinct configs
-- that differ only in the new kicking and DST columns. Reproduced on a scratch
-- database: an insert differing from an existing row only in
-- `defensive_touchdowns` raises a duplicate-key violation here that
-- ON CONFLICT (config_digest) does not catch, so a commissioner editing a DST
-- value in league settings gets a 500 until this file runs.
--
-- The transaction is required. No non-blocking index build is involved.

ALTER TABLE public.league_scoring_formats
  DROP CONSTRAINT league_scoring_formats_config_unique;
