-- STATUS: APPLIED 2026-08-15 against league_production
--
-- Backfill pff_player_gamelogs from the payloads already landed in
-- pff_player_facet_gamelogs.facet_payload.
--
-- The importer (private/scripts/import-pff-archive-player-gamelogs.mjs) reads
-- the archive files on the ingest host. Those payloads are already in this
-- database verbatim -- the facet importer writes `facet_payload: row` -- so the
-- initial population needs no archive access and no re-crawl. This file's
-- SELECT list was GENERATED from that importer's exported SHARED_FIELD_TO_COLUMN
-- and FACET_FIELD_TO_COLUMN, so the two cannot disagree about which payload
-- field fills which column.
--
-- One statement per facet, in the same order the importer walks them. A
-- player-game is assembled from up to six facets, so each statement after the
-- first updates rows the earlier ones created; every column is written
-- COALESCE(EXCLUDED.x, existing.x) so no facet can null out a sibling's value.
--
-- The numeric guard on each extraction is deliberate: a payload field may be
-- JSON null, and a bare cast of a non-numeric string would abort the whole
-- transaction rather than leaving one column NULL.
--
-- statement_timeout is lifted because the server's 40s default cancels these
-- mid-scan; lock_timeout is bounded rather than unlimited so a queued ACCESS
-- EXCLUSIVE cannot park every reader behind it.
--
-- See user:task/league/repoint-analytics-at-pff-facet-tables.md.

SET lock_timeout = '30s';
SET statement_timeout = 0;

-- offense/summary
INSERT INTO public.pff_player_gamelogs (pid, esbid, season_year, pff_game_id, pff_player_id, pff_team_id, nfl_team, player_position, grade_offense, grade_offense_penalty, grade_defense, grade_defense_penalty, grade_pass, grade_run, grade_pass_block, grade_run_block, grade_pass_route, grade_hands_drop, grade_hands_fumble, grade_coverage_defense, grade_pass_rush_defense, grade_run_defense, grade_tackle, grade_punter, penalties, declined_penalties, routes, yards_per_route_run, scrambles, snaps_offense_total, snaps_offense_pass, snaps_offense_run, snaps_offense_total_pass, snaps_offense_total_run, snaps_pass_block, snaps_run_block, snaps_pass_route)
SELECT g.pid, g.esbid, ng.season_year, g.pff_game_id, g.pff_player_id, g.pff_team_id, g.nfl_team, g.player_position,
  CASE WHEN g.facet_payload->>'grades_offense' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_offense')::numeric END::numeric(4,1) AS grade_offense,
  CASE WHEN g.facet_payload->>'grades_offense_penalty' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_offense_penalty')::numeric END::numeric(4,1) AS grade_offense_penalty,
  CASE WHEN g.facet_payload->>'grades_defense' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_defense')::numeric END::numeric(4,1) AS grade_defense,
  CASE WHEN g.facet_payload->>'grades_defense_penalty' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_defense_penalty')::numeric END::numeric(4,1) AS grade_defense_penalty,
  CASE WHEN g.facet_payload->>'grades_pass' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_pass')::numeric END::numeric(4,1) AS grade_pass,
  CASE WHEN g.facet_payload->>'grades_run' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_run')::numeric END::numeric(4,1) AS grade_run,
  CASE WHEN g.facet_payload->>'grades_pass_block' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_pass_block')::numeric END::numeric(4,1) AS grade_pass_block,
  CASE WHEN g.facet_payload->>'grades_run_block' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_run_block')::numeric END::numeric(4,1) AS grade_run_block,
  CASE WHEN g.facet_payload->>'grades_pass_route' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_pass_route')::numeric END::numeric(4,1) AS grade_pass_route,
  CASE WHEN g.facet_payload->>'grades_hands_drop' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_hands_drop')::numeric END::numeric(4,1) AS grade_hands_drop,
  CASE WHEN g.facet_payload->>'grades_hands_fumble' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_hands_fumble')::numeric END::numeric(4,1) AS grade_hands_fumble,
  CASE WHEN g.facet_payload->>'grades_coverage_defense' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_coverage_defense')::numeric END::numeric(4,1) AS grade_coverage_defense,
  CASE WHEN g.facet_payload->>'grades_pass_rush_defense' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_pass_rush_defense')::numeric END::numeric(4,1) AS grade_pass_rush_defense,
  CASE WHEN g.facet_payload->>'grades_run_defense' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_run_defense')::numeric END::numeric(4,1) AS grade_run_defense,
  CASE WHEN g.facet_payload->>'grades_tackle' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_tackle')::numeric END::numeric(4,1) AS grade_tackle,
  CASE WHEN g.facet_payload->>'grades_punter' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_punter')::numeric END::numeric(4,1) AS grade_punter,
  CASE WHEN g.facet_payload->>'penalties' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'penalties')::numeric END::smallint AS penalties,
  CASE WHEN g.facet_payload->>'declined_penalties' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'declined_penalties')::numeric END::smallint AS declined_penalties,
  CASE WHEN g.facet_payload->>'routes' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'routes')::numeric END::smallint AS routes,
  CASE WHEN g.facet_payload->>'yprr' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'yprr')::numeric END::numeric(5,2) AS yards_per_route_run,
  CASE WHEN g.facet_payload->>'scrambles' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'scrambles')::numeric END::smallint AS scrambles,
  CASE WHEN g.facet_payload->>'snap_counts_total' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'snap_counts_total')::numeric END::smallint AS snaps_offense_total,
  CASE WHEN g.facet_payload->>'snap_counts_pass' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'snap_counts_pass')::numeric END::smallint AS snaps_offense_pass,
  CASE WHEN g.facet_payload->>'snap_counts_run' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'snap_counts_run')::numeric END::smallint AS snaps_offense_run,
  CASE WHEN g.facet_payload->>'snap_counts_total_pass' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'snap_counts_total_pass')::numeric END::smallint AS snaps_offense_total_pass,
  CASE WHEN g.facet_payload->>'snap_counts_total_run' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'snap_counts_total_run')::numeric END::smallint AS snaps_offense_total_run,
  CASE WHEN g.facet_payload->>'snap_counts_pass_block' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'snap_counts_pass_block')::numeric END::smallint AS snaps_pass_block,
  CASE WHEN g.facet_payload->>'snap_counts_run_block' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'snap_counts_run_block')::numeric END::smallint AS snaps_run_block,
  CASE WHEN g.facet_payload->>'snap_counts_pass_route' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'snap_counts_pass_route')::numeric END::smallint AS snaps_pass_route
FROM public.pff_player_facet_gamelogs g
JOIN public.nfl_games ng ON ng.esbid::text = g.esbid::text
WHERE g.facet = 'offense/summary'
ON CONFLICT (pid, esbid) DO UPDATE SET
  grade_offense = COALESCE(EXCLUDED.grade_offense, pff_player_gamelogs.grade_offense),
  grade_offense_penalty = COALESCE(EXCLUDED.grade_offense_penalty, pff_player_gamelogs.grade_offense_penalty),
  grade_defense = COALESCE(EXCLUDED.grade_defense, pff_player_gamelogs.grade_defense),
  grade_defense_penalty = COALESCE(EXCLUDED.grade_defense_penalty, pff_player_gamelogs.grade_defense_penalty),
  grade_pass = COALESCE(EXCLUDED.grade_pass, pff_player_gamelogs.grade_pass),
  grade_run = COALESCE(EXCLUDED.grade_run, pff_player_gamelogs.grade_run),
  grade_pass_block = COALESCE(EXCLUDED.grade_pass_block, pff_player_gamelogs.grade_pass_block),
  grade_run_block = COALESCE(EXCLUDED.grade_run_block, pff_player_gamelogs.grade_run_block),
  grade_pass_route = COALESCE(EXCLUDED.grade_pass_route, pff_player_gamelogs.grade_pass_route),
  grade_hands_drop = COALESCE(EXCLUDED.grade_hands_drop, pff_player_gamelogs.grade_hands_drop),
  grade_hands_fumble = COALESCE(EXCLUDED.grade_hands_fumble, pff_player_gamelogs.grade_hands_fumble),
  grade_coverage_defense = COALESCE(EXCLUDED.grade_coverage_defense, pff_player_gamelogs.grade_coverage_defense),
  grade_pass_rush_defense = COALESCE(EXCLUDED.grade_pass_rush_defense, pff_player_gamelogs.grade_pass_rush_defense),
  grade_run_defense = COALESCE(EXCLUDED.grade_run_defense, pff_player_gamelogs.grade_run_defense),
  grade_tackle = COALESCE(EXCLUDED.grade_tackle, pff_player_gamelogs.grade_tackle),
  grade_punter = COALESCE(EXCLUDED.grade_punter, pff_player_gamelogs.grade_punter),
  penalties = COALESCE(EXCLUDED.penalties, pff_player_gamelogs.penalties),
  declined_penalties = COALESCE(EXCLUDED.declined_penalties, pff_player_gamelogs.declined_penalties),
  routes = COALESCE(EXCLUDED.routes, pff_player_gamelogs.routes),
  yards_per_route_run = COALESCE(EXCLUDED.yards_per_route_run, pff_player_gamelogs.yards_per_route_run),
  scrambles = COALESCE(EXCLUDED.scrambles, pff_player_gamelogs.scrambles),
  snaps_offense_total = COALESCE(EXCLUDED.snaps_offense_total, pff_player_gamelogs.snaps_offense_total),
  snaps_offense_pass = COALESCE(EXCLUDED.snaps_offense_pass, pff_player_gamelogs.snaps_offense_pass),
  snaps_offense_run = COALESCE(EXCLUDED.snaps_offense_run, pff_player_gamelogs.snaps_offense_run),
  snaps_offense_total_pass = COALESCE(EXCLUDED.snaps_offense_total_pass, pff_player_gamelogs.snaps_offense_total_pass),
  snaps_offense_total_run = COALESCE(EXCLUDED.snaps_offense_total_run, pff_player_gamelogs.snaps_offense_total_run),
  snaps_pass_block = COALESCE(EXCLUDED.snaps_pass_block, pff_player_gamelogs.snaps_pass_block),
  snaps_run_block = COALESCE(EXCLUDED.snaps_run_block, pff_player_gamelogs.snaps_run_block),
  snaps_pass_route = COALESCE(EXCLUDED.snaps_pass_route, pff_player_gamelogs.snaps_pass_route),
  nfl_team = COALESCE(pff_player_gamelogs.nfl_team, EXCLUDED.nfl_team),
  player_position = COALESCE(pff_player_gamelogs.player_position, EXCLUDED.player_position),
  updated_at = now();

-- passing/summary
INSERT INTO public.pff_player_gamelogs (pid, esbid, season_year, pff_game_id, pff_player_id, pff_team_id, nfl_team, player_position, grade_offense, grade_offense_penalty, grade_defense, grade_defense_penalty, grade_pass, grade_run, grade_pass_block, grade_run_block, grade_pass_route, grade_hands_drop, grade_hands_fumble, grade_coverage_defense, grade_pass_rush_defense, grade_run_defense, grade_tackle, grade_punter, penalties, declined_penalties, routes, yards_per_route_run, scrambles, passing_snaps, passing_dropbacks, passing_attempts, passing_completions, passing_yards, passing_touchdowns, passing_interceptions, passing_first_downs, passing_aimed_passes, passing_batted_passes, passing_big_time_throws, passing_big_time_throw_rate, passing_turnover_worthy_plays, passing_turnover_worthy_play_rate, passing_accuracy_percentage, passing_completion_percentage, passing_drops, passing_drop_rate, passing_hit_as_threw, passing_sacks, passing_sack_percentage, passing_spikes, passing_throwaways, passing_defense_generated_pressures, passing_pressure_to_sack_rate, passing_quarterback_rating, passing_average_depth_of_target, passing_average_time_to_throw, passing_yards_per_attempt)
SELECT g.pid, g.esbid, ng.season_year, g.pff_game_id, g.pff_player_id, g.pff_team_id, g.nfl_team, g.player_position,
  CASE WHEN g.facet_payload->>'grades_offense' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_offense')::numeric END::numeric(4,1) AS grade_offense,
  CASE WHEN g.facet_payload->>'grades_offense_penalty' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_offense_penalty')::numeric END::numeric(4,1) AS grade_offense_penalty,
  CASE WHEN g.facet_payload->>'grades_defense' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_defense')::numeric END::numeric(4,1) AS grade_defense,
  CASE WHEN g.facet_payload->>'grades_defense_penalty' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_defense_penalty')::numeric END::numeric(4,1) AS grade_defense_penalty,
  CASE WHEN g.facet_payload->>'grades_pass' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_pass')::numeric END::numeric(4,1) AS grade_pass,
  CASE WHEN g.facet_payload->>'grades_run' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_run')::numeric END::numeric(4,1) AS grade_run,
  CASE WHEN g.facet_payload->>'grades_pass_block' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_pass_block')::numeric END::numeric(4,1) AS grade_pass_block,
  CASE WHEN g.facet_payload->>'grades_run_block' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_run_block')::numeric END::numeric(4,1) AS grade_run_block,
  CASE WHEN g.facet_payload->>'grades_pass_route' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_pass_route')::numeric END::numeric(4,1) AS grade_pass_route,
  CASE WHEN g.facet_payload->>'grades_hands_drop' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_hands_drop')::numeric END::numeric(4,1) AS grade_hands_drop,
  CASE WHEN g.facet_payload->>'grades_hands_fumble' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_hands_fumble')::numeric END::numeric(4,1) AS grade_hands_fumble,
  CASE WHEN g.facet_payload->>'grades_coverage_defense' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_coverage_defense')::numeric END::numeric(4,1) AS grade_coverage_defense,
  CASE WHEN g.facet_payload->>'grades_pass_rush_defense' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_pass_rush_defense')::numeric END::numeric(4,1) AS grade_pass_rush_defense,
  CASE WHEN g.facet_payload->>'grades_run_defense' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_run_defense')::numeric END::numeric(4,1) AS grade_run_defense,
  CASE WHEN g.facet_payload->>'grades_tackle' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_tackle')::numeric END::numeric(4,1) AS grade_tackle,
  CASE WHEN g.facet_payload->>'grades_punter' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_punter')::numeric END::numeric(4,1) AS grade_punter,
  CASE WHEN g.facet_payload->>'penalties' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'penalties')::numeric END::smallint AS penalties,
  CASE WHEN g.facet_payload->>'declined_penalties' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'declined_penalties')::numeric END::smallint AS declined_penalties,
  CASE WHEN g.facet_payload->>'routes' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'routes')::numeric END::smallint AS routes,
  CASE WHEN g.facet_payload->>'yprr' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'yprr')::numeric END::numeric(5,2) AS yards_per_route_run,
  CASE WHEN g.facet_payload->>'scrambles' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'scrambles')::numeric END::smallint AS scrambles,
  CASE WHEN g.facet_payload->>'passing_snaps' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'passing_snaps')::numeric END::smallint AS passing_snaps,
  CASE WHEN g.facet_payload->>'dropbacks' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'dropbacks')::numeric END::smallint AS passing_dropbacks,
  CASE WHEN g.facet_payload->>'attempts' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'attempts')::numeric END::smallint AS passing_attempts,
  CASE WHEN g.facet_payload->>'completions' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'completions')::numeric END::smallint AS passing_completions,
  CASE WHEN g.facet_payload->>'yards' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'yards')::numeric END::smallint AS passing_yards,
  CASE WHEN g.facet_payload->>'touchdowns' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'touchdowns')::numeric END::smallint AS passing_touchdowns,
  CASE WHEN g.facet_payload->>'interceptions' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'interceptions')::numeric END::smallint AS passing_interceptions,
  CASE WHEN g.facet_payload->>'first_downs' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'first_downs')::numeric END::smallint AS passing_first_downs,
  CASE WHEN g.facet_payload->>'aimed_passes' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'aimed_passes')::numeric END::smallint AS passing_aimed_passes,
  CASE WHEN g.facet_payload->>'bats' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'bats')::numeric END::smallint AS passing_batted_passes,
  CASE WHEN g.facet_payload->>'big_time_throws' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'big_time_throws')::numeric END::smallint AS passing_big_time_throws,
  CASE WHEN g.facet_payload->>'btt_rate' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'btt_rate')::numeric END::numeric(4,1) AS passing_big_time_throw_rate,
  CASE WHEN g.facet_payload->>'turnover_worthy_plays' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'turnover_worthy_plays')::numeric END::smallint AS passing_turnover_worthy_plays,
  CASE WHEN g.facet_payload->>'twp_rate' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'twp_rate')::numeric END::numeric(4,1) AS passing_turnover_worthy_play_rate,
  CASE WHEN g.facet_payload->>'accuracy_percent' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'accuracy_percent')::numeric END::numeric(4,1) AS passing_accuracy_percentage,
  CASE WHEN g.facet_payload->>'completion_percent' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'completion_percent')::numeric END::numeric(4,1) AS passing_completion_percentage,
  CASE WHEN g.facet_payload->>'drops' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'drops')::numeric END::smallint AS passing_drops,
  CASE WHEN g.facet_payload->>'drop_rate' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'drop_rate')::numeric END::numeric(4,1) AS passing_drop_rate,
  CASE WHEN g.facet_payload->>'hit_as_threw' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'hit_as_threw')::numeric END::smallint AS passing_hit_as_threw,
  CASE WHEN g.facet_payload->>'sacks' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'sacks')::numeric END::smallint AS passing_sacks,
  CASE WHEN g.facet_payload->>'sack_percent' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'sack_percent')::numeric END::numeric(4,1) AS passing_sack_percentage,
  CASE WHEN g.facet_payload->>'spikes' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'spikes')::numeric END::smallint AS passing_spikes,
  CASE WHEN g.facet_payload->>'thrown_aways' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'thrown_aways')::numeric END::smallint AS passing_throwaways,
  CASE WHEN g.facet_payload->>'def_gen_pressures' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'def_gen_pressures')::numeric END::smallint AS passing_defense_generated_pressures,
  CASE WHEN g.facet_payload->>'pressure_to_sack_rate' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'pressure_to_sack_rate')::numeric END::numeric(4,1) AS passing_pressure_to_sack_rate,
  CASE WHEN g.facet_payload->>'qb_rating' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'qb_rating')::numeric END::numeric(4,1) AS passing_quarterback_rating,
  CASE WHEN g.facet_payload->>'avg_depth_of_target' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'avg_depth_of_target')::numeric END::numeric(4,1) AS passing_average_depth_of_target,
  CASE WHEN g.facet_payload->>'avg_time_to_throw' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'avg_time_to_throw')::numeric END::numeric(4,2) AS passing_average_time_to_throw,
  CASE WHEN g.facet_payload->>'ypa' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'ypa')::numeric END::numeric(4,1) AS passing_yards_per_attempt
FROM public.pff_player_facet_gamelogs g
JOIN public.nfl_games ng ON ng.esbid::text = g.esbid::text
WHERE g.facet = 'passing/summary'
ON CONFLICT (pid, esbid) DO UPDATE SET
  grade_offense = COALESCE(EXCLUDED.grade_offense, pff_player_gamelogs.grade_offense),
  grade_offense_penalty = COALESCE(EXCLUDED.grade_offense_penalty, pff_player_gamelogs.grade_offense_penalty),
  grade_defense = COALESCE(EXCLUDED.grade_defense, pff_player_gamelogs.grade_defense),
  grade_defense_penalty = COALESCE(EXCLUDED.grade_defense_penalty, pff_player_gamelogs.grade_defense_penalty),
  grade_pass = COALESCE(EXCLUDED.grade_pass, pff_player_gamelogs.grade_pass),
  grade_run = COALESCE(EXCLUDED.grade_run, pff_player_gamelogs.grade_run),
  grade_pass_block = COALESCE(EXCLUDED.grade_pass_block, pff_player_gamelogs.grade_pass_block),
  grade_run_block = COALESCE(EXCLUDED.grade_run_block, pff_player_gamelogs.grade_run_block),
  grade_pass_route = COALESCE(EXCLUDED.grade_pass_route, pff_player_gamelogs.grade_pass_route),
  grade_hands_drop = COALESCE(EXCLUDED.grade_hands_drop, pff_player_gamelogs.grade_hands_drop),
  grade_hands_fumble = COALESCE(EXCLUDED.grade_hands_fumble, pff_player_gamelogs.grade_hands_fumble),
  grade_coverage_defense = COALESCE(EXCLUDED.grade_coverage_defense, pff_player_gamelogs.grade_coverage_defense),
  grade_pass_rush_defense = COALESCE(EXCLUDED.grade_pass_rush_defense, pff_player_gamelogs.grade_pass_rush_defense),
  grade_run_defense = COALESCE(EXCLUDED.grade_run_defense, pff_player_gamelogs.grade_run_defense),
  grade_tackle = COALESCE(EXCLUDED.grade_tackle, pff_player_gamelogs.grade_tackle),
  grade_punter = COALESCE(EXCLUDED.grade_punter, pff_player_gamelogs.grade_punter),
  penalties = COALESCE(EXCLUDED.penalties, pff_player_gamelogs.penalties),
  declined_penalties = COALESCE(EXCLUDED.declined_penalties, pff_player_gamelogs.declined_penalties),
  routes = COALESCE(EXCLUDED.routes, pff_player_gamelogs.routes),
  yards_per_route_run = COALESCE(EXCLUDED.yards_per_route_run, pff_player_gamelogs.yards_per_route_run),
  scrambles = COALESCE(EXCLUDED.scrambles, pff_player_gamelogs.scrambles),
  passing_snaps = COALESCE(EXCLUDED.passing_snaps, pff_player_gamelogs.passing_snaps),
  passing_dropbacks = COALESCE(EXCLUDED.passing_dropbacks, pff_player_gamelogs.passing_dropbacks),
  passing_attempts = COALESCE(EXCLUDED.passing_attempts, pff_player_gamelogs.passing_attempts),
  passing_completions = COALESCE(EXCLUDED.passing_completions, pff_player_gamelogs.passing_completions),
  passing_yards = COALESCE(EXCLUDED.passing_yards, pff_player_gamelogs.passing_yards),
  passing_touchdowns = COALESCE(EXCLUDED.passing_touchdowns, pff_player_gamelogs.passing_touchdowns),
  passing_interceptions = COALESCE(EXCLUDED.passing_interceptions, pff_player_gamelogs.passing_interceptions),
  passing_first_downs = COALESCE(EXCLUDED.passing_first_downs, pff_player_gamelogs.passing_first_downs),
  passing_aimed_passes = COALESCE(EXCLUDED.passing_aimed_passes, pff_player_gamelogs.passing_aimed_passes),
  passing_batted_passes = COALESCE(EXCLUDED.passing_batted_passes, pff_player_gamelogs.passing_batted_passes),
  passing_big_time_throws = COALESCE(EXCLUDED.passing_big_time_throws, pff_player_gamelogs.passing_big_time_throws),
  passing_big_time_throw_rate = COALESCE(EXCLUDED.passing_big_time_throw_rate, pff_player_gamelogs.passing_big_time_throw_rate),
  passing_turnover_worthy_plays = COALESCE(EXCLUDED.passing_turnover_worthy_plays, pff_player_gamelogs.passing_turnover_worthy_plays),
  passing_turnover_worthy_play_rate = COALESCE(EXCLUDED.passing_turnover_worthy_play_rate, pff_player_gamelogs.passing_turnover_worthy_play_rate),
  passing_accuracy_percentage = COALESCE(EXCLUDED.passing_accuracy_percentage, pff_player_gamelogs.passing_accuracy_percentage),
  passing_completion_percentage = COALESCE(EXCLUDED.passing_completion_percentage, pff_player_gamelogs.passing_completion_percentage),
  passing_drops = COALESCE(EXCLUDED.passing_drops, pff_player_gamelogs.passing_drops),
  passing_drop_rate = COALESCE(EXCLUDED.passing_drop_rate, pff_player_gamelogs.passing_drop_rate),
  passing_hit_as_threw = COALESCE(EXCLUDED.passing_hit_as_threw, pff_player_gamelogs.passing_hit_as_threw),
  passing_sacks = COALESCE(EXCLUDED.passing_sacks, pff_player_gamelogs.passing_sacks),
  passing_sack_percentage = COALESCE(EXCLUDED.passing_sack_percentage, pff_player_gamelogs.passing_sack_percentage),
  passing_spikes = COALESCE(EXCLUDED.passing_spikes, pff_player_gamelogs.passing_spikes),
  passing_throwaways = COALESCE(EXCLUDED.passing_throwaways, pff_player_gamelogs.passing_throwaways),
  passing_defense_generated_pressures = COALESCE(EXCLUDED.passing_defense_generated_pressures, pff_player_gamelogs.passing_defense_generated_pressures),
  passing_pressure_to_sack_rate = COALESCE(EXCLUDED.passing_pressure_to_sack_rate, pff_player_gamelogs.passing_pressure_to_sack_rate),
  passing_quarterback_rating = COALESCE(EXCLUDED.passing_quarterback_rating, pff_player_gamelogs.passing_quarterback_rating),
  passing_average_depth_of_target = COALESCE(EXCLUDED.passing_average_depth_of_target, pff_player_gamelogs.passing_average_depth_of_target),
  passing_average_time_to_throw = COALESCE(EXCLUDED.passing_average_time_to_throw, pff_player_gamelogs.passing_average_time_to_throw),
  passing_yards_per_attempt = COALESCE(EXCLUDED.passing_yards_per_attempt, pff_player_gamelogs.passing_yards_per_attempt),
  nfl_team = COALESCE(pff_player_gamelogs.nfl_team, EXCLUDED.nfl_team),
  player_position = COALESCE(pff_player_gamelogs.player_position, EXCLUDED.player_position),
  updated_at = now();

-- receiving/summary
INSERT INTO public.pff_player_gamelogs (pid, esbid, season_year, pff_game_id, pff_player_id, pff_team_id, nfl_team, player_position, grade_offense, grade_offense_penalty, grade_defense, grade_defense_penalty, grade_pass, grade_run, grade_pass_block, grade_run_block, grade_pass_route, grade_hands_drop, grade_hands_fumble, grade_coverage_defense, grade_pass_rush_defense, grade_run_defense, grade_tackle, grade_punter, penalties, declined_penalties, routes, yards_per_route_run, scrambles, receiving_targets, receiving_receptions, receiving_yards, receiving_touchdowns, receiving_first_downs, receiving_longest, receiving_drops, receiving_drop_rate, receiving_fumbles, receiving_interceptions, receiving_caught_percentage, receiving_contested_targets, receiving_contested_receptions, receiving_contested_catch_rate, receiving_avoided_tackles, receiving_yards_after_catch, receiving_yards_after_catch_per_reception, receiving_yards_per_reception, receiving_average_depth_of_target, receiving_targeted_quarterback_rating, receiving_pass_plays, receiving_pass_blocks, receiving_pass_block_rate, receiving_route_rate, receiving_inline_snaps, receiving_inline_rate, receiving_slot_snaps, receiving_slot_rate, receiving_wide_snaps, receiving_wide_rate)
SELECT g.pid, g.esbid, ng.season_year, g.pff_game_id, g.pff_player_id, g.pff_team_id, g.nfl_team, g.player_position,
  CASE WHEN g.facet_payload->>'grades_offense' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_offense')::numeric END::numeric(4,1) AS grade_offense,
  CASE WHEN g.facet_payload->>'grades_offense_penalty' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_offense_penalty')::numeric END::numeric(4,1) AS grade_offense_penalty,
  CASE WHEN g.facet_payload->>'grades_defense' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_defense')::numeric END::numeric(4,1) AS grade_defense,
  CASE WHEN g.facet_payload->>'grades_defense_penalty' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_defense_penalty')::numeric END::numeric(4,1) AS grade_defense_penalty,
  CASE WHEN g.facet_payload->>'grades_pass' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_pass')::numeric END::numeric(4,1) AS grade_pass,
  CASE WHEN g.facet_payload->>'grades_run' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_run')::numeric END::numeric(4,1) AS grade_run,
  CASE WHEN g.facet_payload->>'grades_pass_block' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_pass_block')::numeric END::numeric(4,1) AS grade_pass_block,
  CASE WHEN g.facet_payload->>'grades_run_block' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_run_block')::numeric END::numeric(4,1) AS grade_run_block,
  CASE WHEN g.facet_payload->>'grades_pass_route' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_pass_route')::numeric END::numeric(4,1) AS grade_pass_route,
  CASE WHEN g.facet_payload->>'grades_hands_drop' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_hands_drop')::numeric END::numeric(4,1) AS grade_hands_drop,
  CASE WHEN g.facet_payload->>'grades_hands_fumble' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_hands_fumble')::numeric END::numeric(4,1) AS grade_hands_fumble,
  CASE WHEN g.facet_payload->>'grades_coverage_defense' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_coverage_defense')::numeric END::numeric(4,1) AS grade_coverage_defense,
  CASE WHEN g.facet_payload->>'grades_pass_rush_defense' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_pass_rush_defense')::numeric END::numeric(4,1) AS grade_pass_rush_defense,
  CASE WHEN g.facet_payload->>'grades_run_defense' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_run_defense')::numeric END::numeric(4,1) AS grade_run_defense,
  CASE WHEN g.facet_payload->>'grades_tackle' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_tackle')::numeric END::numeric(4,1) AS grade_tackle,
  CASE WHEN g.facet_payload->>'grades_punter' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_punter')::numeric END::numeric(4,1) AS grade_punter,
  CASE WHEN g.facet_payload->>'penalties' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'penalties')::numeric END::smallint AS penalties,
  CASE WHEN g.facet_payload->>'declined_penalties' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'declined_penalties')::numeric END::smallint AS declined_penalties,
  CASE WHEN g.facet_payload->>'routes' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'routes')::numeric END::smallint AS routes,
  CASE WHEN g.facet_payload->>'yprr' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'yprr')::numeric END::numeric(5,2) AS yards_per_route_run,
  CASE WHEN g.facet_payload->>'scrambles' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'scrambles')::numeric END::smallint AS scrambles,
  CASE WHEN g.facet_payload->>'targets' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'targets')::numeric END::smallint AS receiving_targets,
  CASE WHEN g.facet_payload->>'receptions' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'receptions')::numeric END::smallint AS receiving_receptions,
  CASE WHEN g.facet_payload->>'yards' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'yards')::numeric END::smallint AS receiving_yards,
  CASE WHEN g.facet_payload->>'touchdowns' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'touchdowns')::numeric END::smallint AS receiving_touchdowns,
  CASE WHEN g.facet_payload->>'first_downs' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'first_downs')::numeric END::smallint AS receiving_first_downs,
  CASE WHEN g.facet_payload->>'longest' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'longest')::numeric END::smallint AS receiving_longest,
  CASE WHEN g.facet_payload->>'drops' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'drops')::numeric END::smallint AS receiving_drops,
  CASE WHEN g.facet_payload->>'drop_rate' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'drop_rate')::numeric END::numeric(4,1) AS receiving_drop_rate,
  CASE WHEN g.facet_payload->>'fumbles' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'fumbles')::numeric END::smallint AS receiving_fumbles,
  CASE WHEN g.facet_payload->>'interceptions' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'interceptions')::numeric END::smallint AS receiving_interceptions,
  CASE WHEN g.facet_payload->>'caught_percent' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'caught_percent')::numeric END::numeric(4,1) AS receiving_caught_percentage,
  CASE WHEN g.facet_payload->>'contested_targets' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'contested_targets')::numeric END::smallint AS receiving_contested_targets,
  CASE WHEN g.facet_payload->>'contested_receptions' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'contested_receptions')::numeric END::smallint AS receiving_contested_receptions,
  CASE WHEN g.facet_payload->>'contested_catch_rate' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'contested_catch_rate')::numeric END::numeric(4,1) AS receiving_contested_catch_rate,
  CASE WHEN g.facet_payload->>'avoided_tackles' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'avoided_tackles')::numeric END::smallint AS receiving_avoided_tackles,
  CASE WHEN g.facet_payload->>'yards_after_catch' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'yards_after_catch')::numeric END::smallint AS receiving_yards_after_catch,
  CASE WHEN g.facet_payload->>'yards_after_catch_per_reception' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'yards_after_catch_per_reception')::numeric END::numeric(4,1) AS receiving_yards_after_catch_per_reception,
  CASE WHEN g.facet_payload->>'yards_per_reception' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'yards_per_reception')::numeric END::numeric(4,1) AS receiving_yards_per_reception,
  CASE WHEN g.facet_payload->>'avg_depth_of_target' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'avg_depth_of_target')::numeric END::numeric(4,1) AS receiving_average_depth_of_target,
  CASE WHEN g.facet_payload->>'targeted_qb_rating' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'targeted_qb_rating')::numeric END::numeric(4,1) AS receiving_targeted_quarterback_rating,
  CASE WHEN g.facet_payload->>'pass_plays' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'pass_plays')::numeric END::smallint AS receiving_pass_plays,
  CASE WHEN g.facet_payload->>'pass_blocks' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'pass_blocks')::numeric END::smallint AS receiving_pass_blocks,
  CASE WHEN g.facet_payload->>'pass_block_rate' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'pass_block_rate')::numeric END::numeric(4,1) AS receiving_pass_block_rate,
  CASE WHEN g.facet_payload->>'route_rate' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'route_rate')::numeric END::numeric(4,1) AS receiving_route_rate,
  CASE WHEN g.facet_payload->>'inline_snaps' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'inline_snaps')::numeric END::smallint AS receiving_inline_snaps,
  CASE WHEN g.facet_payload->>'inline_rate' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'inline_rate')::numeric END::numeric(4,1) AS receiving_inline_rate,
  CASE WHEN g.facet_payload->>'slot_snaps' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'slot_snaps')::numeric END::smallint AS receiving_slot_snaps,
  CASE WHEN g.facet_payload->>'slot_rate' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'slot_rate')::numeric END::numeric(4,1) AS receiving_slot_rate,
  CASE WHEN g.facet_payload->>'wide_snaps' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'wide_snaps')::numeric END::smallint AS receiving_wide_snaps,
  CASE WHEN g.facet_payload->>'wide_rate' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'wide_rate')::numeric END::numeric(4,1) AS receiving_wide_rate
FROM public.pff_player_facet_gamelogs g
JOIN public.nfl_games ng ON ng.esbid::text = g.esbid::text
WHERE g.facet = 'receiving/summary'
ON CONFLICT (pid, esbid) DO UPDATE SET
  grade_offense = COALESCE(EXCLUDED.grade_offense, pff_player_gamelogs.grade_offense),
  grade_offense_penalty = COALESCE(EXCLUDED.grade_offense_penalty, pff_player_gamelogs.grade_offense_penalty),
  grade_defense = COALESCE(EXCLUDED.grade_defense, pff_player_gamelogs.grade_defense),
  grade_defense_penalty = COALESCE(EXCLUDED.grade_defense_penalty, pff_player_gamelogs.grade_defense_penalty),
  grade_pass = COALESCE(EXCLUDED.grade_pass, pff_player_gamelogs.grade_pass),
  grade_run = COALESCE(EXCLUDED.grade_run, pff_player_gamelogs.grade_run),
  grade_pass_block = COALESCE(EXCLUDED.grade_pass_block, pff_player_gamelogs.grade_pass_block),
  grade_run_block = COALESCE(EXCLUDED.grade_run_block, pff_player_gamelogs.grade_run_block),
  grade_pass_route = COALESCE(EXCLUDED.grade_pass_route, pff_player_gamelogs.grade_pass_route),
  grade_hands_drop = COALESCE(EXCLUDED.grade_hands_drop, pff_player_gamelogs.grade_hands_drop),
  grade_hands_fumble = COALESCE(EXCLUDED.grade_hands_fumble, pff_player_gamelogs.grade_hands_fumble),
  grade_coverage_defense = COALESCE(EXCLUDED.grade_coverage_defense, pff_player_gamelogs.grade_coverage_defense),
  grade_pass_rush_defense = COALESCE(EXCLUDED.grade_pass_rush_defense, pff_player_gamelogs.grade_pass_rush_defense),
  grade_run_defense = COALESCE(EXCLUDED.grade_run_defense, pff_player_gamelogs.grade_run_defense),
  grade_tackle = COALESCE(EXCLUDED.grade_tackle, pff_player_gamelogs.grade_tackle),
  grade_punter = COALESCE(EXCLUDED.grade_punter, pff_player_gamelogs.grade_punter),
  penalties = COALESCE(EXCLUDED.penalties, pff_player_gamelogs.penalties),
  declined_penalties = COALESCE(EXCLUDED.declined_penalties, pff_player_gamelogs.declined_penalties),
  routes = COALESCE(EXCLUDED.routes, pff_player_gamelogs.routes),
  yards_per_route_run = COALESCE(EXCLUDED.yards_per_route_run, pff_player_gamelogs.yards_per_route_run),
  scrambles = COALESCE(EXCLUDED.scrambles, pff_player_gamelogs.scrambles),
  receiving_targets = COALESCE(EXCLUDED.receiving_targets, pff_player_gamelogs.receiving_targets),
  receiving_receptions = COALESCE(EXCLUDED.receiving_receptions, pff_player_gamelogs.receiving_receptions),
  receiving_yards = COALESCE(EXCLUDED.receiving_yards, pff_player_gamelogs.receiving_yards),
  receiving_touchdowns = COALESCE(EXCLUDED.receiving_touchdowns, pff_player_gamelogs.receiving_touchdowns),
  receiving_first_downs = COALESCE(EXCLUDED.receiving_first_downs, pff_player_gamelogs.receiving_first_downs),
  receiving_longest = COALESCE(EXCLUDED.receiving_longest, pff_player_gamelogs.receiving_longest),
  receiving_drops = COALESCE(EXCLUDED.receiving_drops, pff_player_gamelogs.receiving_drops),
  receiving_drop_rate = COALESCE(EXCLUDED.receiving_drop_rate, pff_player_gamelogs.receiving_drop_rate),
  receiving_fumbles = COALESCE(EXCLUDED.receiving_fumbles, pff_player_gamelogs.receiving_fumbles),
  receiving_interceptions = COALESCE(EXCLUDED.receiving_interceptions, pff_player_gamelogs.receiving_interceptions),
  receiving_caught_percentage = COALESCE(EXCLUDED.receiving_caught_percentage, pff_player_gamelogs.receiving_caught_percentage),
  receiving_contested_targets = COALESCE(EXCLUDED.receiving_contested_targets, pff_player_gamelogs.receiving_contested_targets),
  receiving_contested_receptions = COALESCE(EXCLUDED.receiving_contested_receptions, pff_player_gamelogs.receiving_contested_receptions),
  receiving_contested_catch_rate = COALESCE(EXCLUDED.receiving_contested_catch_rate, pff_player_gamelogs.receiving_contested_catch_rate),
  receiving_avoided_tackles = COALESCE(EXCLUDED.receiving_avoided_tackles, pff_player_gamelogs.receiving_avoided_tackles),
  receiving_yards_after_catch = COALESCE(EXCLUDED.receiving_yards_after_catch, pff_player_gamelogs.receiving_yards_after_catch),
  receiving_yards_after_catch_per_reception = COALESCE(EXCLUDED.receiving_yards_after_catch_per_reception, pff_player_gamelogs.receiving_yards_after_catch_per_reception),
  receiving_yards_per_reception = COALESCE(EXCLUDED.receiving_yards_per_reception, pff_player_gamelogs.receiving_yards_per_reception),
  receiving_average_depth_of_target = COALESCE(EXCLUDED.receiving_average_depth_of_target, pff_player_gamelogs.receiving_average_depth_of_target),
  receiving_targeted_quarterback_rating = COALESCE(EXCLUDED.receiving_targeted_quarterback_rating, pff_player_gamelogs.receiving_targeted_quarterback_rating),
  receiving_pass_plays = COALESCE(EXCLUDED.receiving_pass_plays, pff_player_gamelogs.receiving_pass_plays),
  receiving_pass_blocks = COALESCE(EXCLUDED.receiving_pass_blocks, pff_player_gamelogs.receiving_pass_blocks),
  receiving_pass_block_rate = COALESCE(EXCLUDED.receiving_pass_block_rate, pff_player_gamelogs.receiving_pass_block_rate),
  receiving_route_rate = COALESCE(EXCLUDED.receiving_route_rate, pff_player_gamelogs.receiving_route_rate),
  receiving_inline_snaps = COALESCE(EXCLUDED.receiving_inline_snaps, pff_player_gamelogs.receiving_inline_snaps),
  receiving_inline_rate = COALESCE(EXCLUDED.receiving_inline_rate, pff_player_gamelogs.receiving_inline_rate),
  receiving_slot_snaps = COALESCE(EXCLUDED.receiving_slot_snaps, pff_player_gamelogs.receiving_slot_snaps),
  receiving_slot_rate = COALESCE(EXCLUDED.receiving_slot_rate, pff_player_gamelogs.receiving_slot_rate),
  receiving_wide_snaps = COALESCE(EXCLUDED.receiving_wide_snaps, pff_player_gamelogs.receiving_wide_snaps),
  receiving_wide_rate = COALESCE(EXCLUDED.receiving_wide_rate, pff_player_gamelogs.receiving_wide_rate),
  nfl_team = COALESCE(pff_player_gamelogs.nfl_team, EXCLUDED.nfl_team),
  player_position = COALESCE(pff_player_gamelogs.player_position, EXCLUDED.player_position),
  updated_at = now();

-- rushing/summary
INSERT INTO public.pff_player_gamelogs (pid, esbid, season_year, pff_game_id, pff_player_id, pff_team_id, nfl_team, player_position, grade_offense, grade_offense_penalty, grade_defense, grade_defense_penalty, grade_pass, grade_run, grade_pass_block, grade_run_block, grade_pass_route, grade_hands_drop, grade_hands_fumble, grade_coverage_defense, grade_pass_rush_defense, grade_run_defense, grade_tackle, grade_punter, penalties, declined_penalties, routes, yards_per_route_run, scrambles, rushing_run_plays, rushing_attempts, rushing_yards, rushing_touchdowns, rushing_first_downs, rushing_longest, rushing_fumbles, rushing_drops, rushing_designed_yards, rushing_scramble_yards, rushing_total_touches, rushing_explosive, rushing_gap_attempts, rushing_zone_attempts, rushing_avoided_tackles, rushing_breakaway_attempts, rushing_breakaway_yards, rushing_breakaway_percentage, rushing_elusive_rating, rushing_elusive_receiving_missed_tackles_forced, rushing_elusive_rushing_missed_tackles_forced, rushing_elusive_yards_after_contact, rushing_yards_after_contact, rushing_yards_after_contact_per_attempt, rushing_yards_per_attempt, rushing_targets, rushing_receptions, rushing_receiving_yards)
SELECT g.pid, g.esbid, ng.season_year, g.pff_game_id, g.pff_player_id, g.pff_team_id, g.nfl_team, g.player_position,
  CASE WHEN g.facet_payload->>'grades_offense' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_offense')::numeric END::numeric(4,1) AS grade_offense,
  CASE WHEN g.facet_payload->>'grades_offense_penalty' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_offense_penalty')::numeric END::numeric(4,1) AS grade_offense_penalty,
  CASE WHEN g.facet_payload->>'grades_defense' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_defense')::numeric END::numeric(4,1) AS grade_defense,
  CASE WHEN g.facet_payload->>'grades_defense_penalty' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_defense_penalty')::numeric END::numeric(4,1) AS grade_defense_penalty,
  CASE WHEN g.facet_payload->>'grades_pass' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_pass')::numeric END::numeric(4,1) AS grade_pass,
  CASE WHEN g.facet_payload->>'grades_run' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_run')::numeric END::numeric(4,1) AS grade_run,
  CASE WHEN g.facet_payload->>'grades_pass_block' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_pass_block')::numeric END::numeric(4,1) AS grade_pass_block,
  CASE WHEN g.facet_payload->>'grades_run_block' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_run_block')::numeric END::numeric(4,1) AS grade_run_block,
  CASE WHEN g.facet_payload->>'grades_pass_route' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_pass_route')::numeric END::numeric(4,1) AS grade_pass_route,
  CASE WHEN g.facet_payload->>'grades_hands_drop' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_hands_drop')::numeric END::numeric(4,1) AS grade_hands_drop,
  CASE WHEN g.facet_payload->>'grades_hands_fumble' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_hands_fumble')::numeric END::numeric(4,1) AS grade_hands_fumble,
  CASE WHEN g.facet_payload->>'grades_coverage_defense' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_coverage_defense')::numeric END::numeric(4,1) AS grade_coverage_defense,
  CASE WHEN g.facet_payload->>'grades_pass_rush_defense' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_pass_rush_defense')::numeric END::numeric(4,1) AS grade_pass_rush_defense,
  CASE WHEN g.facet_payload->>'grades_run_defense' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_run_defense')::numeric END::numeric(4,1) AS grade_run_defense,
  CASE WHEN g.facet_payload->>'grades_tackle' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_tackle')::numeric END::numeric(4,1) AS grade_tackle,
  CASE WHEN g.facet_payload->>'grades_punter' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_punter')::numeric END::numeric(4,1) AS grade_punter,
  CASE WHEN g.facet_payload->>'penalties' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'penalties')::numeric END::smallint AS penalties,
  CASE WHEN g.facet_payload->>'declined_penalties' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'declined_penalties')::numeric END::smallint AS declined_penalties,
  CASE WHEN g.facet_payload->>'routes' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'routes')::numeric END::smallint AS routes,
  CASE WHEN g.facet_payload->>'yprr' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'yprr')::numeric END::numeric(5,2) AS yards_per_route_run,
  CASE WHEN g.facet_payload->>'scrambles' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'scrambles')::numeric END::smallint AS scrambles,
  CASE WHEN g.facet_payload->>'run_plays' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'run_plays')::numeric END::smallint AS rushing_run_plays,
  CASE WHEN g.facet_payload->>'attempts' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'attempts')::numeric END::smallint AS rushing_attempts,
  CASE WHEN g.facet_payload->>'yards' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'yards')::numeric END::smallint AS rushing_yards,
  CASE WHEN g.facet_payload->>'touchdowns' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'touchdowns')::numeric END::smallint AS rushing_touchdowns,
  CASE WHEN g.facet_payload->>'first_downs' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'first_downs')::numeric END::smallint AS rushing_first_downs,
  CASE WHEN g.facet_payload->>'longest' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'longest')::numeric END::smallint AS rushing_longest,
  CASE WHEN g.facet_payload->>'fumbles' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'fumbles')::numeric END::smallint AS rushing_fumbles,
  CASE WHEN g.facet_payload->>'drops' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'drops')::numeric END::smallint AS rushing_drops,
  CASE WHEN g.facet_payload->>'designed_yards' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'designed_yards')::numeric END::smallint AS rushing_designed_yards,
  CASE WHEN g.facet_payload->>'scramble_yards' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'scramble_yards')::numeric END::smallint AS rushing_scramble_yards,
  CASE WHEN g.facet_payload->>'total_touches' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'total_touches')::numeric END::smallint AS rushing_total_touches,
  CASE WHEN g.facet_payload->>'explosive' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'explosive')::numeric END::smallint AS rushing_explosive,
  CASE WHEN g.facet_payload->>'gap_attempts' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'gap_attempts')::numeric END::smallint AS rushing_gap_attempts,
  CASE WHEN g.facet_payload->>'zone_attempts' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'zone_attempts')::numeric END::smallint AS rushing_zone_attempts,
  CASE WHEN g.facet_payload->>'avoided_tackles' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'avoided_tackles')::numeric END::smallint AS rushing_avoided_tackles,
  CASE WHEN g.facet_payload->>'breakaway_attempts' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'breakaway_attempts')::numeric END::smallint AS rushing_breakaway_attempts,
  CASE WHEN g.facet_payload->>'breakaway_yards' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'breakaway_yards')::numeric END::smallint AS rushing_breakaway_yards,
  CASE WHEN g.facet_payload->>'breakaway_percent' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'breakaway_percent')::numeric END::numeric(4,1) AS rushing_breakaway_percentage,
  CASE WHEN g.facet_payload->>'elusive_rating' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'elusive_rating')::numeric END::numeric(6,1) AS rushing_elusive_rating,
  CASE WHEN g.facet_payload->>'elu_recv_mtf' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'elu_recv_mtf')::numeric END::smallint AS rushing_elusive_receiving_missed_tackles_forced,
  CASE WHEN g.facet_payload->>'elu_rush_mtf' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'elu_rush_mtf')::numeric END::smallint AS rushing_elusive_rushing_missed_tackles_forced,
  CASE WHEN g.facet_payload->>'elu_yco' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'elu_yco')::numeric END::smallint AS rushing_elusive_yards_after_contact,
  CASE WHEN g.facet_payload->>'yards_after_contact' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'yards_after_contact')::numeric END::smallint AS rushing_yards_after_contact,
  CASE WHEN g.facet_payload->>'yco_attempt' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'yco_attempt')::numeric END::numeric(5,2) AS rushing_yards_after_contact_per_attempt,
  CASE WHEN g.facet_payload->>'ypa' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'ypa')::numeric END::numeric(4,1) AS rushing_yards_per_attempt,
  CASE WHEN g.facet_payload->>'targets' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'targets')::numeric END::smallint AS rushing_targets,
  CASE WHEN g.facet_payload->>'receptions' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'receptions')::numeric END::smallint AS rushing_receptions,
  CASE WHEN g.facet_payload->>'rec_yards' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'rec_yards')::numeric END::smallint AS rushing_receiving_yards
FROM public.pff_player_facet_gamelogs g
JOIN public.nfl_games ng ON ng.esbid::text = g.esbid::text
WHERE g.facet = 'rushing/summary'
ON CONFLICT (pid, esbid) DO UPDATE SET
  grade_offense = COALESCE(EXCLUDED.grade_offense, pff_player_gamelogs.grade_offense),
  grade_offense_penalty = COALESCE(EXCLUDED.grade_offense_penalty, pff_player_gamelogs.grade_offense_penalty),
  grade_defense = COALESCE(EXCLUDED.grade_defense, pff_player_gamelogs.grade_defense),
  grade_defense_penalty = COALESCE(EXCLUDED.grade_defense_penalty, pff_player_gamelogs.grade_defense_penalty),
  grade_pass = COALESCE(EXCLUDED.grade_pass, pff_player_gamelogs.grade_pass),
  grade_run = COALESCE(EXCLUDED.grade_run, pff_player_gamelogs.grade_run),
  grade_pass_block = COALESCE(EXCLUDED.grade_pass_block, pff_player_gamelogs.grade_pass_block),
  grade_run_block = COALESCE(EXCLUDED.grade_run_block, pff_player_gamelogs.grade_run_block),
  grade_pass_route = COALESCE(EXCLUDED.grade_pass_route, pff_player_gamelogs.grade_pass_route),
  grade_hands_drop = COALESCE(EXCLUDED.grade_hands_drop, pff_player_gamelogs.grade_hands_drop),
  grade_hands_fumble = COALESCE(EXCLUDED.grade_hands_fumble, pff_player_gamelogs.grade_hands_fumble),
  grade_coverage_defense = COALESCE(EXCLUDED.grade_coverage_defense, pff_player_gamelogs.grade_coverage_defense),
  grade_pass_rush_defense = COALESCE(EXCLUDED.grade_pass_rush_defense, pff_player_gamelogs.grade_pass_rush_defense),
  grade_run_defense = COALESCE(EXCLUDED.grade_run_defense, pff_player_gamelogs.grade_run_defense),
  grade_tackle = COALESCE(EXCLUDED.grade_tackle, pff_player_gamelogs.grade_tackle),
  grade_punter = COALESCE(EXCLUDED.grade_punter, pff_player_gamelogs.grade_punter),
  penalties = COALESCE(EXCLUDED.penalties, pff_player_gamelogs.penalties),
  declined_penalties = COALESCE(EXCLUDED.declined_penalties, pff_player_gamelogs.declined_penalties),
  routes = COALESCE(EXCLUDED.routes, pff_player_gamelogs.routes),
  yards_per_route_run = COALESCE(EXCLUDED.yards_per_route_run, pff_player_gamelogs.yards_per_route_run),
  scrambles = COALESCE(EXCLUDED.scrambles, pff_player_gamelogs.scrambles),
  rushing_run_plays = COALESCE(EXCLUDED.rushing_run_plays, pff_player_gamelogs.rushing_run_plays),
  rushing_attempts = COALESCE(EXCLUDED.rushing_attempts, pff_player_gamelogs.rushing_attempts),
  rushing_yards = COALESCE(EXCLUDED.rushing_yards, pff_player_gamelogs.rushing_yards),
  rushing_touchdowns = COALESCE(EXCLUDED.rushing_touchdowns, pff_player_gamelogs.rushing_touchdowns),
  rushing_first_downs = COALESCE(EXCLUDED.rushing_first_downs, pff_player_gamelogs.rushing_first_downs),
  rushing_longest = COALESCE(EXCLUDED.rushing_longest, pff_player_gamelogs.rushing_longest),
  rushing_fumbles = COALESCE(EXCLUDED.rushing_fumbles, pff_player_gamelogs.rushing_fumbles),
  rushing_drops = COALESCE(EXCLUDED.rushing_drops, pff_player_gamelogs.rushing_drops),
  rushing_designed_yards = COALESCE(EXCLUDED.rushing_designed_yards, pff_player_gamelogs.rushing_designed_yards),
  rushing_scramble_yards = COALESCE(EXCLUDED.rushing_scramble_yards, pff_player_gamelogs.rushing_scramble_yards),
  rushing_total_touches = COALESCE(EXCLUDED.rushing_total_touches, pff_player_gamelogs.rushing_total_touches),
  rushing_explosive = COALESCE(EXCLUDED.rushing_explosive, pff_player_gamelogs.rushing_explosive),
  rushing_gap_attempts = COALESCE(EXCLUDED.rushing_gap_attempts, pff_player_gamelogs.rushing_gap_attempts),
  rushing_zone_attempts = COALESCE(EXCLUDED.rushing_zone_attempts, pff_player_gamelogs.rushing_zone_attempts),
  rushing_avoided_tackles = COALESCE(EXCLUDED.rushing_avoided_tackles, pff_player_gamelogs.rushing_avoided_tackles),
  rushing_breakaway_attempts = COALESCE(EXCLUDED.rushing_breakaway_attempts, pff_player_gamelogs.rushing_breakaway_attempts),
  rushing_breakaway_yards = COALESCE(EXCLUDED.rushing_breakaway_yards, pff_player_gamelogs.rushing_breakaway_yards),
  rushing_breakaway_percentage = COALESCE(EXCLUDED.rushing_breakaway_percentage, pff_player_gamelogs.rushing_breakaway_percentage),
  rushing_elusive_rating = COALESCE(EXCLUDED.rushing_elusive_rating, pff_player_gamelogs.rushing_elusive_rating),
  rushing_elusive_receiving_missed_tackles_forced = COALESCE(EXCLUDED.rushing_elusive_receiving_missed_tackles_forced, pff_player_gamelogs.rushing_elusive_receiving_missed_tackles_forced),
  rushing_elusive_rushing_missed_tackles_forced = COALESCE(EXCLUDED.rushing_elusive_rushing_missed_tackles_forced, pff_player_gamelogs.rushing_elusive_rushing_missed_tackles_forced),
  rushing_elusive_yards_after_contact = COALESCE(EXCLUDED.rushing_elusive_yards_after_contact, pff_player_gamelogs.rushing_elusive_yards_after_contact),
  rushing_yards_after_contact = COALESCE(EXCLUDED.rushing_yards_after_contact, pff_player_gamelogs.rushing_yards_after_contact),
  rushing_yards_after_contact_per_attempt = COALESCE(EXCLUDED.rushing_yards_after_contact_per_attempt, pff_player_gamelogs.rushing_yards_after_contact_per_attempt),
  rushing_yards_per_attempt = COALESCE(EXCLUDED.rushing_yards_per_attempt, pff_player_gamelogs.rushing_yards_per_attempt),
  rushing_targets = COALESCE(EXCLUDED.rushing_targets, pff_player_gamelogs.rushing_targets),
  rushing_receptions = COALESCE(EXCLUDED.rushing_receptions, pff_player_gamelogs.rushing_receptions),
  rushing_receiving_yards = COALESCE(EXCLUDED.rushing_receiving_yards, pff_player_gamelogs.rushing_receiving_yards),
  nfl_team = COALESCE(pff_player_gamelogs.nfl_team, EXCLUDED.nfl_team),
  player_position = COALESCE(pff_player_gamelogs.player_position, EXCLUDED.player_position),
  updated_at = now();

-- defense/summary
INSERT INTO public.pff_player_gamelogs (pid, esbid, season_year, pff_game_id, pff_player_id, pff_team_id, nfl_team, player_position, grade_offense, grade_offense_penalty, grade_defense, grade_defense_penalty, grade_pass, grade_run, grade_pass_block, grade_run_block, grade_pass_route, grade_hands_drop, grade_hands_fumble, grade_coverage_defense, grade_pass_rush_defense, grade_run_defense, grade_tackle, grade_punter, penalties, declined_penalties, routes, yards_per_route_run, scrambles, defense_snaps, defense_snaps_box, defense_snaps_corner, defense_snaps_coverage, defense_snaps_defensive_line, defense_snaps_center_guard_gap, defense_snaps_guard_tackle_gap, defense_snaps_defensive_line_outside_tackle, defense_snaps_defensive_line_over_tackle, defense_snaps_free_safety, defense_snaps_second_level, defense_snaps_pass_rush, defense_snaps_run_defense, defense_snaps_slot, defense_tackles, defense_assists, defense_missed_tackles, defense_missed_tackle_rate, defense_tackles_for_loss, defense_stops, defense_sacks, defense_hits, defense_hurries, defense_total_pressures, defense_batted_passes, defense_pass_breakups, defense_interceptions, defense_interception_touchdowns, defense_forced_fumbles, defense_fumble_recoveries, defense_fumble_recovery_touchdowns, defense_safeties, defense_targets_allowed, defense_receptions_allowed, defense_yards_allowed, defense_touchdowns_allowed, defense_yards_after_catch_allowed, defense_yards_per_reception_allowed, defense_longest_reception_allowed, defense_catch_rate_allowed, defense_quarterback_rating_against)
SELECT g.pid, g.esbid, ng.season_year, g.pff_game_id, g.pff_player_id, g.pff_team_id, g.nfl_team, g.player_position,
  CASE WHEN g.facet_payload->>'grades_offense' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_offense')::numeric END::numeric(4,1) AS grade_offense,
  CASE WHEN g.facet_payload->>'grades_offense_penalty' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_offense_penalty')::numeric END::numeric(4,1) AS grade_offense_penalty,
  CASE WHEN g.facet_payload->>'grades_defense' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_defense')::numeric END::numeric(4,1) AS grade_defense,
  CASE WHEN g.facet_payload->>'grades_defense_penalty' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_defense_penalty')::numeric END::numeric(4,1) AS grade_defense_penalty,
  CASE WHEN g.facet_payload->>'grades_pass' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_pass')::numeric END::numeric(4,1) AS grade_pass,
  CASE WHEN g.facet_payload->>'grades_run' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_run')::numeric END::numeric(4,1) AS grade_run,
  CASE WHEN g.facet_payload->>'grades_pass_block' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_pass_block')::numeric END::numeric(4,1) AS grade_pass_block,
  CASE WHEN g.facet_payload->>'grades_run_block' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_run_block')::numeric END::numeric(4,1) AS grade_run_block,
  CASE WHEN g.facet_payload->>'grades_pass_route' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_pass_route')::numeric END::numeric(4,1) AS grade_pass_route,
  CASE WHEN g.facet_payload->>'grades_hands_drop' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_hands_drop')::numeric END::numeric(4,1) AS grade_hands_drop,
  CASE WHEN g.facet_payload->>'grades_hands_fumble' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_hands_fumble')::numeric END::numeric(4,1) AS grade_hands_fumble,
  CASE WHEN g.facet_payload->>'grades_coverage_defense' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_coverage_defense')::numeric END::numeric(4,1) AS grade_coverage_defense,
  CASE WHEN g.facet_payload->>'grades_pass_rush_defense' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_pass_rush_defense')::numeric END::numeric(4,1) AS grade_pass_rush_defense,
  CASE WHEN g.facet_payload->>'grades_run_defense' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_run_defense')::numeric END::numeric(4,1) AS grade_run_defense,
  CASE WHEN g.facet_payload->>'grades_tackle' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_tackle')::numeric END::numeric(4,1) AS grade_tackle,
  CASE WHEN g.facet_payload->>'grades_punter' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_punter')::numeric END::numeric(4,1) AS grade_punter,
  CASE WHEN g.facet_payload->>'penalties' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'penalties')::numeric END::smallint AS penalties,
  CASE WHEN g.facet_payload->>'declined_penalties' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'declined_penalties')::numeric END::smallint AS declined_penalties,
  CASE WHEN g.facet_payload->>'routes' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'routes')::numeric END::smallint AS routes,
  CASE WHEN g.facet_payload->>'yprr' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'yprr')::numeric END::numeric(5,2) AS yards_per_route_run,
  CASE WHEN g.facet_payload->>'scrambles' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'scrambles')::numeric END::smallint AS scrambles,
  CASE WHEN g.facet_payload->>'snap_counts_defense' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'snap_counts_defense')::numeric END::smallint AS defense_snaps,
  CASE WHEN g.facet_payload->>'snap_counts_box' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'snap_counts_box')::numeric END::smallint AS defense_snaps_box,
  CASE WHEN g.facet_payload->>'snap_counts_corner' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'snap_counts_corner')::numeric END::smallint AS defense_snaps_corner,
  CASE WHEN g.facet_payload->>'snap_counts_coverage' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'snap_counts_coverage')::numeric END::smallint AS defense_snaps_coverage,
  CASE WHEN g.facet_payload->>'snap_counts_dl' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'snap_counts_dl')::numeric END::smallint AS defense_snaps_defensive_line,
  CASE WHEN g.facet_payload->>'snap_counts_dl_a_gap' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'snap_counts_dl_a_gap')::numeric END::smallint AS defense_snaps_center_guard_gap,
  CASE WHEN g.facet_payload->>'snap_counts_dl_b_gap' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'snap_counts_dl_b_gap')::numeric END::smallint AS defense_snaps_guard_tackle_gap,
  CASE WHEN g.facet_payload->>'snap_counts_dl_outside_t' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'snap_counts_dl_outside_t')::numeric END::smallint AS defense_snaps_defensive_line_outside_tackle,
  CASE WHEN g.facet_payload->>'snap_counts_dl_over_t' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'snap_counts_dl_over_t')::numeric END::smallint AS defense_snaps_defensive_line_over_tackle,
  CASE WHEN g.facet_payload->>'snap_counts_fs' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'snap_counts_fs')::numeric END::smallint AS defense_snaps_free_safety,
  CASE WHEN g.facet_payload->>'snap_counts_offball' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'snap_counts_offball')::numeric END::smallint AS defense_snaps_second_level,
  CASE WHEN g.facet_payload->>'snap_counts_pass_rush' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'snap_counts_pass_rush')::numeric END::smallint AS defense_snaps_pass_rush,
  CASE WHEN g.facet_payload->>'snap_counts_run_defense' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'snap_counts_run_defense')::numeric END::smallint AS defense_snaps_run_defense,
  CASE WHEN g.facet_payload->>'snap_counts_slot' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'snap_counts_slot')::numeric END::smallint AS defense_snaps_slot,
  CASE WHEN g.facet_payload->>'tackles' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'tackles')::numeric END::smallint AS defense_tackles,
  CASE WHEN g.facet_payload->>'assists' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'assists')::numeric END::smallint AS defense_assists,
  CASE WHEN g.facet_payload->>'missed_tackles' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'missed_tackles')::numeric END::smallint AS defense_missed_tackles,
  CASE WHEN g.facet_payload->>'missed_tackle_rate' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'missed_tackle_rate')::numeric END::numeric(4,1) AS defense_missed_tackle_rate,
  CASE WHEN g.facet_payload->>'tackles_for_loss' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'tackles_for_loss')::numeric END::smallint AS defense_tackles_for_loss,
  CASE WHEN g.facet_payload->>'stops' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'stops')::numeric END::smallint AS defense_stops,
  CASE WHEN g.facet_payload->>'sacks' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'sacks')::numeric END::smallint AS defense_sacks,
  CASE WHEN g.facet_payload->>'hits' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'hits')::numeric END::smallint AS defense_hits,
  CASE WHEN g.facet_payload->>'hurries' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'hurries')::numeric END::smallint AS defense_hurries,
  CASE WHEN g.facet_payload->>'total_pressures' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'total_pressures')::numeric END::smallint AS defense_total_pressures,
  CASE WHEN g.facet_payload->>'batted_passes' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'batted_passes')::numeric END::smallint AS defense_batted_passes,
  CASE WHEN g.facet_payload->>'pass_break_ups' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'pass_break_ups')::numeric END::smallint AS defense_pass_breakups,
  CASE WHEN g.facet_payload->>'interceptions' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'interceptions')::numeric END::smallint AS defense_interceptions,
  CASE WHEN g.facet_payload->>'interception_touchdowns' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'interception_touchdowns')::numeric END::smallint AS defense_interception_touchdowns,
  CASE WHEN g.facet_payload->>'forced_fumbles' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'forced_fumbles')::numeric END::smallint AS defense_forced_fumbles,
  CASE WHEN g.facet_payload->>'fumble_recoveries' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'fumble_recoveries')::numeric END::smallint AS defense_fumble_recoveries,
  CASE WHEN g.facet_payload->>'fumble_recovery_touchdowns' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'fumble_recovery_touchdowns')::numeric END::smallint AS defense_fumble_recovery_touchdowns,
  CASE WHEN g.facet_payload->>'safeties' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'safeties')::numeric END::smallint AS defense_safeties,
  CASE WHEN g.facet_payload->>'targets' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'targets')::numeric END::smallint AS defense_targets_allowed,
  CASE WHEN g.facet_payload->>'receptions' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'receptions')::numeric END::smallint AS defense_receptions_allowed,
  CASE WHEN g.facet_payload->>'yards' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'yards')::numeric END::smallint AS defense_yards_allowed,
  CASE WHEN g.facet_payload->>'touchdowns' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'touchdowns')::numeric END::smallint AS defense_touchdowns_allowed,
  CASE WHEN g.facet_payload->>'yards_after_catch' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'yards_after_catch')::numeric END::smallint AS defense_yards_after_catch_allowed,
  CASE WHEN g.facet_payload->>'yards_per_reception' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'yards_per_reception')::numeric END::numeric(4,1) AS defense_yards_per_reception_allowed,
  CASE WHEN g.facet_payload->>'longest' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'longest')::numeric END::smallint AS defense_longest_reception_allowed,
  CASE WHEN g.facet_payload->>'catch_rate' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'catch_rate')::numeric END::numeric(4,1) AS defense_catch_rate_allowed,
  CASE WHEN g.facet_payload->>'qb_rating_against' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'qb_rating_against')::numeric END::numeric(4,1) AS defense_quarterback_rating_against
FROM public.pff_player_facet_gamelogs g
JOIN public.nfl_games ng ON ng.esbid::text = g.esbid::text
WHERE g.facet = 'defense/summary'
ON CONFLICT (pid, esbid) DO UPDATE SET
  grade_offense = COALESCE(EXCLUDED.grade_offense, pff_player_gamelogs.grade_offense),
  grade_offense_penalty = COALESCE(EXCLUDED.grade_offense_penalty, pff_player_gamelogs.grade_offense_penalty),
  grade_defense = COALESCE(EXCLUDED.grade_defense, pff_player_gamelogs.grade_defense),
  grade_defense_penalty = COALESCE(EXCLUDED.grade_defense_penalty, pff_player_gamelogs.grade_defense_penalty),
  grade_pass = COALESCE(EXCLUDED.grade_pass, pff_player_gamelogs.grade_pass),
  grade_run = COALESCE(EXCLUDED.grade_run, pff_player_gamelogs.grade_run),
  grade_pass_block = COALESCE(EXCLUDED.grade_pass_block, pff_player_gamelogs.grade_pass_block),
  grade_run_block = COALESCE(EXCLUDED.grade_run_block, pff_player_gamelogs.grade_run_block),
  grade_pass_route = COALESCE(EXCLUDED.grade_pass_route, pff_player_gamelogs.grade_pass_route),
  grade_hands_drop = COALESCE(EXCLUDED.grade_hands_drop, pff_player_gamelogs.grade_hands_drop),
  grade_hands_fumble = COALESCE(EXCLUDED.grade_hands_fumble, pff_player_gamelogs.grade_hands_fumble),
  grade_coverage_defense = COALESCE(EXCLUDED.grade_coverage_defense, pff_player_gamelogs.grade_coverage_defense),
  grade_pass_rush_defense = COALESCE(EXCLUDED.grade_pass_rush_defense, pff_player_gamelogs.grade_pass_rush_defense),
  grade_run_defense = COALESCE(EXCLUDED.grade_run_defense, pff_player_gamelogs.grade_run_defense),
  grade_tackle = COALESCE(EXCLUDED.grade_tackle, pff_player_gamelogs.grade_tackle),
  grade_punter = COALESCE(EXCLUDED.grade_punter, pff_player_gamelogs.grade_punter),
  penalties = COALESCE(EXCLUDED.penalties, pff_player_gamelogs.penalties),
  declined_penalties = COALESCE(EXCLUDED.declined_penalties, pff_player_gamelogs.declined_penalties),
  routes = COALESCE(EXCLUDED.routes, pff_player_gamelogs.routes),
  yards_per_route_run = COALESCE(EXCLUDED.yards_per_route_run, pff_player_gamelogs.yards_per_route_run),
  scrambles = COALESCE(EXCLUDED.scrambles, pff_player_gamelogs.scrambles),
  defense_snaps = COALESCE(EXCLUDED.defense_snaps, pff_player_gamelogs.defense_snaps),
  defense_snaps_box = COALESCE(EXCLUDED.defense_snaps_box, pff_player_gamelogs.defense_snaps_box),
  defense_snaps_corner = COALESCE(EXCLUDED.defense_snaps_corner, pff_player_gamelogs.defense_snaps_corner),
  defense_snaps_coverage = COALESCE(EXCLUDED.defense_snaps_coverage, pff_player_gamelogs.defense_snaps_coverage),
  defense_snaps_defensive_line = COALESCE(EXCLUDED.defense_snaps_defensive_line, pff_player_gamelogs.defense_snaps_defensive_line),
  defense_snaps_center_guard_gap = COALESCE(EXCLUDED.defense_snaps_center_guard_gap, pff_player_gamelogs.defense_snaps_center_guard_gap),
  defense_snaps_guard_tackle_gap = COALESCE(EXCLUDED.defense_snaps_guard_tackle_gap, pff_player_gamelogs.defense_snaps_guard_tackle_gap),
  defense_snaps_defensive_line_outside_tackle = COALESCE(EXCLUDED.defense_snaps_defensive_line_outside_tackle, pff_player_gamelogs.defense_snaps_defensive_line_outside_tackle),
  defense_snaps_defensive_line_over_tackle = COALESCE(EXCLUDED.defense_snaps_defensive_line_over_tackle, pff_player_gamelogs.defense_snaps_defensive_line_over_tackle),
  defense_snaps_free_safety = COALESCE(EXCLUDED.defense_snaps_free_safety, pff_player_gamelogs.defense_snaps_free_safety),
  defense_snaps_second_level = COALESCE(EXCLUDED.defense_snaps_second_level, pff_player_gamelogs.defense_snaps_second_level),
  defense_snaps_pass_rush = COALESCE(EXCLUDED.defense_snaps_pass_rush, pff_player_gamelogs.defense_snaps_pass_rush),
  defense_snaps_run_defense = COALESCE(EXCLUDED.defense_snaps_run_defense, pff_player_gamelogs.defense_snaps_run_defense),
  defense_snaps_slot = COALESCE(EXCLUDED.defense_snaps_slot, pff_player_gamelogs.defense_snaps_slot),
  defense_tackles = COALESCE(EXCLUDED.defense_tackles, pff_player_gamelogs.defense_tackles),
  defense_assists = COALESCE(EXCLUDED.defense_assists, pff_player_gamelogs.defense_assists),
  defense_missed_tackles = COALESCE(EXCLUDED.defense_missed_tackles, pff_player_gamelogs.defense_missed_tackles),
  defense_missed_tackle_rate = COALESCE(EXCLUDED.defense_missed_tackle_rate, pff_player_gamelogs.defense_missed_tackle_rate),
  defense_tackles_for_loss = COALESCE(EXCLUDED.defense_tackles_for_loss, pff_player_gamelogs.defense_tackles_for_loss),
  defense_stops = COALESCE(EXCLUDED.defense_stops, pff_player_gamelogs.defense_stops),
  defense_sacks = COALESCE(EXCLUDED.defense_sacks, pff_player_gamelogs.defense_sacks),
  defense_hits = COALESCE(EXCLUDED.defense_hits, pff_player_gamelogs.defense_hits),
  defense_hurries = COALESCE(EXCLUDED.defense_hurries, pff_player_gamelogs.defense_hurries),
  defense_total_pressures = COALESCE(EXCLUDED.defense_total_pressures, pff_player_gamelogs.defense_total_pressures),
  defense_batted_passes = COALESCE(EXCLUDED.defense_batted_passes, pff_player_gamelogs.defense_batted_passes),
  defense_pass_breakups = COALESCE(EXCLUDED.defense_pass_breakups, pff_player_gamelogs.defense_pass_breakups),
  defense_interceptions = COALESCE(EXCLUDED.defense_interceptions, pff_player_gamelogs.defense_interceptions),
  defense_interception_touchdowns = COALESCE(EXCLUDED.defense_interception_touchdowns, pff_player_gamelogs.defense_interception_touchdowns),
  defense_forced_fumbles = COALESCE(EXCLUDED.defense_forced_fumbles, pff_player_gamelogs.defense_forced_fumbles),
  defense_fumble_recoveries = COALESCE(EXCLUDED.defense_fumble_recoveries, pff_player_gamelogs.defense_fumble_recoveries),
  defense_fumble_recovery_touchdowns = COALESCE(EXCLUDED.defense_fumble_recovery_touchdowns, pff_player_gamelogs.defense_fumble_recovery_touchdowns),
  defense_safeties = COALESCE(EXCLUDED.defense_safeties, pff_player_gamelogs.defense_safeties),
  defense_targets_allowed = COALESCE(EXCLUDED.defense_targets_allowed, pff_player_gamelogs.defense_targets_allowed),
  defense_receptions_allowed = COALESCE(EXCLUDED.defense_receptions_allowed, pff_player_gamelogs.defense_receptions_allowed),
  defense_yards_allowed = COALESCE(EXCLUDED.defense_yards_allowed, pff_player_gamelogs.defense_yards_allowed),
  defense_touchdowns_allowed = COALESCE(EXCLUDED.defense_touchdowns_allowed, pff_player_gamelogs.defense_touchdowns_allowed),
  defense_yards_after_catch_allowed = COALESCE(EXCLUDED.defense_yards_after_catch_allowed, pff_player_gamelogs.defense_yards_after_catch_allowed),
  defense_yards_per_reception_allowed = COALESCE(EXCLUDED.defense_yards_per_reception_allowed, pff_player_gamelogs.defense_yards_per_reception_allowed),
  defense_longest_reception_allowed = COALESCE(EXCLUDED.defense_longest_reception_allowed, pff_player_gamelogs.defense_longest_reception_allowed),
  defense_catch_rate_allowed = COALESCE(EXCLUDED.defense_catch_rate_allowed, pff_player_gamelogs.defense_catch_rate_allowed),
  defense_quarterback_rating_against = COALESCE(EXCLUDED.defense_quarterback_rating_against, pff_player_gamelogs.defense_quarterback_rating_against),
  nfl_team = COALESCE(pff_player_gamelogs.nfl_team, EXCLUDED.nfl_team),
  player_position = COALESCE(pff_player_gamelogs.player_position, EXCLUDED.player_position),
  updated_at = now();

-- punting/summary
INSERT INTO public.pff_player_gamelogs (pid, esbid, season_year, pff_game_id, pff_player_id, pff_team_id, nfl_team, player_position, grade_offense, grade_offense_penalty, grade_defense, grade_defense_penalty, grade_pass, grade_run, grade_pass_block, grade_run_block, grade_pass_route, grade_hands_drop, grade_hands_fumble, grade_coverage_defense, grade_pass_rush_defense, grade_run_defense, grade_tackle, grade_punter, penalties, declined_penalties, routes, yards_per_route_run, scrambles, punting_snaps, punting_attempts, punting_yards, punting_blocks, punting_touchbacks, punting_inside_twenty_yard_line, punting_downed, punting_out_of_bounds, punting_fair_catches, punting_returns, punting_return_yards, punting_longest_punt, punting_total_net_yards, punting_average_net_yards, punting_average_yards_per_attempt, punting_average_yards_per_return, punting_percentage_returned, punting_attempts_with_hangtime, punting_total_hangtime, punting_average_hangtime)
SELECT g.pid, g.esbid, ng.season_year, g.pff_game_id, g.pff_player_id, g.pff_team_id, g.nfl_team, g.player_position,
  CASE WHEN g.facet_payload->>'grades_offense' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_offense')::numeric END::numeric(4,1) AS grade_offense,
  CASE WHEN g.facet_payload->>'grades_offense_penalty' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_offense_penalty')::numeric END::numeric(4,1) AS grade_offense_penalty,
  CASE WHEN g.facet_payload->>'grades_defense' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_defense')::numeric END::numeric(4,1) AS grade_defense,
  CASE WHEN g.facet_payload->>'grades_defense_penalty' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_defense_penalty')::numeric END::numeric(4,1) AS grade_defense_penalty,
  CASE WHEN g.facet_payload->>'grades_pass' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_pass')::numeric END::numeric(4,1) AS grade_pass,
  CASE WHEN g.facet_payload->>'grades_run' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_run')::numeric END::numeric(4,1) AS grade_run,
  CASE WHEN g.facet_payload->>'grades_pass_block' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_pass_block')::numeric END::numeric(4,1) AS grade_pass_block,
  CASE WHEN g.facet_payload->>'grades_run_block' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_run_block')::numeric END::numeric(4,1) AS grade_run_block,
  CASE WHEN g.facet_payload->>'grades_pass_route' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_pass_route')::numeric END::numeric(4,1) AS grade_pass_route,
  CASE WHEN g.facet_payload->>'grades_hands_drop' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_hands_drop')::numeric END::numeric(4,1) AS grade_hands_drop,
  CASE WHEN g.facet_payload->>'grades_hands_fumble' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_hands_fumble')::numeric END::numeric(4,1) AS grade_hands_fumble,
  CASE WHEN g.facet_payload->>'grades_coverage_defense' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_coverage_defense')::numeric END::numeric(4,1) AS grade_coverage_defense,
  CASE WHEN g.facet_payload->>'grades_pass_rush_defense' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_pass_rush_defense')::numeric END::numeric(4,1) AS grade_pass_rush_defense,
  CASE WHEN g.facet_payload->>'grades_run_defense' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_run_defense')::numeric END::numeric(4,1) AS grade_run_defense,
  CASE WHEN g.facet_payload->>'grades_tackle' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_tackle')::numeric END::numeric(4,1) AS grade_tackle,
  CASE WHEN g.facet_payload->>'grades_punter' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'grades_punter')::numeric END::numeric(4,1) AS grade_punter,
  CASE WHEN g.facet_payload->>'penalties' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'penalties')::numeric END::smallint AS penalties,
  CASE WHEN g.facet_payload->>'declined_penalties' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'declined_penalties')::numeric END::smallint AS declined_penalties,
  CASE WHEN g.facet_payload->>'routes' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'routes')::numeric END::smallint AS routes,
  CASE WHEN g.facet_payload->>'yprr' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'yprr')::numeric END::numeric(5,2) AS yards_per_route_run,
  CASE WHEN g.facet_payload->>'scrambles' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'scrambles')::numeric END::smallint AS scrambles,
  CASE WHEN g.facet_payload->>'snaps' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'snaps')::numeric END::smallint AS punting_snaps,
  CASE WHEN g.facet_payload->>'attempts' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'attempts')::numeric END::smallint AS punting_attempts,
  CASE WHEN g.facet_payload->>'yards' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'yards')::numeric END::smallint AS punting_yards,
  CASE WHEN g.facet_payload->>'blocks' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'blocks')::numeric END::smallint AS punting_blocks,
  CASE WHEN g.facet_payload->>'touchbacks' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'touchbacks')::numeric END::smallint AS punting_touchbacks,
  CASE WHEN g.facet_payload->>'inside_twenties' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'inside_twenties')::numeric END::smallint AS punting_inside_twenty_yard_line,
  CASE WHEN g.facet_payload->>'downeds' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'downeds')::numeric END::smallint AS punting_downed,
  CASE WHEN g.facet_payload->>'out_of_bounds' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'out_of_bounds')::numeric END::smallint AS punting_out_of_bounds,
  CASE WHEN g.facet_payload->>'fair_catches' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'fair_catches')::numeric END::smallint AS punting_fair_catches,
  CASE WHEN g.facet_payload->>'returns' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'returns')::numeric END::smallint AS punting_returns,
  CASE WHEN g.facet_payload->>'return_yards' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'return_yards')::numeric END::smallint AS punting_return_yards,
  CASE WHEN g.facet_payload->>'long' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'long')::numeric END::smallint AS punting_longest_punt,
  CASE WHEN g.facet_payload->>'total_net_yards' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'total_net_yards')::numeric END::smallint AS punting_total_net_yards,
  CASE WHEN g.facet_payload->>'average_net_yards' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'average_net_yards')::numeric END::numeric(5,2) AS punting_average_net_yards,
  CASE WHEN g.facet_payload->>'average_yards_per_attempt' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'average_yards_per_attempt')::numeric END::numeric(5,2) AS punting_average_yards_per_attempt,
  CASE WHEN g.facet_payload->>'average_yards_per_return' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'average_yards_per_return')::numeric END::numeric(4,1) AS punting_average_yards_per_return,
  CASE WHEN g.facet_payload->>'percent_returned' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'percent_returned')::numeric END::numeric(4,1) AS punting_percentage_returned,
  CASE WHEN g.facet_payload->>'attempts_with_hangtime' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'attempts_with_hangtime')::numeric END::smallint AS punting_attempts_with_hangtime,
  CASE WHEN g.facet_payload->>'total_hangtime' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'total_hangtime')::numeric END::numeric(5,2) AS punting_total_hangtime,
  CASE WHEN g.facet_payload->>'average_hangtime' ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (g.facet_payload->>'average_hangtime')::numeric END::numeric(4,2) AS punting_average_hangtime
FROM public.pff_player_facet_gamelogs g
JOIN public.nfl_games ng ON ng.esbid::text = g.esbid::text
WHERE g.facet = 'punting/summary'
ON CONFLICT (pid, esbid) DO UPDATE SET
  grade_offense = COALESCE(EXCLUDED.grade_offense, pff_player_gamelogs.grade_offense),
  grade_offense_penalty = COALESCE(EXCLUDED.grade_offense_penalty, pff_player_gamelogs.grade_offense_penalty),
  grade_defense = COALESCE(EXCLUDED.grade_defense, pff_player_gamelogs.grade_defense),
  grade_defense_penalty = COALESCE(EXCLUDED.grade_defense_penalty, pff_player_gamelogs.grade_defense_penalty),
  grade_pass = COALESCE(EXCLUDED.grade_pass, pff_player_gamelogs.grade_pass),
  grade_run = COALESCE(EXCLUDED.grade_run, pff_player_gamelogs.grade_run),
  grade_pass_block = COALESCE(EXCLUDED.grade_pass_block, pff_player_gamelogs.grade_pass_block),
  grade_run_block = COALESCE(EXCLUDED.grade_run_block, pff_player_gamelogs.grade_run_block),
  grade_pass_route = COALESCE(EXCLUDED.grade_pass_route, pff_player_gamelogs.grade_pass_route),
  grade_hands_drop = COALESCE(EXCLUDED.grade_hands_drop, pff_player_gamelogs.grade_hands_drop),
  grade_hands_fumble = COALESCE(EXCLUDED.grade_hands_fumble, pff_player_gamelogs.grade_hands_fumble),
  grade_coverage_defense = COALESCE(EXCLUDED.grade_coverage_defense, pff_player_gamelogs.grade_coverage_defense),
  grade_pass_rush_defense = COALESCE(EXCLUDED.grade_pass_rush_defense, pff_player_gamelogs.grade_pass_rush_defense),
  grade_run_defense = COALESCE(EXCLUDED.grade_run_defense, pff_player_gamelogs.grade_run_defense),
  grade_tackle = COALESCE(EXCLUDED.grade_tackle, pff_player_gamelogs.grade_tackle),
  grade_punter = COALESCE(EXCLUDED.grade_punter, pff_player_gamelogs.grade_punter),
  penalties = COALESCE(EXCLUDED.penalties, pff_player_gamelogs.penalties),
  declined_penalties = COALESCE(EXCLUDED.declined_penalties, pff_player_gamelogs.declined_penalties),
  routes = COALESCE(EXCLUDED.routes, pff_player_gamelogs.routes),
  yards_per_route_run = COALESCE(EXCLUDED.yards_per_route_run, pff_player_gamelogs.yards_per_route_run),
  scrambles = COALESCE(EXCLUDED.scrambles, pff_player_gamelogs.scrambles),
  punting_snaps = COALESCE(EXCLUDED.punting_snaps, pff_player_gamelogs.punting_snaps),
  punting_attempts = COALESCE(EXCLUDED.punting_attempts, pff_player_gamelogs.punting_attempts),
  punting_yards = COALESCE(EXCLUDED.punting_yards, pff_player_gamelogs.punting_yards),
  punting_blocks = COALESCE(EXCLUDED.punting_blocks, pff_player_gamelogs.punting_blocks),
  punting_touchbacks = COALESCE(EXCLUDED.punting_touchbacks, pff_player_gamelogs.punting_touchbacks),
  punting_inside_twenty_yard_line = COALESCE(EXCLUDED.punting_inside_twenty_yard_line, pff_player_gamelogs.punting_inside_twenty_yard_line),
  punting_downed = COALESCE(EXCLUDED.punting_downed, pff_player_gamelogs.punting_downed),
  punting_out_of_bounds = COALESCE(EXCLUDED.punting_out_of_bounds, pff_player_gamelogs.punting_out_of_bounds),
  punting_fair_catches = COALESCE(EXCLUDED.punting_fair_catches, pff_player_gamelogs.punting_fair_catches),
  punting_returns = COALESCE(EXCLUDED.punting_returns, pff_player_gamelogs.punting_returns),
  punting_return_yards = COALESCE(EXCLUDED.punting_return_yards, pff_player_gamelogs.punting_return_yards),
  punting_longest_punt = COALESCE(EXCLUDED.punting_longest_punt, pff_player_gamelogs.punting_longest_punt),
  punting_total_net_yards = COALESCE(EXCLUDED.punting_total_net_yards, pff_player_gamelogs.punting_total_net_yards),
  punting_average_net_yards = COALESCE(EXCLUDED.punting_average_net_yards, pff_player_gamelogs.punting_average_net_yards),
  punting_average_yards_per_attempt = COALESCE(EXCLUDED.punting_average_yards_per_attempt, pff_player_gamelogs.punting_average_yards_per_attempt),
  punting_average_yards_per_return = COALESCE(EXCLUDED.punting_average_yards_per_return, pff_player_gamelogs.punting_average_yards_per_return),
  punting_percentage_returned = COALESCE(EXCLUDED.punting_percentage_returned, pff_player_gamelogs.punting_percentage_returned),
  punting_attempts_with_hangtime = COALESCE(EXCLUDED.punting_attempts_with_hangtime, pff_player_gamelogs.punting_attempts_with_hangtime),
  punting_total_hangtime = COALESCE(EXCLUDED.punting_total_hangtime, pff_player_gamelogs.punting_total_hangtime),
  punting_average_hangtime = COALESCE(EXCLUDED.punting_average_hangtime, pff_player_gamelogs.punting_average_hangtime),
  nfl_team = COALESCE(pff_player_gamelogs.nfl_team, EXCLUDED.nfl_team),
  player_position = COALESCE(pff_player_gamelogs.player_position, EXCLUDED.player_position),
  updated_at = now();
ANALYZE public.pff_player_gamelogs;
