-- The audit trail for the sandboxed-SQL data-view tier: one row per statement
-- this server attempted to run, whether it executed or was refused.
--
-- STATUS: APPLIED 2026-08-28 against league_production
--
-- STANDALONE, deliberately. An earlier draft specified this as an extension of
-- the audit table that the LLM-assisted generation task builds. Generation runs
-- LAST in the chain (queue -> SQL -> query-backed -> generation), so an
-- extension of it is unbuildable here; this table records what EXECUTED, which
-- is a different fact from the agent's trajectory and is worth having on its
-- own.
--
-- A rejected statement gets a row too. The rejections are the interesting half:
-- they are the record of what the generation agent tried to run against the
-- sandbox, and a rejection class that spikes is either an attack or a guard that
-- is too strict.
--
-- No user_id foreign key. The referenced row can be deleted and an audit trail
-- that a deletion can rewrite is not one; the column records who ran it at the
-- time, nothing more.
--
-- ONE STEP AFTER THIS FILE, IN THE SAME COMMIT. Run `yarn export:schema`, and
-- add `data_view_sql_audit` to EXCLUDED_RELATIONS in
-- db/tools/generate-reader-role-grants.mjs with the reason
-- "the sandbox's own audit trail; a sandbox that can read back other users'
-- statements is not one". That generator grants every relation it is not told to
-- exclude, so this table becomes readable by the sandbox role the moment it
-- enters the schema dump and the grants are next regenerated. The exclusion
-- cannot be added earlier: the tool refuses an exclusion naming a relation the
-- schema does not have, so that a stale entry cannot sit there excluding
-- nothing.

CREATE TABLE public.data_view_sql_audit (
    audit_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id integer,
    -- 'executed' | 'rejected' | 'error'. 'rejected' is the parse-time guard
    -- refusing; 'error' is Postgres refusing at execution, which includes the
    -- statement_timeout cancellation and every privilege denial the GRANTs
    -- produce.
    outcome character varying(16) NOT NULL,
    -- The rejection code for 'rejected', the Postgres SQLSTATE and message for
    -- 'error', null for 'executed'.
    outcome_detail text,
    statement_text text NOT NULL,
    result_row_count integer,
    duration_milliseconds integer,
    CONSTRAINT data_view_sql_audit_pkey PRIMARY KEY (audit_id),
    CONSTRAINT data_view_sql_audit_outcome_check
      CHECK (outcome IN ('executed', 'rejected', 'error'))
);

CREATE INDEX idx_data_view_sql_audit_created_at
  ON public.data_view_sql_audit (created_at DESC);

CREATE INDEX idx_data_view_sql_audit_outcome
  ON public.data_view_sql_audit (outcome, created_at DESC);

-- The app writes this table as league_writer on the MAIN pool, never as
-- league_data_view_reader: the sandbox role holds SELECT grants only, and a
-- sandbox that can write its own audit trail is not one. league_writer owns
-- every object it creates, so it needs no GRANT here.
