-- STATUS: APPLIED 2026-09-03 against league_production
--
-- Conform NFL team abbreviations to the CURRENT franchise abbreviation, 2000
-- onward. Increment D of user:task/league/settle-nfl-games-team-abbreviation-matching.md.
--
-- The operator ruled on 2026-09-02 that the current franchise abbreviation is
-- canonical for every NFL team column. This file rewrites the era tokens the
-- database still holds (SD, STL, RAM, RAI, PHO, BOS, plus the BAL Colts and HOU
-- Oilers collision slots) to that form, for seasons 2000 and later.
--
-- WHAT THIS IS NOT: it is not the fix for the 575 unmatched nflverse games.
-- Those were closed by the matcher alone in league 4406d19f2, with no data
-- write. This file serves the convention.
--
-- ATOMICITY. nfl_games and the WHOLE nfl_plays team-column set conform in one
-- transaction -- not just possession_nfl_team. fixed-drive-enrichment.mjs
-- compares offense_nfl_team to touchdown_nfl_team to classify a defensive
-- touchdown, so a split between those two renumbers fixed_drive for an entire
-- game. db:exec supplies the transaction; do NOT add BEGIN/COMMIT.
--
-- ROLLBACK. Not invertible by map (STL and RAM both collapse to LA, as do SD
-- and LAC) and not invertible by season either, because a pre-existing
-- canonical bleed of 12-36 plays per season is indistinguishable from a
-- conformed row afterwards. So the backups below are the rollback mechanism.
-- nfl_plays, nfl_games, player_gamelogs and player get keyed snapshots;
-- nfl_play_stats gets a FULL PHYSICAL COPY, because idx_24719_play_stat is
-- unique only in Postgres's NULL-permissive sense (5,804,248 rows against
-- 5,308,119 distinct values, player_name NULL on 1,216,509) and cannot say
-- which sibling held which team.
--
-- NOT REWRITTEN, deliberately:
--   * changelog tables -- audit history of what a value WAS, correct as-is
--   * the 40 non-franchise slots (AFC, NFC, IRV, RIC, SAN, CRT, INA)
--   * four EMPTY-STRING slots (2 nfl_plays 2021, 2 player_gamelogs 2024). An
--     empty team is an absence wearing a value, a different defect with a
--     different repair. The conformance check keeps reporting them.
--   * seasons before 2000 -- a separate franchise-identity ruling, increment E
--
-- Generated by db/tools/generate-nfl-team-conform-sql.mjs from
-- libs-shared/nfl-team-franchise-eras.mjs.

SET lock_timeout = '30s';
SET statement_timeout = 0;

-- The franchise-era table and the vendor spelling aliases, GENERATED from
-- libs-shared/nfl-team-franchise-eras.mjs rather than transcribed, so this file
-- and the resolver every importer calls cannot disagree about a boundary year.
CREATE TEMP TABLE conform_era (
  era_nfl_team text NOT NULL,
  start_year int NOT NULL,
  end_year int,
  canonical_nfl_team text NOT NULL
) ON COMMIT DROP;

INSERT INTO conform_era VALUES
  ('STL', 1960, 1987, 'ARI'),
  ('PHO', 1988, 1993, 'ARI'),
  ('BAL', 1953, 1983, 'IND'),
  ('BAL', 1996, NULL::int, 'BAL'),
  ('HOU', 1960, 1996, 'TEN'),
  ('HOU', 2002, NULL::int, 'HOU'),
  ('RAM', 1980, 1994, 'LA'),
  ('STL', 1995, 2015, 'LA'),
  ('SD', 1961, 2016, 'LAC'),
  ('RAI', 1982, 1994, 'LV'),
  ('OAK', 1960, 2019, 'LV'),
  ('BOS', 1960, 1970, 'NE');

CREATE TEMP TABLE conform_alias (
  alias text NOT NULL,
  canonical_nfl_team text NOT NULL
) ON COMMIT DROP;

INSERT INTO conform_alias VALUES
  ('ARZ', 'ARI'),
  ('BLT', 'BAL'),
  ('CLV', 'CLE'),
  ('HST', 'HOU'),
  ('LAR', 'LA');

-- ---------------------------------------------------------------------------
-- Pre-flight. Every one of these must hold BEFORE anything is written.
-- ---------------------------------------------------------------------------

-- The conform must not create a duplicate on idx_24707_game
-- (away_nfl_team, home_nfl_team, week, season_year, season_type). Re-checked
-- here rather than trusted from the planning session, because rows land
-- continuously.

DO $$
DECLARE actual bigint;
BEGIN
  SELECT count(*) FROM (
    SELECT COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = g.away_nfl_team
            AND g.season_year >= e.start_year
            AND (e.end_year IS NULL OR g.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = g.away_nfl_team),
        g.away_nfl_team
      ) AS away_new,
           COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = g.home_nfl_team
            AND g.season_year >= e.start_year
            AND (e.end_year IS NULL OR g.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = g.home_nfl_team),
        g.home_nfl_team
      ) AS home_new,
           g.week, g.season_year, g.season_type
    FROM nfl_games g
    GROUP BY 1, 2, 3, 4, 5
    HAVING count(*) > 1
  ) collisions INTO actual;
  IF actual <> 0 THEN
    RAISE EXCEPTION 'PRE nfl_games idx_24707_game collisions after mapping: expected 0, found %', actual;
  END IF;
  RAISE NOTICE 'PRE nfl_games idx_24707_game collisions after mapping: % (as expected)', actual;
END $$;

-- ---------------------------------------------------------------------------
-- Backups. Inside the transaction on purpose: if this file aborts there is
-- nothing to restore, and if it commits the backups commit with it.
-- ---------------------------------------------------------------------------

CREATE TABLE nfl_games_preconform_20260902 AS
  SELECT esbid, season_year, week, season_type, away_nfl_team, home_nfl_team
  FROM nfl_games
  WHERE season_year >= 2000
    AND (COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = away_nfl_team
            AND season_year >= e.start_year
            AND (e.end_year IS NULL OR season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = away_nfl_team),
        away_nfl_team
      ) <> away_nfl_team
      OR COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = home_nfl_team
            AND season_year >= e.start_year
            AND (e.end_year IS NULL OR season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = home_nfl_team),
        home_nfl_team
      ) <> home_nfl_team);

CREATE TABLE nfl_plays_preconform_20260902 AS
  SELECT esbid, play_id, season_year, possession_nfl_team, offense_nfl_team, defense_nfl_team, yard_line_side, score_team, touchdown_nfl_team, return_nfl_team, penalty_team, timeout_team
  FROM nfl_plays p
  WHERE COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.possession_nfl_team
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.possession_nfl_team),
        p.possession_nfl_team
      ) IS DISTINCT FROM p.possession_nfl_team
     OR COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.offense_nfl_team
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.offense_nfl_team),
        p.offense_nfl_team
      ) IS DISTINCT FROM p.offense_nfl_team
     OR COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.defense_nfl_team
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.defense_nfl_team),
        p.defense_nfl_team
      ) IS DISTINCT FROM p.defense_nfl_team
     OR COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.yard_line_side
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.yard_line_side),
        p.yard_line_side
      ) IS DISTINCT FROM p.yard_line_side
     OR COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.score_team
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.score_team),
        p.score_team
      ) IS DISTINCT FROM p.score_team
     OR COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.touchdown_nfl_team
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.touchdown_nfl_team),
        p.touchdown_nfl_team
      ) IS DISTINCT FROM p.touchdown_nfl_team
     OR COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.return_nfl_team
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.return_nfl_team),
        p.return_nfl_team
      ) IS DISTINCT FROM p.return_nfl_team
     OR COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.penalty_team
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.penalty_team),
        p.penalty_team
      ) IS DISTINCT FROM p.penalty_team
     OR COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.timeout_team
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.timeout_team),
        p.timeout_team
      ) IS DISTINCT FROM p.timeout_team;

CREATE TABLE player_gamelogs_preconform_20260902 AS
  SELECT esbid, pid, season_year, nfl_team, opponent_nfl_team
  FROM player_gamelogs pg
  WHERE COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = pg.nfl_team
            AND pg.season_year >= e.start_year
            AND (e.end_year IS NULL OR pg.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = pg.nfl_team),
        pg.nfl_team
      ) IS DISTINCT FROM pg.nfl_team
     OR COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = pg.opponent_nfl_team
            AND pg.season_year >= e.start_year
            AND (e.end_year IS NULL OR pg.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = pg.opponent_nfl_team),
        pg.opponent_nfl_team
      ) IS DISTINCT FROM pg.opponent_nfl_team;

CREATE TABLE player_preconform_20260902 AS
  SELECT pid, nfl_draft_year, draft_team
  FROM player p
  WHERE p.nfl_draft_year >= 2000
    AND COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.draft_team
            AND p.nfl_draft_year >= e.start_year
            AND (e.end_year IS NULL OR p.nfl_draft_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.draft_team),
        p.draft_team
      ) IS DISTINCT FROM p.draft_team;

-- Full physical copy: this table has no usable row handle, so a keyed snapshot
-- cannot restore it. 1336 MB against 183 GB free.
CREATE TABLE nfl_play_stats_preconform_20260902 AS SELECT * FROM nfl_play_stats;

-- ---------------------------------------------------------------------------
-- The conform.
-- ---------------------------------------------------------------------------

UPDATE nfl_games g
SET away_nfl_team = COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = g.away_nfl_team
            AND g.season_year >= e.start_year
            AND (e.end_year IS NULL OR g.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = g.away_nfl_team),
        g.away_nfl_team
      ),
    home_nfl_team = COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = g.home_nfl_team
            AND g.season_year >= e.start_year
            AND (e.end_year IS NULL OR g.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = g.home_nfl_team),
        g.home_nfl_team
      )
WHERE g.season_year >= 2000
  AND (COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = g.away_nfl_team
            AND g.season_year >= e.start_year
            AND (e.end_year IS NULL OR g.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = g.away_nfl_team),
        g.away_nfl_team
      ) <> g.away_nfl_team
    OR COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = g.home_nfl_team
            AND g.season_year >= e.start_year
            AND (e.end_year IS NULL OR g.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = g.home_nfl_team),
        g.home_nfl_team
      ) <> g.home_nfl_team);

UPDATE nfl_plays p
SET possession_nfl_team = COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.possession_nfl_team
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.possession_nfl_team),
        p.possession_nfl_team
      ),
    offense_nfl_team = COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.offense_nfl_team
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.offense_nfl_team),
        p.offense_nfl_team
      ),
    defense_nfl_team = COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.defense_nfl_team
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.defense_nfl_team),
        p.defense_nfl_team
      ),
    yard_line_side = COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.yard_line_side
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.yard_line_side),
        p.yard_line_side
      ),
    score_team = COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.score_team
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.score_team),
        p.score_team
      ),
    touchdown_nfl_team = COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.touchdown_nfl_team
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.touchdown_nfl_team),
        p.touchdown_nfl_team
      ),
    return_nfl_team = COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.return_nfl_team
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.return_nfl_team),
        p.return_nfl_team
      ),
    penalty_team = COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.penalty_team
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.penalty_team),
        p.penalty_team
      ),
    timeout_team = COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.timeout_team
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.timeout_team),
        p.timeout_team
      )
WHERE COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.possession_nfl_team
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.possession_nfl_team),
        p.possession_nfl_team
      ) IS DISTINCT FROM p.possession_nfl_team
   OR COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.offense_nfl_team
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.offense_nfl_team),
        p.offense_nfl_team
      ) IS DISTINCT FROM p.offense_nfl_team
   OR COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.defense_nfl_team
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.defense_nfl_team),
        p.defense_nfl_team
      ) IS DISTINCT FROM p.defense_nfl_team
   OR COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.yard_line_side
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.yard_line_side),
        p.yard_line_side
      ) IS DISTINCT FROM p.yard_line_side
   OR COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.score_team
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.score_team),
        p.score_team
      ) IS DISTINCT FROM p.score_team
   OR COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.touchdown_nfl_team
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.touchdown_nfl_team),
        p.touchdown_nfl_team
      ) IS DISTINCT FROM p.touchdown_nfl_team
   OR COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.return_nfl_team
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.return_nfl_team),
        p.return_nfl_team
      ) IS DISTINCT FROM p.return_nfl_team
   OR COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.penalty_team
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.penalty_team),
        p.penalty_team
      ) IS DISTINCT FROM p.penalty_team
   OR COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.timeout_team
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.timeout_team),
        p.timeout_team
      ) IS DISTINCT FROM p.timeout_team;

UPDATE nfl_play_stats ps
SET nfl_team = COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = ps.nfl_team
            AND g.season_year >= e.start_year
            AND (e.end_year IS NULL OR g.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = ps.nfl_team),
        ps.nfl_team
      )
FROM nfl_games g
WHERE g.esbid = ps.esbid
  AND COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = ps.nfl_team
            AND g.season_year >= e.start_year
            AND (e.end_year IS NULL OR g.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = ps.nfl_team),
        ps.nfl_team
      ) IS DISTINCT FROM ps.nfl_team;

UPDATE player_gamelogs pg
SET nfl_team = COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = pg.nfl_team
            AND pg.season_year >= e.start_year
            AND (e.end_year IS NULL OR pg.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = pg.nfl_team),
        pg.nfl_team
      ),
    opponent_nfl_team = COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = pg.opponent_nfl_team
            AND pg.season_year >= e.start_year
            AND (e.end_year IS NULL OR pg.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = pg.opponent_nfl_team),
        pg.opponent_nfl_team
      )
WHERE COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = pg.nfl_team
            AND pg.season_year >= e.start_year
            AND (e.end_year IS NULL OR pg.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = pg.nfl_team),
        pg.nfl_team
      ) IS DISTINCT FROM pg.nfl_team
   OR COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = pg.opponent_nfl_team
            AND pg.season_year >= e.start_year
            AND (e.end_year IS NULL OR pg.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = pg.opponent_nfl_team),
        pg.opponent_nfl_team
      ) IS DISTINCT FROM pg.opponent_nfl_team;

UPDATE player p
SET draft_team = COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.draft_team
            AND p.nfl_draft_year >= e.start_year
            AND (e.end_year IS NULL OR p.nfl_draft_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.draft_team),
        p.draft_team
      )
WHERE p.nfl_draft_year >= 2000
  AND COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.draft_team
            AND p.nfl_draft_year >= e.start_year
            AND (e.end_year IS NULL OR p.nfl_draft_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.draft_team),
        p.draft_team
      ) IS DISTINCT FROM p.draft_team;

-- ---------------------------------------------------------------------------
-- Post-conditions. An UPDATE matching zero rows is a SUCCESS, so these assert
-- the PROPERTY rather than trusting a clean exit.
-- ---------------------------------------------------------------------------

-- Every backup holds the rows it was supposed to capture.

DO $$
DECLARE actual bigint;
BEGIN
  SELECT count(*) FROM nfl_games_preconform_20260902 INTO actual;
  IF actual <> 668 THEN
    RAISE EXCEPTION 'POST nfl_games backup rows: expected 668, found %', actual;
  END IF;
  RAISE NOTICE 'POST nfl_games backup rows: % (as expected)', actual;
END $$;

DO $$
DECLARE actual bigint;
BEGIN
  SELECT count(*) FROM nfl_plays_preconform_20260902 INTO actual;
  IF actual <> 83126 THEN
    RAISE EXCEPTION 'POST nfl_plays backup rows: expected 83126, found %', actual;
  END IF;
  RAISE NOTICE 'POST nfl_plays backup rows: % (as expected)', actual;
END $$;

DO $$
DECLARE actual bigint;
BEGIN
  SELECT count(*) FROM player_gamelogs_preconform_20260902 INTO actual;
  IF actual <> 286 THEN
    RAISE EXCEPTION 'POST player_gamelogs backup rows: expected 286, found %', actual;
  END IF;
  RAISE NOTICE 'POST player_gamelogs backup rows: % (as expected)', actual;
END $$;

DO $$
DECLARE actual bigint;
BEGIN
  SELECT count(*) FROM player_preconform_20260902 INTO actual;
  IF actual <> 4 THEN
    RAISE EXCEPTION 'POST player backup rows: expected 4, found %', actual;
  END IF;
  RAISE NOTICE 'POST player backup rows: % (as expected)', actual;
END $$;

DO $$
DECLARE actual bigint;
BEGIN
  SELECT count(*) FROM nfl_play_stats_preconform_20260902 INTO actual;
  IF actual <> 5804248 THEN
    RAISE EXCEPTION 'POST nfl_play_stats physical backup rows: expected 5804248, found %', actual;
  END IF;
  RAISE NOTICE 'POST nfl_play_stats physical backup rows: % (as expected)', actual;
END $$;

-- ZERO residual era tokens from 2000 onward, asked through the same
-- season-first predicate the registered check uses.

DO $$
DECLARE actual bigint;
BEGIN
  SELECT count(*) FROM (
    SELECT 1 FROM nfl_games g WHERE g.season_year >= 2000
      AND (COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = g.away_nfl_team
            AND g.season_year >= e.start_year
            AND (e.end_year IS NULL OR g.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = g.away_nfl_team),
        g.away_nfl_team
      ) <> g.away_nfl_team
        OR COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = g.home_nfl_team
            AND g.season_year >= e.start_year
            AND (e.end_year IS NULL OR g.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = g.home_nfl_team),
        g.home_nfl_team
      ) <> g.home_nfl_team)
    UNION ALL
    SELECT 1 FROM nfl_plays p WHERE COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.possession_nfl_team
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.possession_nfl_team),
        p.possession_nfl_team
      ) IS DISTINCT FROM p.possession_nfl_team
      OR COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.offense_nfl_team
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.offense_nfl_team),
        p.offense_nfl_team
      ) IS DISTINCT FROM p.offense_nfl_team
      OR COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.defense_nfl_team
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.defense_nfl_team),
        p.defense_nfl_team
      ) IS DISTINCT FROM p.defense_nfl_team
      OR COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.yard_line_side
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.yard_line_side),
        p.yard_line_side
      ) IS DISTINCT FROM p.yard_line_side
      OR COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.score_team
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.score_team),
        p.score_team
      ) IS DISTINCT FROM p.score_team
      OR COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.touchdown_nfl_team
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.touchdown_nfl_team),
        p.touchdown_nfl_team
      ) IS DISTINCT FROM p.touchdown_nfl_team
      OR COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.return_nfl_team
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.return_nfl_team),
        p.return_nfl_team
      ) IS DISTINCT FROM p.return_nfl_team
      OR COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.penalty_team
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.penalty_team),
        p.penalty_team
      ) IS DISTINCT FROM p.penalty_team
      OR COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.timeout_team
            AND p.season_year >= e.start_year
            AND (e.end_year IS NULL OR p.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.timeout_team),
        p.timeout_team
      ) IS DISTINCT FROM p.timeout_team
    UNION ALL
    SELECT 1 FROM player_gamelogs pg
      WHERE COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = pg.nfl_team
            AND pg.season_year >= e.start_year
            AND (e.end_year IS NULL OR pg.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = pg.nfl_team),
        pg.nfl_team
      ) IS DISTINCT FROM pg.nfl_team
         OR COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = pg.opponent_nfl_team
            AND pg.season_year >= e.start_year
            AND (e.end_year IS NULL OR pg.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = pg.opponent_nfl_team),
        pg.opponent_nfl_team
      ) IS DISTINCT FROM pg.opponent_nfl_team
    UNION ALL
    SELECT 1 FROM nfl_play_stats ps JOIN nfl_games g ON g.esbid = ps.esbid
      WHERE COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = ps.nfl_team
            AND g.season_year >= e.start_year
            AND (e.end_year IS NULL OR g.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = ps.nfl_team),
        ps.nfl_team
      ) IS DISTINCT FROM ps.nfl_team
    UNION ALL
    SELECT 1 FROM player p WHERE p.nfl_draft_year >= 2000
      AND COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.draft_team
            AND p.nfl_draft_year >= e.start_year
            AND (e.end_year IS NULL OR p.nfl_draft_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.draft_team),
        p.draft_team
      ) IS DISTINCT FROM p.draft_team
  ) residual INTO actual;
  IF actual <> 0 THEN
    RAISE EXCEPTION 'POST residual non-conforming slots, 2000 onward: expected 0, found %', actual;
  END IF;
  RAISE NOTICE 'POST residual non-conforming slots, 2000 onward: % (as expected)', actual;
END $$;

-- A relabel MOVES no rows. These are the population-level reconciliation that
-- is independent of the mapper: if any of them changed, something other than a
-- team abbreviation was rewritten.

DO $$
DECLARE actual bigint;
BEGIN
  SELECT count(*) FROM nfl_games INTO actual;
  IF actual <> 15622 THEN
    RAISE EXCEPTION 'POST nfl_games row count unchanged: expected 15622, found %', actual;
  END IF;
  RAISE NOTICE 'POST nfl_games row count unchanged: % (as expected)', actual;
END $$;

DO $$
DECLARE actual bigint;
BEGIN
  SELECT count(*) FROM nfl_play_stats INTO actual;
  IF actual <> 5804248 THEN
    RAISE EXCEPTION 'POST nfl_play_stats row count unchanged: expected 5804248, found %', actual;
  END IF;
  RAISE NOTICE 'POST nfl_play_stats row count unchanged: % (as expected)', actual;
END $$;

DO $$
DECLARE actual bigint;
BEGIN
  SELECT count(*) FROM (
    SELECT away_nfl_team AS t FROM nfl_games
    UNION ALL SELECT home_nfl_team FROM nfl_games
  ) s WHERE s.t IN ('AFC','NFC','IRV','RIC','SAN','CRT','INA') INTO actual;
  IF actual <> 40 THEN
    RAISE EXCEPTION 'POST non-franchise slots still 40: expected 40, found %', actual;
  END IF;
  RAISE NOTICE 'POST non-franchise slots still 40: % (as expected)', actual;
END $$;
