-- STATUS: APPLIED 2026-09-01 against league_production
--
-- Set market_type on 23,046 CAESARS rows in prop_markets_index that the
-- currently deployed mapper already knows how to type, across 55 templates.
-- These rows were written by older importer builds, before the corresponding
-- case existed in private/libs-server/caesars.mjs. No code changes; this is the
-- mapper applied to names already stored.
--
-- WHY THE MAPPING IS MATERIALIZED HERE rather than replayed by a script calling
-- get_market_type. The mapper lives in the private submodule, which reaches
-- production only by push and checkout update, and league pushes are currently
-- held. Materializing the 55 pairs removes that coupling entirely and makes the
-- file say exactly which template became which type, which a script deleted
-- after its run does not. The pairs were GENERATED by calling the deployed
-- get_market_type on every distinct stored template, never hand-typed.
--
-- THE TEMPLATE MUST BE WRAPPED IN PIPES BEFORE THE MAPPER SEES IT, and this is
-- the trap that makes a naive backfill silently type nothing. source_market_name
-- is built as `${event} - ${market} — ${template} — ${category}` and the importer
-- stores templateName.replaceAll('|',''), so the pipes are STRIPPED. The mapper's
-- switch cases are not: they read case '|Match Spread|'. Passing the stored
-- segment verbatim matches no case at all.
--
--   get_market_type({ template_name: 'Match Spread' })    -> null
--   get_market_type({ template_name: '|Match Spread|' })  -> GAME_SPREAD
--
-- Measured, not assumed: over all 814 distinct stored templates in the untyped
-- population, the bare form types 0 rows and the pipe-wrapped form types 23,046.
--
-- THERE IS NO market_category FALL-THROUGH. The template switch's `default`
-- returns null INSIDE the `if (template_name)` block, so a template that misses
-- returns null outright; only a FALSY template reaches the category branch. The
-- third segment is therefore irrelevant here, and the non-empty-template filter
-- below matters for a narrower reason -- an empty template is falsy and would
-- take the category branch with a category this file does not supply.
--
-- TWO INDEPENDENT DERIVATIONS AGREE, which is the point, because the obvious
-- pair of checks both call the same function and agree by construction:
--
--   1. Calling the deployed get_market_type on each of the 814 distinct stored
--      templates: 55 map, covering 23,046 rows.
--   2. Extracting the pipe-quoted `case` labels from the mapper's SOURCE TEXT --
--      67 of them -- and joining that list against the stored template census in
--      SQL, touching no JavaScript: 55 match, covering 23,046 rows. The other 12
--      labels have no untyped rows left.
--
-- LIVE MARKETS FALL OUT BY CONSTRUCTION, and are not this file's business. The
-- switch is exact-match, so a template carrying a trailing ' Live' hits no case
-- and stays null. None of the 55 pairs below ends in ' Live'. Typing the live
-- family needs consumer-side is_live predicates first, or mid-game prices
-- contaminate pregame hit-rate and closing-line populations; that is a separate
-- decision and a separate change.
--
-- THIS WRITE IS NOT DURABLE AGAINST A RE-OBSERVATION, and it is important to say
-- so rather than imply otherwise. market_type is in MARKET_INDEX_MERGE_COLUMNS in
-- libs-server/insert-prop-markets.mjs, and build_market_index_merge maps every
-- such column to excluded.<column>, so an incoming import value wins
-- unconditionally on conflict. A still-observed market re-typed here would revert
-- on the next importer run against an un-updated mapper.
--
-- It holds for THIS population only because the population is historical: the
-- affected markets span the 2023 to 2025 seasons and were last observed
-- 2026-01-11, and it is now the 2026 preseason. That is a property of the rows,
-- not a protection. The durable fix is to add the missing cases to the mapper so
-- the importer types these templates at write time, which is the next increment
-- of user:task/league/close-caesars-market-type-coverage.md.
--
-- WHAT THIS MAKES VISIBLE. market_type is what settlement, the data-view betting
-- columns and historical hit-rate calculation all key on, and a null type is
-- excluded by every one of them. 22,553 of the 23,046 rows -- 97.9 percent --
-- already carry an esbid and so become fully readable immediately. That fraction
-- was 76 percent until earlier today, when
-- db/adhoc/2026-09-01-stamp-caesars-esbid-across-the-match-gap.sql resolved the
-- thirteen-month esbid gap; the two files were applied in separate windows
-- precisely so neither falsifies the other's before-and-after census.
--
-- The Caesars null_type count falls from 152,000 to 128,954. No other source is
-- touched. A large residue stays untyped by decision and this file does not
-- pretend to close it.

DO $$
DECLARE
  caesars_null_type integer;
  other_sources_null_type integer;
BEGIN
  SELECT count(*) FILTER (WHERE source_id = 'CAESARS' AND market_type IS NULL),
         count(*) FILTER (WHERE source_id <> 'CAESARS' AND market_type IS NULL)
    INTO caesars_null_type, other_sources_null_type
    FROM public.prop_markets_index;

  IF caesars_null_type <> 152000 THEN
    RAISE EXCEPTION
      'expected 152000 untyped CAESARS rows, found %; the population moved and the counts below are about a different one, rolling back',
      caesars_null_type;
  END IF;

  IF other_sources_null_type <> 1839491 THEN
    RAISE EXCEPTION
      'expected 1839491 untyped rows across the other sources, found %; rolling back',
      other_sources_null_type;
  END IF;
END $$;

DO $$
DECLARE
  updated integer;
BEGIN
  WITH template_market_type (template, market_type) AS (
    VALUES
      ('Player Total Tackles + Assists', 'GAME_TACKLES_ASSISTS'),
      ('Player Total Rushing Yards', 'GAME_RUSHING_YARDS'),
      ('Player Total Receiving Yards', 'GAME_RECEIVING_YARDS'),
      ('Player Total Receptions', 'GAME_RECEPTIONS'),
      ('Player Longest Reception', 'GAME_LONGEST_RECEPTION'),
      ('Alt Receiving Yards', 'GAME_ALT_RECEIVING_YARDS'),
      ('Player Total Rushing + Receiving Yards', 'GAME_RUSHING_RECEIVING_YARDS'),
      ('1st Half Spread', 'GAME_FIRST_HALF_SPREAD'),
      ('Alt Rushing Yards', 'GAME_ALT_RUSHING_YARDS'),
      ('Player Total Rushing Attempts', 'GAME_RUSHING_ATTEMPTS'),
      ('Will There Be Overtime?', 'GAME_OVERTIME'),
      ('Highest Scoring Quarter', 'GAME_HIGHEST_SCORING_QUARTER'),
      ('Total Home Points', 'GAME_TEAM_TOTAL'),
      ('1st Scoring Play', 'GAME_FIRST_SCORING_PLAY_TYPE'),
      ('Double Result', 'GAME_HALF_TIME_FULL_TIME'),
      ('Total Away Points', 'GAME_TEAM_TOTAL'),
      ('Winning Margins', 'GAME_WINNING_MARGIN'),
      ('Total Points Odd/Even', 'GAME_TOTAL_POINTS_ODD_EVEN'),
      ('Winning Margin', 'GAME_WINNING_MARGIN'),
      ('Team Total Points', 'GAME_TEAM_TOTAL'),
      ('Total Points', 'GAME_TOTAL'),
      ('Match Spread', 'GAME_SPREAD'),
      ('Money Line', 'GAME_MONEYLINE'),
      ('Player Total Passing Completions', 'GAME_PASSING_COMPLETIONS'),
      ('Player Total Passing Yards', 'GAME_PASSING_YARDS'),
      ('Player Longest Passing Completion', 'GAME_PASSING_LONGEST_COMPLETION'),
      ('Player Total Interceptions', 'GAME_PASSING_INTERCEPTIONS'),
      ('Player Total Passing Touchdowns', 'GAME_PASSING_TOUCHDOWNS'),
      ('Player Total Passing Attempts', 'GAME_PASSING_ATTEMPTS'),
      ('Alt Passing Touchdowns', 'GAME_ALT_PASSING_TOUCHDOWNS'),
      ('Alt Receptions', 'GAME_ALT_RECEPTIONS'),
      ('Alt Receiving Touchdowns', 'GAME_ALT_RECEIVING_TOUCHDOWNS'),
      ('Alt Passing Yards', 'GAME_ALT_PASSING_YARDS'),
      ('Total Regular Season Receiving Yards', 'SEASON_RECEIVING_YARDS'),
      ('Total Regular Season Receiving Touchdowns', 'SEASON_RECEIVING_TOUCHDOWNS'),
      ('Alt Rushing Attempts', 'GAME_ALT_RUSHING_ATTEMPTS'),
      ('Total Regular Season Rushing Yards', 'SEASON_RUSHING_YARDS'),
      ('Total Regular Season Rushing Touchdowns', 'SEASON_RUSHING_TOUCHDOWNS'),
      ('First Touchdown Scorer', 'GAME_FIRST_TOUCHDOWN_SCORER'),
      ('Last Touchdown Scorer', 'GAME_LAST_TOUCHDOWN_SCORER'),
      ('Anytime Touchdown Scorer', 'ANYTIME_TOUCHDOWN'),
      ('Alt Longest Rush', 'GAME_ALT_LONGEST_RUSH'),
      ('Alt Rushing Touchdowns', 'GAME_ALT_RUSHING_TOUCHDOWNS'),
      ('Total Regular Season Sacks', 'SEASON_DEFENSE_SACKS'),
      ('Total Regular Season Passing Yards', 'SEASON_PASSING_YARDS'),
      ('Total Regular Season Touchdown Passes', 'SEASON_PASSING_TOUCHDOWNS'),
      ('Alt Longest Completion', 'GAME_ALT_PASSING_LONGEST_COMPLETION'),
      ('Alt Passing Completions', 'GAME_ALT_PASSING_COMPLETIONS'),
      ('Alt Passing Attempts', 'GAME_ALT_PASSING_ATTEMPTS'),
      ('Most Regular Season Passing Yards', 'SEASON_LEADER_PASSING_YARDS'),
      ('Highest Scoring Half', 'GAME_HIGHEST_SCORING_HALF'),
      ('Most Regular Season Receiving Yards', 'SEASON_LEADER_RECEIVING_YARDS'),
      ('Most Regular Season Rushing Touchdowns', 'SEASON_LEADER_RUSHING_TOUCHDOWNS'),
      ('Most Regular Season Rushing Yards', 'SEASON_LEADER_RUSHING_YARDS'),
      ('Most Regular Season Passing Touchdowns', 'SEASON_LEADER_PASSING_TOUCHDOWNS')
  )
  UPDATE public.prop_markets_index m
     SET market_type = t.market_type
    FROM template_market_type t
   WHERE m.source_id = 'CAESARS'
     AND m.market_type IS NULL
     AND split_part(m.source_market_name, ' — ', 2) = t.template;

  GET DIAGNOSTICS updated = ROW_COUNT;

  IF updated <> 23046 THEN
    RAISE EXCEPTION 'expected to type 23046 rows, typed %; rolling back', updated;
  END IF;

  RAISE NOTICE 'typed % CAESARS rows across 55 templates', updated;
END $$;

-- Post-conditions, inside the same transaction.
DO $$
DECLARE
  caesars_null_type integer;
  other_sources_null_type integer;
  live_typed integer;
BEGIN
  SELECT count(*) FILTER (WHERE source_id = 'CAESARS' AND market_type IS NULL),
         count(*) FILTER (WHERE source_id <> 'CAESARS' AND market_type IS NULL)
    INTO caesars_null_type, other_sources_null_type
    FROM public.prop_markets_index;

  IF caesars_null_type <> 128954 THEN
    RAISE EXCEPTION
      'expected 128954 untyped CAESARS rows after typing, found %; rolling back', caesars_null_type;
  END IF;

  -- A per-source check, not just a Caesars one: a total that fell while another
  -- source rose would read as success on a single number.
  IF other_sources_null_type <> 1839491 THEN
    RAISE EXCEPTION
      'another source''s untyped count moved (% vs 1839491); rolling back', other_sources_null_type;
  END IF;

  -- Nothing carrying a trailing ' Live' may have acquired a type here. The
  -- exact-match switch guarantees it; this asserts it rather than trusting it,
  -- because a live row winning the observed_at dedup is how a mid-game price
  -- displaces a pregame one in a data-view cell.
  SELECT count(*)
    INTO live_typed
    FROM public.prop_markets_index
   WHERE source_id = 'CAESARS'
     AND market_type IS NOT NULL
     AND split_part(source_market_name, ' — ', 2) LIKE '% Live';

  IF live_typed <> 0 THEN
    RAISE EXCEPTION
      '% live-suffixed templates carry a market_type; rolling back', live_typed;
  END IF;

  RAISE NOTICE 'CAESARS untyped now %, live-suffixed typed rows %', caesars_null_type, live_typed;
END $$;
