-- STATUS: PENDING
--
-- Deletes the recruiting round's candidate responses. RUN THIS WHEN THE ROUND
-- CLOSES -- it is deliberately committed unapplied, alongside the migration
-- that creates the table, so the retention promise is a prepared step someone
-- can execute rather than a sentence in a plan.
--
-- The round closes when the Article IV waiting-list vote has seated a manager
-- and no second round is planned. Everything the league needs after that lives
-- in the vote's outcome, not in the submissions: a seated manager becomes a
-- user and a team owner, and an unseated candidate has no further relationship
-- with the league and did not consent to one.
--
-- The table itself is kept. A second round reuses it, and dropping it would
-- mean re-running the migration, the fixture-reset entry and the schema export
-- for no gain.
--
-- Deliberately unconditional. A `WHERE submitted_at < ...` predicate would
-- invite running this while a round is live and silently keeping the newest
-- rows; the whole point is that after the vote there is nothing here to retain.

DELETE FROM public.manager_waitlist_submissions;
