-- STATUS: APPLIED 2026-09-03 against league_production
--
-- Conform NFL team abbreviations to the CURRENT franchise abbreviation, before
-- 2000. Increment E of user:task/league/settle-nfl-games-team-abbreviation-matching.md.
--
-- THIS IS A FRANCHISE-IDENTITY RULING, NOT A MATCHING FIX, and it carried its
-- own operator gate separate from increment D. It relabels the 1975 Colts as
-- IND, the 1980 Oilers as TEN and the 1975 Cardinals as ARI, destroying a
-- historical label the system does not currently render. Approving the
-- abbreviation convention was NOT the same as approving this.
--
-- It is also the one part of this work with no live consumer: nfl_plays,
-- player_gamelogs and nfl_play_stats all begin at season 2000, so no pre-2000
-- row is joined by anything. Only nfl_games and player.draft_team are touched,
-- and there is no atomicity coupling -- no plays exist before 2000.
--
-- Generated by db/tools/generate-nfl-team-conform-sql.mjs from
-- libs-shared/nfl-team-franchise-eras.mjs.

SET lock_timeout = '30s';
SET statement_timeout = 0;

-- The franchise-era table and the vendor spelling aliases, GENERATED from
-- libs-shared/nfl-team-franchise-eras.mjs rather than transcribed, so this file
-- and the resolver every importer calls cannot disagree about a boundary year.
CREATE TEMP TABLE conform_era (
  era_nfl_team text NOT NULL,
  start_year int NOT NULL,
  end_year int,
  canonical_nfl_team text NOT NULL
) ON COMMIT DROP;

INSERT INTO conform_era VALUES
  ('STL', 1960, 1987, 'ARI'),
  ('PHO', 1988, 1993, 'ARI'),
  ('BAL', 1953, 1983, 'IND'),
  ('BAL', 1996, NULL::int, 'BAL'),
  ('HOU', 1960, 1996, 'TEN'),
  ('HOU', 2002, NULL::int, 'HOU'),
  ('RAM', 1980, 1994, 'LA'),
  ('STL', 1995, 2015, 'LA'),
  ('SD', 1961, 2016, 'LAC'),
  ('RAI', 1982, 1994, 'LV'),
  ('OAK', 1960, 2019, 'LV'),
  ('BOS', 1960, 1970, 'NE');

CREATE TEMP TABLE conform_alias (
  alias text NOT NULL,
  canonical_nfl_team text NOT NULL
) ON COMMIT DROP;

INSERT INTO conform_alias VALUES
  ('ARZ', 'ARI'),
  ('BLT', 'BAL'),
  ('CLV', 'CLE'),
  ('HST', 'HOU'),
  ('LAR', 'LA');


DO $$
DECLARE actual bigint;
BEGIN
  SELECT count(*) FROM (
    SELECT COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = g.away_nfl_team
            AND g.season_year >= e.start_year
            AND (e.end_year IS NULL OR g.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = g.away_nfl_team),
        g.away_nfl_team
      ) AS away_new,
           COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = g.home_nfl_team
            AND g.season_year >= e.start_year
            AND (e.end_year IS NULL OR g.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = g.home_nfl_team),
        g.home_nfl_team
      ) AS home_new,
           g.week, g.season_year, g.season_type
    FROM nfl_games g
    GROUP BY 1, 2, 3, 4, 5
    HAVING count(*) > 1
  ) collisions INTO actual;
  IF actual <> 0 THEN
    RAISE EXCEPTION 'PRE nfl_games idx_24707_game collisions after mapping: expected 0, found %', actual;
  END IF;
  RAISE NOTICE 'PRE nfl_games idx_24707_game collisions after mapping: % (as expected)', actual;
END $$;

CREATE TABLE nfl_games_preconform_pre2000_20260902 AS
  SELECT esbid, season_year, week, season_type, away_nfl_team, home_nfl_team
  FROM nfl_games
  WHERE season_year < 2000
    AND (COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = away_nfl_team
            AND season_year >= e.start_year
            AND (e.end_year IS NULL OR season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = away_nfl_team),
        away_nfl_team
      ) <> away_nfl_team
      OR COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = home_nfl_team
            AND season_year >= e.start_year
            AND (e.end_year IS NULL OR season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = home_nfl_team),
        home_nfl_team
      ) <> home_nfl_team);

CREATE TABLE player_preconform_pre2000_20260902 AS
  SELECT pid, nfl_draft_year, draft_team
  FROM player p
  WHERE p.nfl_draft_year < 2000
    AND COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.draft_team
            AND p.nfl_draft_year >= e.start_year
            AND (e.end_year IS NULL OR p.nfl_draft_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.draft_team),
        p.draft_team
      ) IS DISTINCT FROM p.draft_team;

UPDATE nfl_games g
SET away_nfl_team = COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = g.away_nfl_team
            AND g.season_year >= e.start_year
            AND (e.end_year IS NULL OR g.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = g.away_nfl_team),
        g.away_nfl_team
      ),
    home_nfl_team = COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = g.home_nfl_team
            AND g.season_year >= e.start_year
            AND (e.end_year IS NULL OR g.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = g.home_nfl_team),
        g.home_nfl_team
      )
WHERE g.season_year < 2000
  AND (COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = g.away_nfl_team
            AND g.season_year >= e.start_year
            AND (e.end_year IS NULL OR g.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = g.away_nfl_team),
        g.away_nfl_team
      ) <> g.away_nfl_team
    OR COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = g.home_nfl_team
            AND g.season_year >= e.start_year
            AND (e.end_year IS NULL OR g.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = g.home_nfl_team),
        g.home_nfl_team
      ) <> g.home_nfl_team);

UPDATE player p
SET draft_team = COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.draft_team
            AND p.nfl_draft_year >= e.start_year
            AND (e.end_year IS NULL OR p.nfl_draft_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.draft_team),
        p.draft_team
      )
WHERE p.nfl_draft_year < 2000
  AND COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.draft_team
            AND p.nfl_draft_year >= e.start_year
            AND (e.end_year IS NULL OR p.nfl_draft_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.draft_team),
        p.draft_team
      ) IS DISTINCT FROM p.draft_team;


DO $$
DECLARE actual bigint;
BEGIN
  SELECT count(*) FROM nfl_games_preconform_pre2000_20260902 INTO actual;
  IF actual <> 1885 THEN
    RAISE EXCEPTION 'POST nfl_games pre-2000 backup rows: expected 1885, found %', actual;
  END IF;
  RAISE NOTICE 'POST nfl_games pre-2000 backup rows: % (as expected)', actual;
END $$;

DO $$
DECLARE actual bigint;
BEGIN
  SELECT count(*) FROM player_preconform_pre2000_20260902 INTO actual;
  IF actual <> 1 THEN
    RAISE EXCEPTION 'POST player pre-2000 backup rows: expected 1, found %', actual;
  END IF;
  RAISE NOTICE 'POST player pre-2000 backup rows: % (as expected)', actual;
END $$;
-- SCOPED TO PRE-2000, which is what this file is responsible for. An earlier
-- revision asserted zero residual across ALL seasons and the dry run failed it
-- at 672 -- the 668 nfl_games and 4 player rows increment D owns. That reading
-- was correct: a file must assert its own effect, not one that depends on a
-- sibling having been applied first, or it passes and fails on run ORDER
-- rather than on whether it worked.

DO $$
DECLARE actual bigint;
BEGIN
  SELECT count(*) FROM (
    SELECT 1 FROM nfl_games g WHERE g.season_year < 2000
      AND (COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = g.away_nfl_team
            AND g.season_year >= e.start_year
            AND (e.end_year IS NULL OR g.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = g.away_nfl_team),
        g.away_nfl_team
      ) <> g.away_nfl_team
        OR COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = g.home_nfl_team
            AND g.season_year >= e.start_year
            AND (e.end_year IS NULL OR g.season_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = g.home_nfl_team),
        g.home_nfl_team
      ) <> g.home_nfl_team)
    UNION ALL
    SELECT 1 FROM player p WHERE p.nfl_draft_year < 2000
      AND COALESCE(
        (SELECT e.canonical_nfl_team FROM conform_era e
          WHERE e.era_nfl_team = p.draft_team
            AND p.nfl_draft_year >= e.start_year
            AND (e.end_year IS NULL OR p.nfl_draft_year <= e.end_year)),
        (SELECT a.canonical_nfl_team FROM conform_alias a WHERE a.alias = p.draft_team),
        p.draft_team
      ) IS DISTINCT FROM p.draft_team
  ) residual INTO actual;
  IF actual <> 0 THEN
    RAISE EXCEPTION 'POST residual non-conforming slots, before 2000: expected 0, found %', actual;
  END IF;
  RAISE NOTICE 'POST residual non-conforming slots, before 2000: % (as expected)', actual;
END $$;

DO $$
DECLARE actual bigint;
BEGIN
  SELECT count(*) FROM nfl_games INTO actual;
  IF actual <> 15622 THEN
    RAISE EXCEPTION 'POST nfl_games row count unchanged: expected 15622, found %', actual;
  END IF;
  RAISE NOTICE 'POST nfl_games row count unchanged: % (as expected)', actual;
END $$;

DO $$
DECLARE actual bigint;
BEGIN
  SELECT count(*) FROM (
    SELECT away_nfl_team AS t FROM nfl_games
    UNION ALL SELECT home_nfl_team FROM nfl_games
  ) s WHERE s.t IN ('AFC','NFC','IRV','RIC','SAN','CRT','INA') INTO actual;
  IF actual <> 40 THEN
    RAISE EXCEPTION 'POST non-franchise slots still 40: expected 40, found %', actual;
  END IF;
  RAISE NOTICE 'POST non-franchise slots still 40: % (as expected)', actual;
END $$;
